import type { Product } from "@/types";
import { p } from "./_helper";

/** Pet Care — 10 products. Loaded lazily by the catalogue hook. */
export const products: Product[] = [
  p("p207", "Pedigree Adult Chicken & Veg", "पेडिग्री एडल्ट डॉग फूड", "Complete balanced nutrition for adult dogs — real chicken and vegetables", "20", 430, 470, "1.2 kg", 30),
  p("p208", "Pedigree Puppy Chicken & Milk", "पेडिग्री पपी फूड", "Pro-Health Start formula — chicken, milk and DHA for growing puppies", "20", 445, 485, "1.2 kg", 25),
  p("p209", "Royal Canin Mini Adult", "रॉयल केनिन मिनी एडल्ट", "Premium kibble for small breed adult dogs 1-8 years — balanced complete nutrition", "20", 1295, 1450, "2 kg", 15),
  p("p210", "Drools Adult Chicken & Egg", "ड्रूल्स एडल्ट डॉग फूड", "Real chicken first ingredient — omega-3, shiny coat formula", "20", 525, 595, "3 kg", 20),
  p("p211", "Whiskas Adult Ocean Fish", "व्हिस्कस ओशन फिश कैट फूड", "Adult cat dry food with ocean fish — taurine for heart and vision health", "20", 415, 460, "1.1 kg", 25),
  p("p212", "Whiskas Kitten Ocean Fish", "व्हिस्कस किटन फूड", "Specially formulated for 2-12 month kittens — DHA for brain, milk calcium", "20", 366, 425, "1.1 kg", 25),
  p("p213", "Sheba Adult Wet Cat Food Skipjack", "शीबा वेट कैट फूड", "Gourmet wet cat food with skipjack tuna in gravy — premium daily nutrition", "20", 50, 55, "35 g", 50),
  p("p214", "Drools Wet Puppy Food", "ड्रूल्स पपी वेट फूड", "Real chicken liver chunks in gravy for puppies — high palatability, complete meal", "20", 233, 260, "6 x 150 g", 25),
  p("p215", "Goofy Tails Chicken Dog Chew", "गूफी टेल्स डॉग चू", "Long-lasting chicken-flavour dog chew sticks — dental health, training treat", "20", 199, 245, "200 g", 35),
  p("p216", "Drools Cat Litter Clumping", "ड्रूल्स कैट लिटर", "Bentonite clumping cat litter — fast-absorbing, lavender scented, easy clean-up", "20", 425, 475, "5 kg", 20),
  p("p1045", "Pedigree Adult Beef Veg 3kg", "पेडिग्री एडल्ट बीफ", "Pedigree Adult Dry Dog Food Beef and Vegetables — complete daily nutrition", "20", 985, 1095, "3 kg", 18),
  p("p1046", "Pedigree Adult Chicken Veg 3kg", "पेडिग्री एडल्ट चिकन", "Pedigree Adult Dry Dog Food Chicken and Vegetables — balanced complete nutrition", "20", 985, 1095, "3 kg", 20),
  p("p1047", "Pedigree Roasted Chicken Treats", "पेडिग्री रोस्टेड चिकन ट्रीट्स", "Pedigree Roasted Chicken Adult Dog Treats — training reward, real chicken", "20", 145, 175, "80 g", 30),
  p("p1048", "Pedigree Dentastix", "पेडिग्री डेंटास्टिक्स", "Pedigree Dentastix Daily Dental Chew — reduces tartar buildup, fresh breath", "20", 245, 285, "180 g", 25),
  p("p1049", "Drools Wet Food Chicken Liver", "ड्रूल्स वेट चिकन लिवर", "Drools Wet Food Adult Chicken Liver in Gravy — premium real meat chunks", "20", 65, 75, "150 g", 35),
  p("p1050", "Royal Canin Maxi Adult", "रॉयल केनिन मैक्सी", "Royal Canin Maxi Adult Dog Food — large breed 26-44 kg, joint and muscle support", "20", 3850, 4250, "4 kg", 12),
  p("p1051", "Royal Canin Mini Indoor Adult", "रॉयल केनिन मिनी इंडोर", "Royal Canin Mini Indoor Adult Dog Food — small breed, urban lifestyle nutrition", "20", 2495, 2750, "1.5 kg", 12),
  p("p1052", "Hill's Science Diet Adult", "हिल्स साइंस डाइट एडल्ट", "Hill's Science Diet Adult Dog Food Chicken and Barley — premium daily nutrition", "20", 2895, 3250, "2 kg", 10),
  p("p1053", "Purina Pro Plan Adult", "प्यूरिना प्रो प्लान", "Purina Pro Plan Adult Dog Food Chicken and Rice — high-protein performance formula", "20", 2495, 2795, "2.5 kg", 12),
  p("p1054", "Whiskas Junior Dog", "व्हिस्कस जूनियर डॉग", "Whiskas Junior Dog Food — for growing puppies, real chicken and milk", "20", 425, 475, "1.2 kg", 22),
  p("p1055", "Whiskas Adult Tuna 1.1kg", "व्हिस्कस एडल्ट टूना", "Whiskas Adult Cat Food Tuna — real fish, taurine for heart and vision health", "20", 415, 460, "1.1 kg", 25),
  p("p1056", "Whiskas Mackerel Tuna Wet", "व्हिस्कस मैकेरल टूना वेट", "Whiskas Adult Mackerel and Tuna Wet Food — gourmet pouch, complete meal", "20", 50, 55, "85 g", 50),
  p("p1057", "Sheba Rich Tuna Salmon", "शीबा रिच टूना सैल्मन", "Sheba Rich Tuna and Salmon Wet Cat Food — gourmet flavours, premium quality", "20", 65, 75, "70 g", 45),
  p("p1058", "Royal Canin Indoor Cat", "रॉयल केनिन इंडोर कैट", "Royal Canin Indoor Adult Cat Food — for indoor cats, hairball control", "20", 2195, 2450, "2 kg", 12),
  p("p1059", "Hill's Science Diet Cat", "हिल्स साइंस डाइट कैट", "Hill's Science Diet Adult Cat Food Chicken — premium daily nutrition for cats", "20", 2495, 2795, "2 kg", 10),
  p("p1060", "Me-O Adult Cat Food Tuna", "मी-ओ एडल्ट कैट फूड", "Me-O Adult Cat Food Tuna — premium dry food, taurine and DHA enriched", "20", 425, 475, "1.2 kg", 25),
  p("p1061", "Purepet Cat Adult Ocean Fish", "प्योरपेट कैट ओशन फिश", "Purepet Adult Cat Food Ocean Fish — economical premium nutrition with vitamins", "20", 285, 325, "1.2 kg", 25),
  p("p1062", "Pedigree Jumbone Medium", "पेडिग्री जंबोन मीडियम", "Pedigree Jumbone Medium Dog Chew — long-lasting beef flavour chew, dental health", "20", 165, 195, "180 g", 25),
  p("p1063", "Dingo Bones Beef Chips", "डिंगो बीफ चिप्स", "Dingo Bones Beef Chips — premium rawhide chew with real meat wrap", "20", 245, 285, "150 g", 22),
  p("p1064", "Pedigree Schmackos", "पेडिग्री श्मैकोस", "Pedigree Schmackos Beef Treats — soft training treats, rich in meat", "20", 175, 195, "60 g", 30),
  p("p1065", "Drools Dental Chew Sticks", "ड्रूल्स डेंटल चू स्टिक्स", "Drools Daily Dental Chew Sticks — promotes dental hygiene, reduces tartar", "20", 145, 165, "200 g", 25),
  p("p1066", "Goofy Tails Squeaky Toy", "गूफी टेल्स स्क्वीकी टॉय", "Goofy Tails Squeaky Dog Toy — soft plush with sound, interactive play", "20", 245, 295, "1 pc", 20),
  p("p1067", "Pet Bowl Stainless Steel", "पेट बाउल स्टेनलेस स्टील", "Premium Stainless Steel Pet Bowl — rust-proof, dishwasher safe, anti-skid base", "20", 195, 225, "1 pc", 25),
  p("p1068", "Beaphar Dog Shampoo", "बीफार डॉग शैम्पू", "Beaphar Macadamia Oil Dog Shampoo — gentle cleansing, shiny coat, 250 ml", "20", 345, 395, "250 ml", 20),
  p("p1069", "Pet Carrier Bag", "पेट कैरियर बैग", "Premium Pet Carrier Bag — breathable mesh, comfortable for small pets travel", "20", 985, 1195, "1 pc", 12),
];
