import type { Product } from "@/types";
import { p } from "./_helper";

/** Dairy, Bread & Eggs — 35 products. Loaded lazily by the catalogue hook. */
export const products: Product[] = [
  p("p19", "Amul Taaza Milk", "अमूल ताज़ा दूध", "Amul Taaza pasteurised toned milk — 3% fat, perfect for chai, coffee, and daily use", "2", 28, 30, "500 ml", 40),
  p("p20", "Amul Gold Milk", "अमूल गोल्ड दूध", "Amul Gold full cream milk — 6% fat, rich and creamy, ideal for kheer and sweets", "2", 34, 36, "500 ml", 35),
  p("p21", "Mother Dairy Milk", "मदर डेयरी दूध", "Mother Dairy full cream pasteurised milk — fresh, thick, and rich in protein", "2", 32, 34, "500 ml", 30),
  p("p22", "Amul Butter", "अमूल मक्खन", "Amul pasteurised butter — utterly butterly delicious, perfect for parathas and toast", "2", 56, 58, "100 g", 25),
  p("p23", "Bread (White)", "ब्रेड सफ़ेद", "Soft white bread loaf, freshly baked — ideal for sandwiches and breakfast toast", "2", 40, 45, "400 g", 20),
  p("p24", "Bread (Brown/Wheat)", "ब्रेड ब्राउन", "Whole wheat brown bread — high-fibre, healthier choice for everyday breakfast", "2", 45, 50, "400 g", 18),
  p("p25", "Paneer (Fresh)", "पनीर", "Soft fresh paneer, made daily — high-protein, perfect for paneer butter masala and tikka", "2", 80, 90, "200 g", 15),
  p("p26", "Dahi (Curd)", "दही", "Thick fresh curd (dahi) — naturally fermented, great for raita, lassi, and digestion", "2", 30, 35, "400 g", 30),
  p("p27", "Amul Cheese Slices", "अमूल चीज़ स्लाइस", "Amul processed cheese slices — melts smoothly, perfect for sandwiches and burgers", "2", 95, 105, "200 g (10 slices)", 20),
  p("p28", "Amul Lassi Mango", "अमूल लस्सी आम", "Amul Mango Lassi — chilled creamy mango drink, ready to enjoy", "2", 25, 25, "200 ml", 40),
  p("p29", "Egg (Anda)", "अंडा", "Farm-fresh table eggs — rich in protein, white shell, ideal for omelette and bhurji", "2", 75, 84, "6 pcs", 25),
  p("p30", "Cream (Amul)", "अमूल क्रीम", "Amul fresh cream — rich and silky, use in soups, gravies, and desserts", "2", 42, 45, "200 ml", 15),
  p("p288", "Amul Buffalo Milk", "अमूल भैंस का दूध", "High-fat buffalo milk — ideal for ghee, paneer and rich chai (6% fat)", "2", 40, 42, "500 ml", 50),
  p("p289", "Nestle a+ Slim Toned Milk", "नेस्ले a+ टोन्ड दूध", "Nestle a+ slim toned milk — low-fat daily milk in tetra pack", "2", 85, 90, "1 L", 35),
  p("p290", "Mother Dairy Toned Milk", "मदर डेयरी टोन्ड", "Fresh toned cow milk pouch — for chai, coffee and daily use", "2", 32, 34, "500 ml", 60),
  p("p291", "Amul Slim 'n' Trim Milk", "अमूल स्लिम मिल्क", "Double-toned skim milk — low fat for weight watchers", "2", 30, 32, "500 ml", 40),
  p("p292", "Amul Masti Dahi Family Pack", "अमूल मस्ती दही", "Thick fresh curd in family pack — perfect with parathas and raita", "2", 75, 80, "1 kg", 45),
  p("p293", "Britannia Dahi Cup", "ब्रिटानिया दही", "Smooth set curd in handy cup — ideal for tiffin and lassi", "2", 35, 38, "400 g", 50),
  p("p294", "Amul Masala Chaas", "अमूल छाछ", "Spiced masala chaas with jeera — refreshing summer drink", "2", 18, 20, "200 ml", 65),
  p("p295", "Mother Dairy Lassi", "मदर डेयरी लस्सी", "Sweet creamy lassi pack — classic Punjabi-style summer cooler", "2", 30, 32, "200 ml", 55),
  p("p296", "Amul Mishti Doi", "अमूल मिष्टी दही", "Traditional Bengali sweetened curd — caramel-flavoured dessert", "2", 50, 55, "400 g", 30),
  p("p297", "Epigamia Greek Yogurt Natural", "एपिगामिया ग्रीक योगर्ट", "High-protein Greek yogurt — thick and creamy, perfect post-workout", "2", 75, 80, "90 g", 35),
  p("p298", "Amul Cheese Cubes", "अमूल चीज़ क्यूब्स", "Bite-sized processed cheese cubes for tiffin and snacks — 10 cubes", "2", 135, 145, "200 g", 40),
  p("p299", "Britannia Cheese Spread", "ब्रिटानिया चीज़ स्प्रेड", "Creamy spreadable cheese for bread, sandwiches and wraps", "2", 110, 120, "180 g", 35),
  p("p300", "Mother Dairy Paneer", "मदर डेयरी पनीर", "Fresh soft paneer block — perfect for paneer butter masala and tikka", "2", 105, 115, "200 g", 50),
  p("p301", "Amul Shrikhand Elaichi", "अमूल श्रीखंड इलायची", "Traditional Gujarati shrikhand with cardamom — festive dessert", "2", 75, 80, "200 g", 25),
  p("p302", "Britannia Mozzarella Cheese", "मोज़ेरेला चीज़", "Stretchy mozzarella for pizza, pasta and garlic bread", "2", 285, 320, "200 g", 30),
  p("p303", "Amul Processed Cheese Block", "अमूल चीज़ ब्लॉक", "Versatile cheese block — slice or grate for sandwiches and bakes", "2", 245, 260, "400 g", 35),
  p("p304", "English Oven Multigrain Bread", "इंग्लिश ओवन मल्टीग्रेन", "Healthy 7-grain loaf — oven-baked daily, rich in fibre", "2", 70, 75, "400 g", 40),
  p("p305", "Britannia Whole Wheat Brown Bread", "ब्रिटानिया होल व्हीट", "Pure whole wheat brown bread — zero maida, healthier daily choice", "2", 55, 60, "400 g", 45),
  p("p306", "Britannia Pav Buns", "ब्रिटानिया पाव", "Soft small buns — perfect with pav bhaji and vada pav (8 pcs)", "2", 40, 45, "200 g", 50),
  p("p307", "Britannia Burger Buns", "बर्गर बन्स", "Soft sesame-top burger buns for veggie and paneer burgers (6 pcs)", "2", 70, 80, "300 g", 35),
  p("p308", "Country Farm Eggs (8 pc)", "देसी अंडे", "Free-range desi farm eggs — naturally raised, brown shell", "2", 110, 120, "8 pcs", 40),
  p("p309", "Brown Eggs (6 pc)", "ब्राउन अंडे", "High-protein brown eggs — hand-picked and sanitised", "2", 75, 85, "6 pcs", 45),
  p("p310", "Mother Dairy Strawberry Yogurt", "स्ट्राबेरी योगर्ट", "Fruity strawberry-flavoured yogurt — kid-friendly tiffin treat", "2", 25, 30, "85 g", 50),
  p("p1070", "Amul Cow Ghee", "अमूल गाय का घी", "Pure cow milk ghee — rich golden aroma, traditional dana-dana texture for daal and roti", "2", 645, 700, "1 L", 30),
  p("p1071", "Amul Buffalo Ghee 500ml", "अमूल भैंस का घी", "Rich buffalo milk ghee — granular texture, ideal for halwa and tadka", "2", 320, 345, "500 ml", 35),
  p("p1072", "Patanjali Cow Ghee 500ml", "पतंजलि गाय घी", "Patanjali pure desi cow ghee — bilona-style, aromatic and pure", "2", 365, 395, "500 ml", 40),
  p("p1073", "Heritage Cow Ghee 1L", "हेरिटेज गाय घी", "Heritage premium cow ghee — slow-churned, rich nutty aroma", "2", 685, 750, "1 L", 25),
  p("p1074", "Mother Dairy Cow Ghee 500ml", "मदर डेयरी घी", "Mother Dairy pure cow ghee — pasteurised, granular texture", "2", 360, 390, "500 ml", 35),
  p("p1075", "Amul Set Curd Cup 200g", "अमूल सेट दही कप", "Thick set curd in handy single-serve cup — perfect for tiffin", "2", 22, 25, "200 g", 60),
  p("p1076", "Britannia Set Curd 400g", "ब्रिटानिया सेट दही", "Thick creamy set curd — fresh daily, ideal for raita and lassi", "2", 45, 50, "400 g", 50),
  p("p1077", "Heritage Curd Cup 400g", "हेरिटेज दही", "Heritage thick fresh curd — high protein, smooth set texture", "2", 50, 55, "400 g", 45),
  p("p1078", "Mother Dairy Mishti Doi Cup", "मदर डेयरी मिष्टी दही", "Bengali-style sweetened curd cup — caramel notes, traditional dessert", "2", 35, 40, "85 g", 55),
  p("p1079", "Amul Probiotic Lassi", "अमूल प्रोबायोटिक लस्सी", "Probiotic sweet lassi with live cultures — refreshing and gut-friendly", "2", 25, 28, "200 ml", 50),
  p("p1080", "Britannia Yogurt Mango", "ब्रिटानिया मैंगो योगर्ट", "Mango-flavoured fruit yogurt — kid favourite, with real mango bits", "2", 25, 30, "85 g", 50),
  p("p1081", "Britannia Yogurt Strawberry", "ब्रिटानिया स्ट्राबेरी योगर्ट", "Strawberry-flavoured creamy fruit yogurt — tangy-sweet tiffin pack", "2", 25, 30, "85 g", 50),
  p("p1082", "Epigamia Mango Yogurt 90g", "एपिगामिया मैंगो योगर्ट", "Greek mango yogurt — high-protein, real Alphonso mango pulp", "2", 60, 65, "90 g", 40),
  p("p1083", "Epigamia Aam Ras Yogurt", "एपिगामिया आम रस", "Greek yogurt blended with Alphonso aam ras — thick and indulgent", "2", 60, 65, "90 g", 40),
  p("p1084", "Yakult Light Probiotic Drink", "याकल्ट लाइट", "Yakult light probiotic drink — 6.5 billion good bacteria per bottle, daily gut health", "2", 90, 95, "5 x 65 ml", 35),
  p("p1085", "Epigamia Greek Yogurt Honey", "एपिगामिया हनी योगर्ट", "Greek yogurt sweetened with raw honey — high-protein indulgent breakfast", "2", 60, 65, "90 g", 40),
  p("p1086", "Brown Eggs Tray 30pc", "ब्राउन अंडे ट्रे", "Farm-fresh brown eggs in 30pc bulk tray — high-protein, sanitised", "2", 295, 320, "30 pcs", 30),
  p("p1087", "White Eggs Tray 30pc", "सफेद अंडे ट्रे", "Hand-picked white shell eggs in family pack tray — kitchen essential", "2", 245, 270, "30 pcs", 35),
  p("p1088", "Country Eggs 12 pc", "देसी अंडे 12", "Free-range desi country eggs — naturally raised, vibrant yolks", "2", 155, 170, "12 pcs", 30),
  p("p1089", "Pasteurised White Eggs 12pc", "पाश्चराइज़्ड अंडे", "Pasteurised white eggs — safe for raw use in salads and smoothies", "2", 135, 145, "12 pcs", 35),
  p("p1090", "Modern Multigrain Bread", "मॉडर्न मल्टीग्रेन ब्रेड", "Modern 9-grain healthy multigrain bread loaf — rich fibre and protein", "2", 60, 65, "400 g", 40),
  p("p1091", "English Oven Atta Bread", "इंग्लिश ओवन आटा ब्रेड", "Whole wheat atta bread — soft texture, zero maida, oven-baked daily", "2", 65, 70, "400 g", 45),
  p("p1092", "Britannia Whole Wheat Buns", "ब्रिटानिया होल व्हीट बन्स", "Soft whole wheat burger buns — healthier 6pc pack for sandwiches", "2", 75, 85, "300 g", 35),
  p("p1093", "Britannia Pizza Base 2pc", "ब्रिटानिया पिज़्ज़ा बेस", "Pre-baked Italian-style 7-inch pizza bases — ready to top and bake", "2", 95, 110, "200 g (2 pcs)", 30),
  p("p1094", "Britannia Slim Cheese Slices", "ब्रिटानिया स्लिम चीज़", "Britannia low-fat slim cheese slices — guilt-free sandwich essential", "2", 105, 115, "200 g (10 slices)", 35),
];
