import type { Product } from "@/types";
import { p } from "./_helper";

/** Breakfast & Instant Food — 12 products. Loaded lazily by the catalogue hook. */
export const products: Product[] = [
  p("p98", "Maggi 2-Minute Noodles", "मैगी नूडल्स", "Maggi 2-Minute Noodles — masala flavour, India's iconic quick snack", "6", 14, 15, "70 g", 100),
  p("p99", "Maggi Masala (4-Pack)", "मैगी मसाला 4-पैक", "Maggi Masala Noodles 4-Pack — family pack value, kids' all-time favourite", "6", 52, 60, "280 g", 40),
  p("p100", "Yippee Noodles", "यिप्पी नूडल्स", "Sunfeast YiPPee Magic Masala — slim long noodles, spicy masala flavour", "6", 14, 16, "70 g", 60),
  p("p101", "Top Ramen Curry", "टॉप रामेन करी", "Nissin Top Ramen Curry — Japanese-style curry noodles, ready in 3 minutes", "6", 14, 16, "70 g", 35),
  p("p102", "MTR Ready Meal - Paneer Butter Masala", "MTR पनीर बटर मसाला", "MTR Paneer Butter Masala — ready-to-eat rich gravy, restaurant taste at home", "6", 85, 99, "300 g", 20),
  p("p103", "MTR Ready Meal - Dal Makhani", "MTR दाल मखनी", "MTR Dal Makhani — slow-cooked creamy dal, just heat and eat", "6", 75, 89, "300 g", 18),
  p("p104", "Haldiram Minute Khana - Rajma Chawal", "हल्दीराम राजमा चावल", "Haldiram's Rajma Chawal — complete ready-to-eat North Indian meal", "6", 90, 105, "375 g", 12),
  p("p105", "Knorr Soup - Tomato", "नॉर टमाटर सूप", "Knorr Classic Tomato Soup — smooth instant soup mix, warm comfort in a bowl", "6", 45, 50, "51 g", 30),
  p("p106", "Ching's Schezwan Noodles", "चिंग्स शेजवान", "Ching's Schezwan Noodles — desi-Chinese fiery spice, restaurant-style", "6", 25, 30, "60 g", 40),
  p("p107", "Saffola Oats", "सैफोला ओट्स", "Saffola Classic Oats — 100% whole grain, fibre-rich healthy breakfast", "6", 99, 115, "500 g", 15),
  p("p108", "Kellogg's Cornflakes", "कैलॉग्स कॉर्नफ्लेक्स", "Kellogg's Original Cornflakes — golden crunchy flakes, iron-fortified breakfast", "6", 165, 185, "475 g", 12),
  p("p109", "Upma Mix (MTR)", "एमटीआर उपमा मिक्स", "MTR Instant Upma Mix — South Indian breakfast ready in minutes", "6", 50, 58, "200 g", 20),
  p("p670", "Maggi Atta Noodles", "मैगी आटा नूडल्स", "Whole-wheat atta noodles in masala flavour — wholesome quick snack", "6", 16, 18, "75 g", 60),
  p("p671", "Maggi Cuppa Noodles Masala", "मैगी कप्पा नूडल्स मसाला", "Ready-to-eat masala cup noodles — just add hot water", "6", 35, 40, "70 g", 45),
  p("p672", "Maggi Cuppa Noodles Curry", "मैगी कप्पा करी", "Spicy curry-flavoured cup noodles — instant office snack", "6", 35, 40, "70 g", 40),
  p("p673", "Maggi Pazzta Cheese Macaroni", "मैगी पाज़ा चीज़", "Cheesy macaroni pasta with creamy cheese sauce — kids' meal", "6", 50, 55, "65 g", 35),
  p("p674", "Sunfeast YiPPee Power Up", "यिप्पी पावर अप", "Atta-based noodles with iron and proteins — healthier slim noodles", "6", 18, 20, "70 g", 50),
  p("p675", "Sunfeast YiPPee Tricolour", "यिप्पी ट्राइकलर", "Tricolour vegetable noodles with magic masala — fun mealtime", "6", 18, 20, "70 g", 45),
  p("p676", "Top Ramen Smoodles Masala", "टॉप रामेन स्मूडल्स", "Smooth slurpy noodles in zesty masala — Nissin's signature instant", "6", 14, 16, "70 g", 40),
  p("p677", "Ching's Singapore Curry Noodles", "चिंग्स सिंगापुर करी", "Desi-Chinese Singapore curry noodles — fiery street-style taste", "6", 25, 30, "60 g", 40),
  p("p678", "Ching's Hakka Noodles", "चिंग्स हक्का", "Authentic restaurant-style hakka noodles — quick stir-fry meal", "6", 25, 30, "60 g", 40),
  p("p679", "Wai Wai Veg Noodles", "वाई वाई वेज नूडल्स", "Ready-to-eat crunchy noodle snack — eat straight from pack", "6", 18, 20, "70 g", 50),
  p("p680", "Knorr Soupy Noodles Mast Masala", "नॉर सूपी नूडल्स", "Tangy soupy noodles in mast masala — slurp-worthy comfort snack", "6", 25, 30, "70 g", 40),
  p("p681", "Knorr Sweet Corn Veg Soup", "नॉर स्वीट कॉर्न सूप", "Sweet corn veg soup mix — Chinese-style instant warm bowl", "6", 50, 55, "44 g", 30),
  p("p682", "MTR Khichdi Mix", "MTR खिचड़ी मिक्स", "Instant moong dal khichdi mix — wholesome one-pot meal in minutes", "6", 65, 75, "200 g", 25),
  p("p683", "MTR Poha Mix", "MTR पोहा मिक्स", "Authentic Maharashtrian poha mix with peanuts — quick breakfast", "6", 55, 65, "180 g", 30),
  p("p684", "MTR Vermicelli Upma Mix", "MTR सेवइयाँ उपमा", "Roasted vermicelli upma mix with veggies — light breakfast", "6", 55, 65, "200 g", 25),
  p("p685", "MTR Oats Khichdi", "MTR ओट्स खिचड़ी", "Healthy oats-based khichdi with veggies and spices — fibre breakfast", "6", 70, 80, "200 g", 25),
  p("p686", "MTR Halwa Mix", "MTR हलवा मिक्स", "Instant rava-suji halwa mix — South Indian dessert in 5 minutes", "6", 95, 110, "500 g", 20),
  p("p687", "MTR Idli Mix", "MTR इडली मिक्स", "Instant idli mix for soft fluffy steamed cakes — South Indian classic", "6", 105, 120, "500 g", 25),
  p("p688", "MTR Dosa Batter", "MTR डोसा बैटर", "Ready-to-use dosa batter — restaurant-quality crispy dosa at home", "6", 90, 105, "1 kg", 20),
  p("p689", "MTR Sambhar Powder", "MTR सांभर पाउडर", "Authentic South Indian sambhar masala blend — restaurant taste", "6", 80, 90, "200 g", 25),
  p("p690", "MTR Bisi Bele Bath Mix", "MTR बिसी बेले बाथ", "Karnataka spicy rice-lentil dish mix — wholesome one-pot meal", "6", 75, 85, "200 g", 20),
  p("p691", "Gits Khaman Dhokla Mix", "गिट्स खमण ढोकला", "Soft spongy Gujarati khaman dhokla mix — steam-cook snack", "6", 95, 105, "200 g", 25),
  p("p692", "Gits Gulab Jamun Mix", "गिट्स गुलाब जामुन मिक्स", "Ready khoya mix for soft gulab jamuns — festive sweet at home", "6", 95, 110, "200 g", 30),
  p("p693", "Gits Idli Mix", "गिट्स इडली मिक्स", "Fermented rice-dal idli mix — fluffy steamed idlis in 30 min", "6", 100, 115, "500 g", 25),
  p("p694", "Patanjali Atta Noodles", "पतंजलि आटा नूडल्स", "Healthy whole-wheat atta noodles with desi spices — no maida", "6", 16, 18, "70 g", 40),
  p("p695", "Saffola Masala Oats Veggie Twist", "सैफोला मसाला ओट्स", "Tasty masala oats with veggies — high-fibre breakfast in 3 min", "6", 35, 40, "40 g", 45),
  p("p696", "Bagrry's Crunchy Muesli", "बैग्रीज़ क्रंची मूसली", "Crunchy oats muesli with fruits and nuts — premium fibre breakfast", "6", 365, 410, "750 g", 20),
  p("p697", "Yoga Bar Muesli Nuts & Seeds", "योगा बार मूसली", "Wholegrain muesli with nuts and seeds — no sugar, healthy breakfast", "6", 425, 480, "700 g", 18),
  p("p698", "Quaker Oats Original 1kg", "क्वेकर ओट्स 1kg", "100% whole-grain rolled oats — heart-healthy fibre breakfast", "6", 215, 240, "1 kg", 25),
  p("p699", "Patanjali Honey Oats", "पतंजलि हनी ओट्स", "Whole-grain oats with natural honey flavour — wholesome breakfast", "6", 145, 165, "500 g", 25),
  p("p700", "Kellogg's Chocos", "कैलॉग्स चोकोस", "Chocolate-flavoured wheat scoops — kids' chocolatey breakfast", "6", 245, 275, "375 g", 20),
  p("p701", "Kellogg's Cornflakes Real Strawberry", "कैलॉग्स स्ट्रॉबेरी", "Crunchy cornflakes with real strawberry pieces — fruity breakfast", "6", 195, 220, "300 g", 22),
  p("p702", "Kellogg's Muesli with Almonds", "कैलॉग्स मूसली बादाम", "Wholesome muesli with crunchy almonds and raisins — fibre breakfast", "6", 365, 410, "500 g", 20),
  p("p703", "Bagrry's Granola Almonds & Honey", "बैग्रीज़ ग्रनोला", "Crunchy granola clusters with almonds and honey — premium breakfast", "6", 425, 475, "450 g", 18),
  p("p704", "Patanjali Cornflakes", "पतंजलि कॉर्नफ्लेक्स", "Crunchy golden cornflakes fortified with vitamins — value pack", "6", 145, 165, "500 g", 25),
];
