import type { Product } from "@/types";
import { p } from "./_helper";

/** Bakery & Biscuits — 22 products. Loaded lazily by the catalogue hook. */
export const products: Product[] = [
  p("p72", "Parle-G Biscuits", "पारले-जी", "Parle-G Original Glucose Biscuits — India's favourite, energy in every bite", "8", 10, 10, "80 g", 80),
  p("p73", "Britannia Good Day", "ब्रिटानिया गुड डे", "Britannia Good Day Butter Cookies — buttery, rich, melt-in-mouth cookies", "8", 30, 30, "75 g", 45),
  p("p74", "Britannia Marie Gold", "ब्रिटानिया मारी गोल्ड", "Britannia Marie Gold — light, crispy tea-time biscuit, India's classic choice", "8", 30, 30, "250 g", 40),
  p("p75", "Dark Fantasy Choco Fills", "डार्क फैंटेसी", "Sunfeast Dark Fantasy Choco Fills — crunchy outside, molten chocolate inside", "8", 40, 45, "75 g", 35),
  p("p76", "Oreo Biscuit", "ओरियो", "Cadbury Oreo Vanilla Cream — chocolate biscuit with classic vanilla filling", "8", 30, 35, "120 g", 50),
  p("p236", "Britannia Bourbon Original", "ब्रिटानिया बोरबॉन", "Classic chocolate cream sandwich biscuit — iconic Indian tea-time favourite", "8", 45, 50, "150 g", 50),
  p("p237", "Sunfeast Bounce Elaichi", "सनफीस्ट बाउंस इलायची", "Crisp biscuit with creamy elaichi cream filling — ITC family pack", "8", 30, 35, "120 g", 45),
  p("p238", "Britannia Tiger Glucose", "ब्रिटानिया टाइगर ग्लूकोज़", "Energy-rich glucose biscuit for kids — India's most loved kids' biscuit", "8", 25, 30, "200 g", 50),
  p("p239", "Britannia 50-50 Maska Chaska", "ब्रिटानिया 50-50 मस्का चस्का", "Salty-sweet butter biscuit with chatpata masala twist — namkeen biscuit", "8", 30, 35, "120 g", 45),
  p("p240", "Britannia Hide & Seek Choco", "ब्रिटानिया हाइड एंड सीक", "Choco-chip cookies loaded with real chocolate chunks — premium snack", "8", 30, 35, "100 g", 50),
  p("p241", "Britannia NutriChoice Digestive", "ब्रिटानिया न्यूट्रीचॉइस", "High-fibre wheat digestive biscuit — healthy choice for daily tea", "8", 75, 85, "250 g", 40),
  p("p242", "Anmol Cream Biscuits Vanilla", "अनमोल वनिला क्रीम", "Smooth vanilla cream sandwich biscuit — value family pack price", "8", 25, 30, "200 g", 45),
  p("p243", "Britannia Treat Jim Jam", "ब्रिटानिया जिम जैम", "Vanilla biscuit sandwich with jam dot centre — kids' lunchbox favourite", "8", 35, 40, "100 g", 45),
  p("p244", "Britannia Milk Bikis", "ब्रिटानिया मिल्क बिकिस", "Milk-rich biscuit with goodness of dairy — classic teatime dunker", "8", 30, 35, "200 g", 50),
  p("p245", "Britannia Premium Rusk", "ब्रिटानिया प्रीमियम रस्क", "Crispy elaichi-flavoured tea rusk — perfectly toasted for chai dunking", "8", 80, 90, "350 g", 40),
  p("p246", "Bakers Bite Suji Rusk", "बेकर्स बाइट सूजी रस्क", "Crunchy suji and elaichi rusk — family pack for everyday breakfast", "8", 70, 80, "400 g", 35),
  p("p247", "Britannia Pure Magic Choco", "ब्रिटानिया प्योर मैजिक", "Premium chocolate sandwich biscuit with rich cocoa cream filling", "8", 40, 45, "75 g", 45),
  p("p248", "Cremica Chocolate Wafer", "क्रेमिका चॉकलेट वेफर", "Crispy multi-layer chocolate wafer — light and crunchy snack", "8", 30, 35, "75 g", 45),
  p("p249", "Britannia Tiger Krunch Chocochips", "टाइगर क्रंच चोको चिप्स", "Crunchy cookie loaded with chocolate chips — kids' afterschool snack", "8", 25, 30, "75 g", 50),
  p("p250", "Sunfeast Marie Light", "सनफीस्ट मैरी लाइट", "Light and crisp marie biscuit — perfect low-fat tea companion", "8", 25, 30, "200 g", 50),
  p("p251", "Britannia Cake Slice Vanilla", "ब्रिटानिया केक स्लाइस वनिला", "Soft vanilla sponge cake slice — ready-to-eat snack for tiffin and travel", "8", 40, 45, "6 pcs", 35),
  p("p252", "Britannia Chocolate Bar Cake", "ब्रिटानिया चॉकलेट बार केक", "Soft eggless chocolate bar cake — individually wrapped tiffin pack", "8", 50, 55, "6 pcs", 35),
  p("p545", "Britannia 50-50 Sweet & Salty", "ब्रिटानिया 50-50 स्वीट सॉल्टी", "Britannia 50-50 Sweet & Salty — perfect balance of sweet and salty crunch", "8", 30, 35, "120 g", 45),
  p("p546", "Britannia Cream Treat Strawberry", "ब्रिटानिया स्ट्रॉबेरी क्रीम", "Britannia Treat Strawberry Cream Biscuit — creamy berry sandwich biscuit", "8", 30, 35, "100 g", 50),
  p("p547", "Britannia Treat Crackers", "ब्रिटानिया ट्रीट क्रैकर", "Britannia Treat Crackers Salted — crispy savoury cream cracker", "8", 25, 30, "150 g", 45),
  p("p548", "Britannia Treat Choco Vanilla", "ट्रीट चोको वनिला", "Britannia Treat Choco-Vanilla — twin cream sandwich biscuit, kids' favourite", "8", 30, 35, "120 g", 45),
  p("p549", "Britannia Pure Magic Stars", "प्योर मैजिक स्टार्स", "Britannia Pure Magic Stars — star-shaped biscuit with chocolate cream", "8", 40, 45, "75 g", 40),
  p("p550", "Britannia Hide & Seek Black Bourbon", "हाइड एंड सीक बोरबॉन", "Hide & Seek Black Bourbon — premium dark chocolate sandwich biscuit", "8", 35, 40, "100 g", 45),
  p("p551", "Britannia Time Pass Classic Salted", "टाइम पास", "Britannia Time Pass Classic Salted — square salty biscuit, chai's best friend", "8", 20, 25, "200 g", 50),
  p("p552", "Britannia Toastea Coffee Rusk", "टोस्टी कॉफी रस्क", "Britannia Toastea Coffee Premium Rusk — coffee-flavoured tea rusk", "8", 95, 105, "300 g", 30),
  p("p553", "Britannia Toastea Elaichi Rusk", "टोस्टी इलायची", "Britannia Toastea Premium Elaichi Rusk — fragrant cardamom-flavoured rusk", "8", 90, 100, "300 g", 35),
  p("p554", "Britannia Petit Beurre", "पेटिट बर्र", "Britannia Petit Beurre — classic French-style butter biscuit, delicate", "8", 40, 45, "120 g", 30),
  p("p555", "Marie Tidda Britannia", "मैरी तिड्डा", "Britannia Marie Tidda — small bite-sized marie biscuits for kids", "8", 30, 35, "150 g", 40),
  p("p556", "Sunfeast Bounce Orange", "बाउंस ऑरेंज", "Sunfeast Bounce Orange Cream Biscuit — tangy orange cream sandwich", "8", 30, 35, "120 g", 40),
  p("p557", "Sunfeast Dark Fantasy Choco Meltz", "डार्क फैंटेसी मेल्ट्ज़", "Sunfeast Dark Fantasy Choco Meltz — gooey chocolate melt cookies", "8", 50, 55, "75 g", 35),
  p("p558", "Sunfeast Dark Fantasy Choco Creme", "डार्क फैंटेसी क्रीम", "Sunfeast Dark Fantasy Choco Creme — luxurious chocolate cream cookie", "8", 35, 40, "100 g", 40),
  p("p559", "Sunfeast Bourbon Chocolate", "सनफीस्ट बोरबॉन", "Sunfeast Bourbon Chocolate Cream Biscuit — classic choco cream sandwich", "8", 35, 40, "150 g", 40),
  p("p560", "Cremica Chocolate Cookies", "क्रेमिका चॉकलेट कुकीज़", "Cremica Premium Chocolate Cookies — rich chocolate chip indulgence", "8", 60, 70, "100 g", 30),
  p("p561", "Cremica Honey Cookies", "क्रेमिका हनी कुकीज़", "Cremica Honey Cookies — golden cookies sweetened with natural honey", "8", 55, 65, "100 g", 30),
  p("p562", "Karachi Bakery Fruit Biscuits", "कराची फ्रूट बिस्किट", "Karachi Bakery Fruit Biscuits — Hyderabad's iconic tutti-frutti biscuits", "8", 180, 220, "400 g", 25),
  p("p563", "Karachi Bakery Osmania Biscuits", "कराची ओस्मानिया", "Karachi Bakery Osmania Biscuits — Hyderabad's salty-sweet butter biscuit", "8", 165, 200, "400 g", 22),
  p("p564", "Karachi Bakery Cashew Almond", "कराची काजू बादाम", "Karachi Bakery Cashew Almond Biscuits — rich premium nutty cookies", "8", 220, 260, "400 g", 20),
  p("p565", "Modern White Bread 800g", "मॉडर्न ब्रेड", "Modern Milk Bread 800g — soft daily-fresh white sandwich bread", "8", 55, 60, "800 g", 40),
  p("p566", "Modern Brown Bread", "मॉडर्न ब्राउन ब्रेड", "Modern Brown Bread — wholesome wheat sandwich bread with bran", "8", 50, 55, "400 g", 35),
  p("p567", "Modern Multigrain Bread", "मॉडर्न मल्टीग्रेन", "Modern Multigrain Bread — fibre-rich seven-grain healthy sandwich bread", "8", 60, 65, "400 g", 30),
  p("p568", "Modern Sandwich Bread", "मॉडर्न सैंडविच ब्रेड", "Modern Sandwich Bread — extra-soft, perfect for sandwich making", "8", 45, 50, "400 g", 40),
  p("p569", "English Oven Croissant", "इंग्लिश ओवन क्रोसां", "English Oven Butter Croissant — flaky French-style buttery pastry", "8", 80, 90, "2 pcs", 25),
  p("p570", "Dominos Garlic Breadsticks", "डोमिनोज़ ब्रेडस्टिक्स", "Dominos Stuffed Garlic Bread Sticks — frozen ready-to-bake snack", "8", 99, 120, "150 g", 20),
  p("p571", "Anmol Rusk Elaichi", "अनमोल रस्क", "Anmol Premium Elaichi Rusk — crunchy cardamom flavoured tea rusk", "8", 65, 75, "300 g", 35),
  p("p572", "Brown Wheat Rusk", "ब्राउन रस्क", "Brown Wheat Rusk — healthy whole-wheat toast rusk for tea time", "8", 70, 80, "350 g", 30),
  p("p573", "Mio Amore Pineapple Cake Slice", "केक स्लाइस अनानास", "Mio Amore Pineapple Sponge Cake Slice — soft eggless cake, tiffin friendly", "8", 45, 50, "6 pcs", 30),
  p("p574", "Knorr Crispiness Pakoda Mix", "नोर पकोड़ा मिक्स", "Knorr Crispiness Pakoda Mix — instant batter mix for crispy onion pakoras", "8", 65, 75, "200 g", 25),
  p("p575", "Patanjali Marie Biscuit", "पतंजलि मारी", "Patanjali Marie Biscuit — light crisp tea biscuit, natural ingredients", "8", 25, 30, "200 g", 40),
  p("p576", "Patanjali Choco Biscuit", "पतंजलि चोको", "Patanjali Choco Cream Biscuit — chocolate cream sandwich, value pack", "8", 30, 35, "100 g", 40),
  p("p577", "Britannia Treat Pure Magic Hand Pies", "हैंड पाइज़", "Britannia Pure Magic Hand Pies — choco-filled flaky bite-size pastry", "8", 40, 45, "75 g", 35),
  p("p578", "Bakery Garlic Bread", "गार्लिक ब्रेड", "Bakery-Style Garlic Bread — savoury herb-buttered loaf, just warm and serve", "8", 90, 99, "200 g", 22),
  p("p579", "Sunfeast Marie Tea Biscuit", "सनफीस्ट मैरी टी", "Sunfeast Marie Tea Biscuit — light crisp tea biscuit family pack", "8", 35, 40, "250 g", 40),
];
