import type { Product } from "@/types";
import { p } from "./_helper";

/** Atta, Rice & Dal — 15 products. Loaded lazily by the catalogue hook. */
export const products: Product[] = [
  p("p31", "Aashirvaad Atta", "आशीर्वाद आटा", "Aashirvaad Shudh Chakki Atta — 100% whole wheat, stone-ground, soft rotis guaranteed", "10", 265, 310, "5 kg", 20),
  p("p32", "Aashirvaad Atta", "आशीर्वाद आटा", "Aashirvaad Shudh Chakki Atta — convenient 1 kg pack, stone-ground whole wheat", "10", 55, 62, "1 kg", 35),
  p("p33", "India Gate Basmati", "इंडिया गेट बासमती", "India Gate Super Basmati — extra-long aged grains, fluffy biryani and pulao", "10", 180, 210, "1 kg", 25),
  p("p34", "Dawat Rozana Basmati", "दावत रोज़ाना", "Dawat Rozana basmati rice — everyday long-grain rice for daily meals", "10", 85, 99, "1 kg", 30),
  p("p35", "Toor Dal (Arhar)", "तूर दाल", "Premium toor dal (arhar) — unpolished split pigeon peas, the heart of dal tadka", "10", 140, 160, "1 kg", 30),
  p("p36", "Moong Dal", "मूंग दाल", "Yellow moong dal (split) — light and easy to digest, perfect for khichdi and dal", "10", 120, 140, "1 kg", 28),
  p("p37", "Chana Dal", "चना दाल", "Chana dal (Bengal gram split) — protein-rich, ideal for dal, mithai, and snacks", "10", 95, 110, "1 kg", 25),
  p("p38", "Masoor Dal", "मसूर दाल", "Masoor dal (red lentils) — quick-cooking, mildly sweet, perfect for daily dal", "10", 90, 105, "1 kg", 22),
  p("p39", "Urad Dal", "उड़द दाल", "Whole urad dal (black gram) — base for dal makhani and idli-dosa batter", "10", 130, 150, "1 kg", 20),
  p("p40", "Rajma (Kidney Beans)", "राजमा", "Premium Chitra rajma (kidney beans) — soft texture, ideal for rajma chawal", "10", 120, 140, "500 g", 18),
  p("p41", "Chole (Chickpeas)", "छोले", "Kabuli chana (white chickpeas) — large grain, perfect for chole and chaat", "10", 75, 90, "500 g", 25),
  p("p42", "Poha (Flattened Rice)", "पोहा", "Thick variety poha (flattened rice) — quick breakfast staple, ready in minutes", "10", 35, 40, "500 g", 30),
  p("p43", "Suji (Semolina)", "सूजी", "Fine semolina (suji/rava) — ideal for upma, halwa, and idli batter", "10", 38, 42, "500 g", 28),
  p("p44", "Besan (Gram Flour)", "बेसन", "Pure gram flour (besan) — fine-milled, essential for pakoras, kadhi, and laddoos", "10", 48, 58, "500 g", 25),
  p("p45", "Maida", "मैदा", "Refined wheat flour (maida) — for cakes, puris, parathas, and bakery items", "10", 35, 40, "500 g", 30),
  p("p470", "Aashirvaad Multigrain Atta", "आशीर्वाद मल्टीग्रेन", "Aashirvaad Multigrain Atta — 6 grains blend, fibre-rich, soft rotis", "10", 360, 410, "5 kg", 18),
  p("p471", "Aashirvaad Whole Wheat Select", "आशीर्वाद सेलेक्ट", "Aashirvaad Whole Wheat Select Atta — premium MP wheat, superior taste", "10", 320, 365, "5 kg", 15),
  p("p472", "Aashirvaad Sugar Release Control Atta", "शुगर रिलीज़ कंट्रोल", "Aashirvaad Sugar Release Control Atta — diabetic-friendly multigrain blend", "10", 410, 460, "5 kg", 12),
  p("p473", "Patanjali Whole Wheat Atta", "पतंजलि आटा", "Patanjali Chakki Atta — stone-ground whole wheat, soft and nutritious rotis", "10", 250, 285, "5 kg", 25),
  p("p474", "Patanjali Atta 1kg", "पतंजलि आटा 1kg", "Patanjali Chakki Atta convenient 1 kg pack — daily whole wheat goodness", "10", 50, 58, "1 kg", 40),
  p("p475", "Annapurna Farm Fresh Atta", "अन्नपूर्णा आटा", "Annapurna Farm Fresh Atta — soft fluffy rotis with whole wheat goodness", "10", 270, 310, "5 kg", 22),
  p("p476", "Pillsbury Chakki Fresh Atta", "पिल्सबरी आटा", "Pillsbury Chakki Fresh Atta — soft rotis that stay soft for hours", "10", 280, 325, "5 kg", 18),
  p("p477", "Aashirvaad Atta with Multigrains 1kg", "मल्टीग्रेन 1kg", "Aashirvaad Multigrain Atta — small pack with 6 grain mix, nutrient-rich", "10", 75, 85, "1 kg", 30),
  p("p478", "India Gate Tibar Basmati Rice", "इंडिया गेट तिबार", "India Gate Tibar Basmati — premium long-grain everyday basmati, aromatic", "10", 130, 150, "1 kg", 28),
  p("p479", "India Gate Mini Mogra Basmati", "इंडिया गेट मिनी मोगरा", "India Gate Mini Mogra Basmati — broken basmati, perfect for daily meals", "10", 95, 110, "1 kg", 30),
  p("p480", "Daawat Pulav Basmati Rice", "दावत पुलाव", "Daawat Pulav Basmati — premium long-grain for fragrant pulao and biryani", "10", 165, 195, "1 kg", 22),
  p("p481", "Lal Qilla Basmati Rice", "लाल किला बासमती", "Lal Qilla Classic Basmati Rice — aged extra-long basmati, fluffy texture", "10", 175, 210, "1 kg", 20),
  p("p482", "Kohinoor Authentic Basmati", "कोहिनूर बासमती", "Kohinoor Authentic Basmati Rice — premium long-grain aged rice", "10", 195, 225, "1 kg", 18),
  p("p483", "Sona Masuri Rice", "सोना मसूरी", "Sona Masuri Raw Rice — medium-grain South Indian rice, daily staple", "10", 85, 99, "1 kg", 30),
  p("p484", "Sona Masoori Steam Rice", "सोना मसूरी स्टीम", "Sona Masoori Steam Rice — parboiled medium grain, healthier choice", "10", 92, 105, "1 kg", 25),
  p("p485", "Kolam Rice", "कोलम चावल", "Kolam Rice — short-grain Maharashtra favourite, ideal for daily meals", "10", 80, 92, "1 kg", 28),
  p("p486", "Idli Rice", "इडली चावल", "Idli Rice — short-grain parboiled rice, perfect for idli and dosa batter", "10", 75, 88, "1 kg", 25),
  p("p487", "Patanjali Brown Rice", "पतंजलि ब्राउन राइस", "Patanjali Brown Rice — fibre-rich unpolished healthy whole grain rice", "10", 110, 125, "1 kg", 20),
  p("p488", "Quinoa Whole Grain", "क्विनोआ", "Premium White Quinoa — gluten-free superfood, high-protein whole grain", "10", 280, 325, "500 g", 18),
  p("p489", "Daliya / Broken Wheat", "दलिया", "Daliya (Broken Wheat) — wholesome fibre-rich, ideal for porridge and khichdi", "10", 45, 55, "500 g", 25),
  p("p490", "Foxnuts / Makhana Raw", "मखाना", "Premium Raw Makhana (Foxnuts) — light, low-calorie healthy snack base", "10", 175, 210, "200 g", 22),
  p("p491", "Toor Dal 500g", "तूर दाल 500g", "Premium Toor Dal (Arhar) — split pigeon peas, small 500g pack for trial", "10", 75, 85, "500 g", 35),
  p("p492", "Moong Whole (Green)", "मूंग साबुत", "Whole green moong — protein-rich, ideal for sprouts and dal", "10", 130, 150, "1 kg", 22),
  p("p493", "Urad Sabut (Whole Black)", "उड़द साबुत", "Whole Black Urad — base for dal makhani, rich earthy flavour", "10", 140, 165, "1 kg", 20),
  p("p494", "Sabut Chana Kala", "साबुत चना काला", "Whole Kala Chana (Brown Chickpeas) — high-fibre, protein-rich legume", "10", 85, 99, "1 kg", 28),
  p("p495", "Sabut Masoor (Whole Red)", "साबुत मसूर", "Whole Masoor Dal — brown lentils with skin, hearty and nutritious", "10", 95, 110, "1 kg", 22),
  p("p496", "Lobia / Black Eye Peas", "लोबिया", "Lobia (Black Eye Peas) — protein-rich, ideal for curry and salads", "10", 90, 105, "500 g", 20),
  p("p497", "Moth Beans (Matki)", "मटकी / मोठ", "Whole Moth Beans (Matki) — Maharashtra favourite for usal and sprouts", "10", 95, 110, "500 g", 20),
  p("p498", "Sabudana (Sago)", "साबूदाना", "Premium Nylon Sabudana (Sago) — perfect for khichdi, kheer, and vrat", "10", 60, 70, "500 g", 30),
  p("p499", "MTR Rava (Sooji 1kg)", "MTR रवा", "MTR Bombay Rava (Sooji/Semolina) — ideal for upma, halwa, idli batter", "10", 60, 70, "1 kg", 25),
  p("p500", "Patanjali Besan", "पतंजलि बेसन", "Patanjali Pure Besan — fine-milled gram flour, perfect for pakora and kadhi", "10", 85, 99, "1 kg", 22),
  p("p501", "Aashirvaad Sugar Release Control 5kg", "शुगर कंट्रोल 5kg", "Aashirvaad Sugar Release Control Atta — diabetes-friendly bulk 5 kg pack", "10", 410, 460, "5 kg", 10),
  p("p502", "Brown Rice 1kg India Gate", "इंडिया गेट ब्राउन राइस", "India Gate Brown Basmati Rice — fibre-rich healthy whole-grain rice", "10", 165, 195, "1 kg", 18),
  p("p503", "Idli/Dosa Rava", "इडली रवा", "Idli/Dosa Rava — coarse rice rava for soft idlis and crispy dosas", "10", 55, 65, "500 g", 22),
  p("p504", "MTR Khichdi Mix", "MTR खिचड़ी मिक्स", "MTR Ready-to-Cook Khichdi Mix — wholesome instant meal, just add water", "10", 60, 70, "200 g", 28),
];
