import type { Product } from "@/types";
import { p } from "./_helper";

/** Sauces & Spreads — 14 products. Loaded lazily by the catalogue hook. */
export const products: Product[] = [
  p("p171", "Kissan Mixed Fruit Jam", "किसान मिक्स्ड फ्रूट जैम", "India's favourite fruit jam with 8 real fruits — mango, apple, pineapple and more", "12", 181, 195, "490 g", 40),
  p("p172", "Maggi Hot & Sweet Tomato Chilli Sauce", "मैगी हॉट एंड स्वीट सॉस", "Iconic tangy-sweet tomato chilli sauce — pairs perfectly with snacks and pakoras", "12", 150, 165, "1 kg", 35),
  p("p173", "Kissan Fresh Tomato Ketchup", "किसान टमेटो केचअप", "Made from real tomatoes, no artificial colours — family-size squeezy bottle", "12", 106, 120, "950 g", 40),
  p("p174", "Heinz Tomato Ketchup", "हाइंज टमेटो केचअप", "World-famous Heinz ketchup — thick rich tomato taste, premium import", "12", 227, 245, "900 g", 25),
  p("p175", "Veeba Veg Eggless Mayonnaise", "वीबा वेज मेयोनेज़", "100% eggless creamy mayonnaise — perfect for sandwiches, wraps and burgers", "12", 74, 85, "250 g", 45),
  p("p176", "Dabur Honey 100% Pure", "डाबर शहद", "World's No.1 honey brand — NMR tested for purity, no sugar adulteration", "12", 221, 245, "500 g", 50),
  p("p177", "Saffola Peanut Butter Jaggery", "साफोला पीनट बटर", "High-protein peanut butter sweetened with jaggery — no refined sugar, 31% protein", "12", 245, 280, "850 g", 30),
  p("p178", "Ching's Schezwan Chutney", "चिंग्स शेज़वान चटनी", "Spicy Indo-Chinese schezwan chutney — perfect for noodles, fried rice and momos", "12", 110, 125, "250 g", 40),
  p("p179", "Nutella Hazelnut Cocoa Spread", "नटेला चॉकलेट स्प्रेड", "Italian hazelnut cocoa spread — kids' favourite breakfast spread on bread", "12", 425, 460, "350 g", 30),
  p("p180", "Funfoods Garlic Mayonnaise", "फनफूड्स गार्लिक मेयो", "Dr. Oetker FunFoods creamy garlic mayonnaise — perfect dip for fries and wraps", "12", 105, 120, "245 g", 35),
  p("p181", "Mother's Recipe Mango Pickle", "मदर्स रेसिपी आम का अचार", "Classic Punjabi mango achaar — hand-cut raw mango pieces in mustard oil and spices", "12", 99, 115, "400 g", 50),
  p("p182", "Tops Mixed Vegetable Pickle", "टॉप्स मिक्स अचार", "Traditional north Indian mixed veg pickle — perfect with paratha and dal-chawal", "12", 95, 110, "400 g", 45),
  p("p183", "Amul Lite Bread Spread", "अमूल लाइट ब्रेड स्प्रेड", "Low-fat butter alternative spread — easy to spread on bread, with vitamin A & E", "12", 50, 55, "100 g", 50),
  p("p184", "Kissan Pineapple Jam", "किसान पाइनएप्पल जैम", "Real pineapple chunks jam — fruity tropical taste, kid-friendly breakfast spread", "12", 95, 105, "200 g", 40),
  p("p1205", "Wingreens Farms Tomato Ketchup", "विंग्रीन्स केचअप", "Wingreens premium tomato ketchup — no synthetic colours, no preservatives", "12", 115, 130, "950 g", 35),
  p("p1206", "Mother's Recipe Schezwan Ketchup", "मदर्स रेसिपी शेज़वान", "Schezwan tomato chilli ketchup — Indo-Chinese spicy twist for snacks", "12", 95, 110, "200 g", 40),
  p("p1207", "Bertolli Olive Oil Pasta Sauce", "बेर्टोली पास्ता सॉस", "Italian pasta sauce with extra-virgin olive oil — restaurant-style", "12", 285, 320, "350 g", 25),
  p("p1208", "Veeba Marinara Pasta Sauce", "वीबा मैरिनारा सॉस", "Classic Italian marinara — slow-cooked tomato pasta sauce, no preservatives", "12", 165, 185, "350 g", 35),
  p("p1209", "Veeba Tomato Basil Sauce", "वीबा टमेटो बेसिल", "Tomato basil pasta sauce — fresh herb aroma, ready to heat and serve", "12", 165, 185, "350 g", 30),
  p("p1210", "Veeba Burger Mayo 300g", "वीबा बर्गर मेयो", "Creamy burger spread mayo — sweet-tangy taste, restaurant burger style", "12", 95, 110, "300 g", 40),
  p("p1211", "Veeba Tandoori Mayo 300g", "वीबा तंदूरी मेयो", "Smoky tandoori mayonnaise — perfect dip for fries, kebab and wraps", "12", 95, 110, "300 g", 40),
  p("p1212", "Wingreens Eggless Mayo 250g", "विंग्रीन्स एगलेस मेयो", "Wingreens 100% eggless mayonnaise — vegetarian-friendly creamy spread", "12", 85, 95, "250 g", 40),
  p("p1213", "Cremica Garlic Mayo 275g", "क्रेमिका गार्लिक मेयो", "Cremica creamy garlic mayonnaise — perfect for sandwiches and fries", "12", 105, 120, "275 g", 35),
  p("p1214", "Cremica Peri Peri Mayo", "क्रेमिका पेरी पेरी", "Spicy Peri Peri mayonnaise — Spanish-style fiery dip and spread", "12", 105, 120, "275 g", 35),
  p("p1215", "Knorr Soy Sauce 200ml", "नॉर सोया सॉस", "Knorr light soy sauce — for Indo-Chinese noodles, rice and stir fry", "12", 75, 85, "200 ml", 40),
  p("p1216", "Knorr Chilli Garlic Sauce", "नॉर चिली गार्लिक", "Spicy chilli garlic sauce — perfect for momos, noodles and snacks", "12", 85, 95, "200 g", 40),
  p("p1217", "Ching's Soy Sauce 210g", "चिंग्स सोया सॉस", "Ching's Secret dark soy sauce — Indo-Chinese essential, rich umami", "12", 85, 95, "210 g", 40),
  p("p1218", "Ching's Vinegar 170g", "चिंग्स विनेगर", "Ching's synthetic white vinegar — for Indo-Chinese dishes and pickles", "12", 45, 55, "170 g", 45),
  p("p1219", "Ching's Schezwan Sauce 1kg", "चिंग्स शेज़वान 1 kg", "Ching's bulk schezwan chutney — fiery Indo-Chinese essential", "12", 385, 425, "1 kg", 25),
  p("p1220", "Sriracha Hot Sauce 200ml", "श्रीराचा सॉस", "Authentic Thai-style sriracha hot chilli sauce — spicy tangy versatile dip", "12", 165, 185, "200 ml", 30),
  p("p1221", "Tabasco Original Pepper Sauce", "टबास्को सॉस", "McIlhenny Tabasco original pepper sauce — fiery aged Louisiana classic", "12", 425, 475, "60 ml", 20),
  p("p1222", "Mama Earth Crunchy Peanut Butter", "मामा अर्थ पीनट बटर", "Mama Earth crunchy peanut butter — no added sugar, real roasted peanuts", "12", 215, 245, "500 g", 30),
  p("p1223", "Pintola All-Natural Peanut Butter", "पिंटोला पीनट बटर", "Pintola all-natural creamy peanut butter — 100% peanuts, no additives", "12", 245, 280, "1 kg", 30),
  p("p1224", "MyFitness Crunchy Peanut Butter", "मायफिटनेस पीनट बटर", "MyFitness crunchy peanut butter — 30g protein per serve, by Beast Life", "12", 345, 395, "1 kg", 30),
  p("p1225", "Hershey's Chocolate Syrup 623g", "हर्षीज़ चॉकलेट सिरप", "Hershey's classic chocolate syrup — for milkshakes, sundaes and pancakes", "12", 265, 295, "623 g", 30),
  p("p1226", "Hershey's Strawberry Syrup", "हर्षीज़ स्ट्राबेरी सिरप", "Hershey's strawberry syrup — for shakes, ice cream and desserts", "12", 245, 275, "623 g", 25),
  p("p1227", "Kissan Strawberry Jam 200g", "किसान स्ट्राबेरी जैम", "Kissan real strawberry jam — fruity sweet breakfast spread for bread", "12", 95, 105, "200 g", 40),
  p("p1228", "Lotus Biscoff Spread Smooth", "लोटस बिस्कॉफ स्प्रेड", "Lotus Biscoff caramelised biscuit spread — sweet cinnamon indulgence", "12", 425, 475, "400 g", 25),
  p("p1229", "Figaro Olives Stuffed 200g", "फिगारो ऑलिव्स", "Figaro green olives stuffed with pimiento — Spanish gourmet snack", "12", 245, 275, "200 g", 25),
];
