import type { Product } from "@/types";
import { p } from "./_helper";

/** Tea, Coffee & Health Drink — 21 products. Loaded lazily by the catalogue hook. */
export const products: Product[] = [
  p("p88", "Tata Tea Gold", "टाटा टी गोल्ड", "Tata Tea Gold — premium long-leaf tea with assam blend, full-bodied chai", "9", 165, 180, "250 g", 20),
  p("p89", "Red Label Tea", "रेड लेबल चाय", "Brooke Bond Red Label — strong, fragrant Indian tea, the family favourite", "9", 140, 155, "250 g", 22),
  p("p90", "Nescafe Classic Coffee", "नेस्कैफे क्लासिक", "Nescafé Classic — 100% pure instant coffee, rich aroma in every cup", "9", 195, 220, "100 g", 18),
  p("p91", "Bru Instant Coffee", "ब्रू कॉफ़ी", "Bru Instant Coffee — smooth coffee-chicory blend, energising taste", "9", 165, 185, "100 g", 15),
  p("p92", "Bournvita", "बोर्नविटा", "Cadbury Bournvita — chocolate health drink with vitamins and minerals", "9", 210, 240, "500 g", 20),
  p("p93", "Horlicks Classic Malt", "हॉर्लिक्स", "Horlicks Classic Malt — nutritious malt drink with 24 vital nutrients", "9", 225, 255, "500 g", 18),
  p("p253", "Tetley Classic Green Tea", "टेटली ग्रीन टी", "Pure refreshing green tea bags with antioxidants — premium daily detox", "9", 162, 190, "25 bags", 40),
  p("p254", "Lipton Honey Lemon Green Tea", "लिप्टन हनी लेमन", "Zesty honey and lemon green tea bags — refreshing weight-wellness blend", "9", 180, 200, "25 bags", 40),
  p("p255", "Wagh Bakri Premium Tea", "वाघ बकरी चाय", "Strong full-bodied Assam blend leaf tea — Gujarat's #1 chai brand", "9", 290, 320, "500 g", 45),
  p("p256", "Tata Tea Premium", "टाटा टी प्रीमियम", "Bold-flavour Assam dust tea for kadak doodh-wali chai — family pack", "9", 280, 305, "500 g", 50),
  p("p257", "Society Masala Tea", "सोसाइटी मसाला चाय", "Aromatic CTC tea with natural masala blend — Maharashtra household favourite", "9", 270, 295, "500 g", 35),
  p("p258", "Taj Mahal Tea Bags", "ताज महल टी बैग", "Premium Assam tea bags with strong taste — Brooke Bond's signature brand", "9", 199, 220, "100 bags", 40),
  p("p259", "Continental Speciale Coffee", "कॉन्टिनेंटल कॉफी", "Premium freeze-dried instant coffee with rich aroma — smooth daily cuppa", "9", 235, 260, "100 g", 30),
  p("p260", "Nescafe Sunrise Instant", "नेस्कैफे सनराइज", "Coffee-chicory blend for strong filter-style taste — India's morning favourite", "9", 215, 240, "100 g", 40),
  p("p261", "Boost Chocolate", "बूस्ट चॉकलेट", "Malt-cocoa energy drink mix endorsed by cricketers — refill pack", "9", 295, 325, "500 g", 35),
  p("p262", "Complan Royale Chocolate", "कॉम्प्लान रॉयल", "Complete planned food with 33 vital nutrients — growth drink for kids", "9", 410, 445, "500 g", 30),
  p("p263", "Horlicks Women's Plus", "हॉर्लिक्स वुमन्स प्लस", "Caramel-flavour nutrition drink for women — supports bone and iron health", "9", 405, 435, "400 g", 30),
  p("p264", "Pediasure Vanilla Delight", "पीडियाश्योर वनिला", "Scientifically designed nutrition drink for kids 2-10 yrs — refill pack", "9", 648, 685, "375 g", 25),
  p("p265", "Protinex Original", "प्रोटीनेक्स ओरिजिनल", "High-protein nutritional drink for adults with vital nutrients — jar", "9", 601, 665, "400 g", 25),
  p("p266", "Tang Orange Drink Mix", "टैंग ऑरेंज", "Vitamin C-rich instant orange drink mix — refreshing summer cooler", "9", 165, 180, "500 g", 35),
  p("p267", "Nestle Milkmaid", "नेस्ले मिल्कमेड", "Sweetened condensed milk — classic mithai-base for kheer and barfi", "9", 175, 195, "400 g", 40),
  p("p615", "Tata Tea Agni", "टाटा टी अग्नि", "Strong CTC dust tea for kadak masala chai — value-pack family choice", "9", 225, 250, "500 g", 45),
  p("p616", "Tata Tea Chakra Gold", "टाटा टी चक्रा गोल्ड", "South Indian style strong leaf tea with malty taste — premium blend", "9", 285, 315, "500 g", 35),
  p("p617", "Lipton Yellow Label Tea", "लिप्टन येलो लेबल", "Bright refreshing global tea blend — Lipton's signature daily brew", "9", 155, 175, "250 g", 30),
  p("p618", "Lipton Strong Black Tea", "लिप्टन स्ट्रॉन्ग", "Extra-strong Assam blend tea for full-bodied chai — bold morning kick", "9", 165, 185, "250 g", 30),
  p("p619", "3 Roses Natural Care Tea", "3 रोज़ेज़ चाय", "South India's iconic strong dust tea blend — perfect milk chai", "9", 275, 300, "500 g", 35),
  p("p620", "Brooke Bond Taaza Leaf Tea", "ब्रूक बॉन्ड ताज़ा", "Fresh-tasting everyday tea at value price — wide-spread household brand", "9", 230, 255, "500 g", 40),
  p("p621", "TGL Co Earl Grey Tea Bags", "TGL अर्ल ग्रे टी बैग", "Premium Ceylon black tea infused with bergamot oil — gourmet pyramid bags", "9", 425, 475, "25 bags", 20),
  p("p622", "Twinings Pure Green Tea", "ट्विनिंग्स ग्रीन टी", "Classic English-style pure green tea bags — light, refreshing antioxidant cup", "9", 295, 325, "25 bags", 25),
  p("p623", "Tata Tetley Long Leaf Green Tea", "टेटली लॉन्ग लीफ ग्रीन", "Whole-leaf green tea with smooth, mellow taste — premium daily detox", "9", 245, 275, "100 g", 30),
  p("p624", "Organic India Tulsi Original", "ऑर्गेनिक इंडिया तुलसी", "Caffeine-free herbal infusion with five tulsi varieties — stress-relief tea", "9", 215, 240, "25 bags", 25),
  p("p625", "Organic India Tulsi Ginger", "तुलसी जिंजर", "Soothing tulsi blend with warm ginger — immunity-boosting herbal tea", "9", 215, 240, "25 bags", 25),
  p("p626", "Vahdam Himalayan Green Tea", "वहडम हिमालयन ग्रीन", "High-altitude Himalayan green tea — antioxidant-rich premium loose leaf", "9", 395, 450, "100 g", 20),
  p("p627", "Nescafe Gold Blend", "नेस्कैफे गोल्ड", "Premium freeze-dried instant coffee with smooth aromatic taste — gold jar", "9", 565, 625, "100 g", 25),
  p("p628", "Davidoff Fine Aroma Coffee", "डेविडॉफ कॉफी", "Premium German freeze-dried instant coffee — refined aromatic blend", "9", 645, 715, "100 g", 18),
  p("p629", "Continental Black Coffee", "कॉन्टिनेंटल ब्लैक कॉफी", "100% pure coffee for black cuppa or espresso-style brew — refill pouch", "9", 195, 220, "100 g", 30),
  p("p630", "Coffee Day Filter Coffee Powder", "कॉफी डे फिल्टर", "Authentic South Indian filter coffee powder — 80:20 coffee-chicory blend", "9", 245, 275, "500 g", 25),
  p("p631", "Bru Gold Instant Coffee", "ब्रू गोल्ड", "Premium 100% pure freeze-dried Arabica coffee — smooth rich taste", "9", 455, 510, "100 g", 25),
  p("p632", "Tata Coffee Grand", "टाटा कॉफी ग्रैंड", "Aromatic instant coffee with flavour-locked granules — premium taste", "9", 215, 240, "100 g", 30),
  p("p633", "Nescafe Sunrise 200g", "नेस्कैफे सनराइज 200g", "Coffee-chicory blend for South Indian filter taste — value family pack", "9", 395, 435, "200 g", 30),
  p("p634", "Wagh Bakri Instant Masala Tea", "वाघ बकरी मसाला चाय", "Ready-to-make masala chai with milk and sugar — sachet pack", "9", 165, 185, "140 g", 35),
  p("p635", "MTR Instant Filter Coffee", "MTR फिल्टर कॉफी", "Authentic 3-in-1 South Indian filter coffee sachets — restaurant taste", "9", 165, 185, "10 sachets", 30),
  p("p636", "Horlicks Lite", "हॉर्लिक्स लाइट", "Low-sugar nutrition drink for weight watchers — vanilla flavour", "9", 410, 445, "450 g", 25),
  p("p637", "Horlicks Classic Plain", "हॉर्लिक्स क्लासिक", "Original plain malt drink with 24 vital nutrients — refill pack", "9", 230, 255, "500 g", 25),
  p("p638", "Horlicks Protein Plus", "हॉर्लिक्स प्रोटीन प्लस", "Triple-protein blend (whey, soy, casein) for adult muscle health", "9", 645, 715, "400 g", 20),
  p("p639", "Boost 2x Power", "बूस्ट 2X पावर", "Energy drink with chocolate flavour and 2x power for active days", "9", 305, 340, "500 g", 30),
  p("p640", "Complan Pista Badam", "कॉम्प्लान पिस्ता बादाम", "Nutrition drink with pistachio and almond — kids growth formula", "9", 415, 450, "500 g", 25),
  p("p641", "Cadbury Bournvita Lil Champs Strawberry", "बोर्नविटा लिल चैम्प्स", "Nutrition drink for 2-5 year toddlers — strawberry flavour", "9", 235, 265, "200 g", 30),
  p("p642", "Pediasure Chocolate", "पीडियाश्योर चॉकलेट", "Scientifically designed nutrition for kids 2-10 yrs — chocolate flavour", "9", 685, 745, "400 g", 20),
  p("p643", "Tang Mango Drink Mix", "टैंग मैंगो", "Instant mango drink mix with vitamin C — refreshing summer cooler", "9", 175, 195, "500 g", 30),
  p("p644", "Tang Lime Drink Mix", "टैंग लाइम", "Tangy lime instant drink mix with vitamin C — chilled glass refresher", "9", 175, 195, "500 g", 30),
];
