import type { Product } from "@/types";
import { p } from "./_helper";

/** Snacks & Munchies — 8 products. Loaded lazily by the catalogue hook. */
export const products: Product[] = [
  p("p67", "Lays Classic Salted", "लेज़ क्लासिक", "Lay's Classic Salted — crispy thinly-sliced potato chips, irresistible taste", "5", 20, 25, "52 g", 60),
  p("p68", "Lays Magic Masala", "लेज़ मैजिक मसाला", "Lay's India's Magic Masala — bold spicy flavour, India's most loved chip", "5", 20, 25, "52 g", 55),
  p("p69", "Kurkure Masala Munch", "कुरकुरे", "Kurkure Masala Munch — crunchy corn puffs with tangy masala, iconic snack", "5", 20, 25, "75 g", 50),
  p("p70", "Haldiram Aloo Bhujia", "हल्दीराम आलू भुजिया", "Haldiram's Aloo Bhujia — crispy spiced potato sticks, perfect chai-time namkeen", "5", 50, 55, "200 g", 30),
  p("p71", "Haldiram Moong Dal", "हल्दीराम मूंग दाल", "Haldiram's Moong Dal — crunchy roasted dal, lightly salted, healthy bites", "5", 45, 50, "200 g", 28),
  p("p77", "Bingo Mad Angles", "बिंगो मैड एंगल्स", "Bingo Mad Angles Achari Masti — triangle chips, achaari Indian flavour", "5", 20, 25, "66 g", 40),
  p("p78", "Uncle Chipps", "अंकल चिप्स", "Uncle Chipps Spicy Treat — bold masala potato chips, full of crunch", "5", 20, 25, "55 g", 35),
  p("p79", "Haldiram Namkeen Mixture", "हल्दीराम नमकीन मिक्स", "Haldiram's Classic Namkeen Mixture — assorted crispy mix, perfect with chai", "5", 55, 60, "200 g", 25),
  p("p400", "Lays Cream & Onion", "लेज़ क्रीम एंड अनियन", "Lay's American Style Cream & Onion — creamy onion flavour with classic crunch", "5", 20, 25, "52 g", 55),
  p("p401", "Lays Tomato Tango", "लेज़ टोमैटो टैंगो", "Lay's Tomato Tango — tangy tomato chips with a zesty kick", "5", 20, 25, "52 g", 50),
  p("p402", "Lays Spanish Tomato Tango", "लेज़ स्पैनिश टोमैटो", "Lay's Spanish Tomato Tango — bold Spanish tomato flavour, party favourite", "5", 20, 25, "52 g", 45),
  p("p403", "Lays Wafer Style Hot & Sweet Chilli", "लेज़ वेफर स्टाइल", "Lay's Wafer Style Hot & Sweet Chilli — thick-cut chips with bold flavour", "5", 50, 55, "52 g", 35),
  p("p404", "Lays Sizzling Hot", "लेज़ सिज़लिंग हॉट", "Lay's Sizzling Hot — fiery red chilli chips for spice lovers", "5", 20, 25, "52 g", 40),
  p("p405", "Lays Chile Limon", "लेज़ चिली लेमन", "Lay's Chile Limon — tangy lemon and spicy chilli combination", "5", 20, 25, "52 g", 35),
  p("p406", "Kurkure Green Chutney Rajasthani Style", "कुरकुरे ग्रीन चटनी", "Kurkure Green Chutney Style — minty Rajasthani chutney flavour, crunchy puffs", "5", 20, 25, "75 g", 45),
  p("p407", "Kurkure Naughty Tomato", "कुरकुरे नॉटी टोमैटो", "Kurkure Naughty Tomato — playful tomato tang, kids' favourite", "5", 20, 25, "75 g", 45),
  p("p408", "Kurkure Twisteez", "कुरकुरे ट्विस्टीज़", "Kurkure Twisteez Saucy Tomato — twisted crunchy snack, full of flavour", "5", 20, 25, "55 g", 40),
  p("p409", "Kurkure Solid Masti Tomato", "कुरकुरे सॉलिड मस्ती", "Kurkure Solid Masti Yummy Tomato — bigger crunch, longer fun", "5", 30, 35, "85 g", 35),
  p("p410", "Kurkure Puffcorn Yummy Cheese", "कुरकुरे पफकॉर्न चीज़", "Kurkure Puffcorn Yummy Cheese — light fluffy cheesy puffs, melt-in-mouth", "5", 20, 25, "55 g", 50),
  p("p411", "Kurkure Puffcorn Butter Delight", "पफकॉर्न बटर", "Kurkure Puffcorn Butter Delight — buttery puff corn, addictive bite", "5", 20, 25, "55 g", 48),
  p("p412", "Cheetos Crunchy Masala Balls", "चीटोस मसाला बॉल्स", "Cheetos Crunchy Masala Balls — bold masala flavour, signature crunch", "5", 20, 25, "55 g", 45),
  p("p413", "Cheetos Cheese Puffs", "चीटोस चीज़ पफ्स", "Cheetos Cheese Puffs — airy cheesy puffs, kids' all-time favourite", "5", 20, 25, "32 g", 50),
  p("p414", "Pringles Original", "प्रिंगल्स ओरिजिनल", "Pringles Original — uniformly stacked salted chips in iconic can", "5", 110, 125, "107 g", 30),
  p("p415", "Pringles Sour Cream & Onion", "प्रिंगल्स साउर क्रीम", "Pringles Sour Cream & Onion — creamy tangy onion chips, premium snack", "5", 110, 125, "107 g", 25),
  p("p416", "Pringles Hot & Spicy", "प्रिंगल्स हॉट एंड स्पाइसी", "Pringles Hot & Spicy — fiery hot stacked potato chips", "5", 110, 125, "107 g", 25),
  p("p417", "Pringles Cheesy Cheese", "प्रिंगल्स चीज़", "Pringles Cheesy Cheese — rich cheddar flavoured crisps", "5", 110, 125, "107 g", 20),
  p("p418", "Doritos Nacho Cheese", "डोरिटोस नाचो चीज़", "Doritos Nacho Cheese flavoured triangular tortilla chips — bold crunch", "5", 50, 55, "70 g", 35),
  p("p419", "Doritos Cheesy Tomato", "डोरिटोस टोमैटो", "Doritos Cheesy Tomato — cheesy tomato tortilla chips, party-style", "5", 50, 55, "70 g", 30),
  p("p420", "Doritos Sweet Chilli", "डोरिटोस स्वीट चिली", "Doritos Sweet Chilli — sweet and spicy tortilla chips, bold flavour", "5", 50, 55, "70 g", 28),
  p("p421", "Bingo Tedhe Medhe Masala Tadka", "बिंगो टेढ़े मेढ़े", "Bingo Tedhe Medhe Masala Tadka — wavy crunchy snack with tangy masala", "5", 20, 25, "70 g", 50),
  p("p422", "Bingo Mad Angles Tomato Madness", "बिंगो टोमैटो", "Bingo Mad Angles Tomato Madness — triangular chips with juicy tomato flavour", "5", 20, 25, "66 g", 45),
  p("p423", "Bingo Mad Angles Cheese Nachos", "बिंगो चीज़ नाचो", "Bingo Mad Angles Cheese Nachos — crispy triangles with cheesy goodness", "5", 20, 25, "66 g", 40),
  p("p424", "Bingo Original Yumitos Pudina Twist", "यूमिटोज़ पुदीना", "Bingo Yumitos Original Style Pudina Twist — refreshing mint potato chips", "5", 20, 25, "52 g", 40),
  p("p425", "Bingo Yumitos Tomato Mischief", "यूमिटोज़ टोमैटो", "Bingo Yumitos Tomato Mischief — tangy tomato thin potato chips", "5", 20, 25, "52 g", 38),
  p("p426", "Bingo Starters Masala Chips", "बिंगो स्टार्टर्स", "Bingo Starters Masala — restaurant-style starter chips with bold masala", "5", 20, 25, "55 g", 35),
  p("p427", "Haldiram Bhel Puri", "हल्दीराम भेल पुरी", "Haldiram's Bhel Puri — Mumbai-style ready-to-eat bhel with chutneys", "5", 50, 55, "200 g", 25),
  p("p428", "Haldiram Khatta Meetha", "हल्दीराम खट्टा मीठा", "Haldiram's Khatta Meetha — sweet and tangy mix with sev, raisins, peanuts", "5", 55, 60, "200 g", 25),
  p("p429", "Haldiram Chana Jor Garam", "हल्दीराम चना जोर", "Haldiram's Chana Jor Garam — flattened spicy chana, classic Indian snack", "5", 45, 50, "200 g", 20),
  p("p430", "Haldiram Murukku", "हल्दीराम मुरुक्कू", "Haldiram's Murukku — crispy South Indian rice flour spirals, classic taste", "5", 50, 55, "200 g", 22),
  p("p431", "Haldiram Boondi Plain Salted", "हल्दीराम बूंदी", "Haldiram's Plain Salted Boondi — crunchy gram flour pearls, snacking classic", "5", 45, 50, "200 g", 28),
  p("p432", "Haldiram Boondi Masala", "हल्दीराम मसाला बूंदी", "Haldiram's Masala Boondi — spicy crunchy boondi with chatpata masala", "5", 50, 55, "200 g", 28),
  p("p433", "Haldiram Aloo Tikki Namkeen", "हल्दीराम आलू टिक्की", "Haldiram's Aloo Tikki Namkeen — crispy aloo flavoured tikki bites", "5", 55, 60, "200 g", 22),
  p("p434", "Haldiram Navratan Mixture", "हल्दीराम नवरतन", "Haldiram's Navratan Mixture — premium nine-ingredient namkeen mix", "5", 60, 70, "200 g", 25),
  p("p435", "Bikaji Bhujia", "बीकाजी भुजिया", "Bikaji Bikaneri Bhujia — original Bikaner-style spicy gram flour sticks", "5", 50, 55, "200 g", 30),
  p("p436", "Bikaji Sev Special", "बीकाजी सेव", "Bikaji Sev Special — thin crispy gram flour sev, perfect topping or snack", "5", 48, 55, "200 g", 28),
  p("p437", "Bikaji Soya Sticks", "बीकाजी सोया स्टिक्स", "Bikaji Soya Sticks — crunchy protein-rich soya sticks, healthier snacking", "5", 45, 50, "180 g", 25),
  p("p438", "Bikaji Aloo Bhujia", "बीकाजी आलू भुजिया", "Bikaji Aloo Bhujia — spicy potato and gram flour sticks, Bikaner classic", "5", 50, 55, "200 g", 28),
  p("p439", "Yellow Diamond Chips Salted", "येलो डायमंड चिप्स", "Yellow Diamond Classic Salted Potato Chips — value pack family snack", "5", 20, 25, "55 g", 40),
  p("p440", "Balaji Wafers Masala Magic", "बालाजी मसाला", "Balaji Wafers Masala Magic — bold Indian masala potato wafers", "5", 10, 10, "30 g", 50),
  p("p441", "Balaji Wafers Simply Salted", "बालाजी सिंपली सॉल्टेड", "Balaji Wafers Simply Salted — classic salted potato wafers, value pack", "5", 10, 10, "30 g", 50),
  p("p442", "Cornitos Nachos Cheese & Herbs", "कॉर्निटोस चीज़", "Cornitos Cheese & Herbs Nacho Crisps — restaurant-style nachos", "5", 80, 99, "60 g", 30),
  p("p443", "Cornitos Nachos Tomato Mexicana", "कॉर्निटोस टोमैटो", "Cornitos Tomato Mexicana Nacho Crisps — tangy Mexican-style nachos", "5", 80, 99, "60 g", 28),
  p("p444", "Cornitos Nachos Sea Salt", "कॉर्निटोस सी सॉल्ट", "Cornitos Sea Salt Nacho Crisps — lightly salted corn nachos", "5", 80, 99, "60 g", 25),
  p("p445", "Act II Microwave Popcorn Butter", "एक्ट II पॉपकॉर्न", "Act II Microwave Popcorn Golden Sizzle Butter — ready in 3 minutes", "5", 70, 80, "99 g", 30),
  p("p446", "Act II Instant Popcorn Tomato Chilli", "एक्ट II टोमैटो चिली", "Act II Instant Popcorn Tomato Chilli — tangy spicy popcorn pouch", "5", 35, 40, "70 g", 35),
  p("p447", "Too Yumm Multigrain Chips", "टू यम मल्टीग्रेन", "Too Yumm Multigrain Chips Tangy Tomato — baked, not fried, healthy snack", "5", 30, 35, "54 g", 35),
  p("p448", "Too Yumm Karare Sweet Chilli", "टू यम करारे", "Too Yumm Karare Sweet Chilli — baked sticks with sweet chilli flavour", "5", 30, 35, "60 g", 32),
  p("p449", "Too Yumm Roasted Makhana Cream & Onion", "टू यम मखाना", "Too Yumm Roasted Makhana Cream & Onion — guilt-free foxnut snack", "5", 60, 75, "30 g", 30),
  p("p450", "Too Yumm Foxnuts Pudina", "टू यम फॉक्सनट्स", "Too Yumm Roasted Foxnuts Pudina — refreshing mint makhana, healthy crunch", "5", 60, 75, "30 g", 28),
  p("p451", "Beyond Snack Banana Chips Salted", "बियॉन्ड स्नैक बनाना", "Beyond Snack Kerala Banana Chips Classic Salted — naturally crunchy", "5", 99, 110, "100 g", 30),
  p("p452", "Beyond Snack Peri Peri Banana Chips", "बियॉन्ड पेरी पेरी", "Beyond Snack Peri Peri Banana Chips — bold peri peri Kerala chips", "5", 99, 110, "100 g", 28),
  p("p453", "Open Secret Cookies Choco Almond", "ओपन सीक्रेट कुकीज़", "Open Secret Unjunk Cookies Choco Almond — healthy hidden veggies cookies", "5", 99, 120, "75 g", 30),
  p("p454", "Lehar Kurkure Funjabi Kadhai Masala", "लहर फनजाबी", "Lehar Funjabi Kadhai Masala — Punjabi-style spicy crunchy snack", "5", 20, 25, "65 g", 35),
  p("p455", "Anand Banana Chips", "आनंद बनाना चिप्स", "Anand Banana Chips Salted — traditional Kerala-style banana chips", "5", 70, 80, "200 g", 25),
  p("p456", "Diamond Bhel Mixture", "डायमंड मिक्सचर", "Diamond Bhel Mixture — classic Indian namkeen mix with sev and dal", "5", 50, 55, "200 g", 25),
  p("p457", "Aloo Sev Namkeen", "आलू सेव", "Crispy Aloo Sev — spicy potato sev, perfect for chaat topping or snack", "5", 45, 55, "200 g", 28),
  p("p458", "Mathri Salted", "नमकीन मठरी", "Traditional Salted Mathri — flaky deep-fried North Indian tea snack", "5", 60, 70, "200 g", 25),
  p("p459", "Roasted Chana Salted", "भुना चना", "Roasted Chana Salted — protein-rich black chickpeas, healthy bite", "5", 40, 50, "200 g", 35),
  p("p460", "Snickers Chocolate Bar", "स्निकर्स", "Snickers Peanut Caramel Chocolate Bar — hunger-busting snack bar", "5", 50, 60, "50 g", 40),
  p("p461", "Mars Chocolate Bar", "मार्स", "Mars Caramel Nougat Chocolate Bar — smooth caramel filling, classic bar", "5", 50, 60, "51 g", 35),
  p("p462", "Bounty Coconut Bar", "बाउंटी", "Bounty Coconut Chocolate Bar — tender coconut covered in milk chocolate", "5", 50, 60, "57 g", 30),
  p("p463", "Twisties Cheese Puffs", "ट्विस्टीज़ चीज़", "Twisties Cheese Flavoured Corn Puffs — light cheesy twisted snack", "5", 20, 25, "60 g", 35),
  p("p464", "Pretzels Salted", "प्रेट्ज़ल्स", "Classic Salted Pretzels — crunchy twisted baked bites, popular party snack", "5", 80, 99, "100 g", 25),
  p("p465", "Sabudana Chips", "साबूदाना चिप्स", "Sabudana Tapioca Chips — crispy lightly salted vrat-friendly snack", "5", 55, 65, "150 g", 25),
  p("p466", "Bhakarwadi", "भाकरवड़ी", "Maharashtrian Bhakarwadi — spiced spiral snack with chatpata filling", "5", 60, 70, "200 g", 25),
  p("p467", "Soan Papdi Bikaji", "सोन पापड़ी बीकाजी", "Bikaji Soan Papdi — flaky melt-in-mouth Indian sweet, festive favourite", "5", 80, 99, "250 g", 30),
  p("p468", "Pop Drop Cheese Balls", "पॉप ड्रॉप चीज़", "Pop Drop Cheese Balls — crunchy cheesy puff balls, kids' party snack", "5", 20, 25, "60 g", 40),
  p("p469", "Bingo Tedhe Medhe Tangy Tomato", "बिंगो टैंगी टोमैटो", "Bingo Tedhe Medhe Tangy Tomato — wavy snack with tangy tomato kick", "5", 20, 25, "70 g", 45),
];
