import type { Product } from "@/types";
import { p } from "./_helper";

/** Fruits & Vegetables — 47 products. Loaded lazily by the catalogue hook. */
export const products: Product[] = [
  p("p1", "Tamatar (Tomato)", "टमाटर", "Hand-picked farm-fresh tomatoes, ripe and juicy — perfect for sabzi, curry, and salads", "3", 30, 40, "500 g", 50),
  p("p2", "Pyaz (Onion)", "प्याज", "Premium red onions sourced from Nashik farms — strong flavour, ideal for daily cooking", "3", 35, 45, "1 kg", 60),
  p("p3", "Aloo (Potato)", "आलू", "Farm-fresh raw potatoes, washed and graded — versatile for sabzi, fries, and curries", "3", 28, 35, "1 kg", 70),
  p("p4", "Kela (Banana)", "केला", "Naturally ripened bananas, rich in potassium — great for breakfast and post-workout snack", "3", 45, 50, "1 dozen", 30),
  p("p5", "Shimla Mirch (Capsicum)", "शिमला मिर्च", "Crunchy green capsicum, freshly harvested — adds colour and flavour to stir-fries and pizzas", "3", 40, 50, "250 g", 25),
  p("p6", "Palak (Spinach)", "पालक", "Tender baby spinach leaves, washed and ready — packed with iron, perfect for palak dishes", "3", 20, 25, "1 bunch", 35),
  p("p7", "Gajar (Carrot)", "गाजर", "Bright orange carrots, naturally sweet — eat raw, juice, or cook in halwa and sabzi", "3", 35, 42, "500 g", 40),
  p("p8", "Gobhi (Cauliflower)", "गोभी", "Tightly-packed fresh cauliflower head — versatile for aloo gobi, parathas, and pakoras", "3", 30, 40, "1 pc", 20),
  p("p9", "Bhindi (Lady Finger)", "भिंडी", "Tender young okra (bhindi), hand-picked — ideal for masala bhindi and kurkuri preparations", "3", 35, 45, "250 g", 30),
  p("p10", "Mirchi Hari (Green Chilli)", "हरी मिर्च", "Spicy fresh green chillies (hari mirch) — essential tadka and garnish ingredient", "3", 10, 15, "100 g", 60),
  p("p11", "Adrak (Ginger)", "अदरक", "Aromatic fresh ginger root — adds zing to chai, sabzi, and Indian curries", "3", 25, 30, "100 g", 40),
  p("p12", "Lehsun (Garlic)", "लहसुन", "Plump garlic cloves with natural skin — strong aroma, key for tadka and marinades", "3", 30, 40, "200 g", 35),
  p("p13", "Dhaniya Patta (Coriander)", "धनिया पत्ता", "Fresh coriander leaves with stems (dhaniya patta) — finishing touch for every Indian dish", "3", 10, 12, "1 bunch", 50),
  p("p14", "Nimbu (Lemon)", "नींबू", "Juicy thin-skinned lemons — perfect for nimbu pani, dal, and salad dressings", "3", 20, 25, "4 pcs", 45),
  p("p15", "Seb (Apple)", "सेब", "Crisp Shimla apples, naturally sweet — ideal for snacking and lunchbox", "3", 120, 150, "500 g", 20),
  p("p16", "Santra (Orange)", "संतरा", "Sweet seedless Nagpur oranges — refreshing, rich in vitamin C", "3", 60, 70, "500 g", 25),
  p("p17", "Papita (Papaya)", "पपीता", "Ripe sweet papaya — eat fresh or use in smoothies and salads", "3", 40, 50, "1 pc", 15),
  p("p18", "Aam (Mango)", "आम", "Sweet seasonal desi mango — enjoy chilled or in shakes, raita, and aamras", "3", 80, 100, "500 g", 30),
  p("p311", "Khira (Cucumber)", "खीरा", "Crunchy hydrating cucumber — perfect for salad, raita and sandwich", "3", 30, 35, "500 g", 60),
  p("p312", "Khumbi (Button Mushroom)", "खुम्बी", "Fresh white button mushrooms — great for matar mushroom and pizza", "3", 65, 75, "200 g", 35),
  p("p313", "Karela (Bitter Gourd)", "करेला", "Fresh tender bitter gourd — great for stuffed karela and juice", "3", 35, 40, "500 g", 40),
  p("p314", "Lauki (Bottle Gourd)", "लौकी", "Tender bottle gourd for sabzi, kofta and halwa — light and cooling", "3", 30, 35, "1 pc", 45),
  p("p315", "Tinda (Apple Gourd)", "टिंडा", "Small round tinda — perfect for North Indian masala sabzi", "3", 55, 65, "500 g", 30),
  p("p316", "Parwal (Pointed Gourd)", "परवल", "Fresh green parwal — ideal for Bihari and UP-style stuffed sabzi", "3", 60, 70, "500 g", 30),
  p("p317", "Baingan (Brinjal)", "बैंगन", "Dark purple brinjal — perfect for baingan bharta and bharli bhaji", "3", 35, 40, "500 g", 50),
  p("p318", "Matar (Green Peas)", "हरी मटर", "Sweet shelled green peas — makes great matar paneer and pulao", "3", 70, 80, "500 g", 45),
  p("p319", "Methi Patta (Fenugreek)", "मेथी पत्ता", "Fresh aromatic methi leaves — for methi paratha and aloo methi", "3", 25, 30, "250 g", 50),
  p("p320", "Mooli (Radish)", "मूली", "Crisp white radish — perfect for mooli paratha and salad", "3", 30, 35, "500 g", 40),
  p("p321", "Chukandar (Beetroot)", "चुकंदर", "Iron-rich beetroot — great for salad, juice and beetroot tikki", "3", 35, 40, "500 g", 40),
  p("p322", "Sakarkand (Sweet Potato)", "शकरकंद", "Naturally sweet purple sweet potato — perfect for chaat and roast", "3", 50, 60, "500 g", 45),
  p("p323", "Bhutta (Sweet Corn)", "भुट्टा", "Tender American sweet corn — makes bhutta masala and soup (2 pcs)", "3", 35, 40, "2 pcs", 50),
  p("p324", "Anar (Pomegranate)", "अनार", "Juicy ruby-red pomegranate — packed with antioxidants", "3", 140, 160, "500 g", 50),
  p("p325", "Angoor Green (Grapes)", "हरे अंगूर", "Sweet seedless green grapes from Nashik — perfect snack", "3", 75, 85, "500 g", 45),
  p("p326", "Angoor Black (Grapes)", "काले अंगूर", "Juicy black grapes — naturally sweet, rich in antioxidants", "3", 90, 100, "500 g", 40),
  p("p327", "Tarbooz (Watermelon)", "तरबूज", "Sweet juicy watermelon — summer must-have, naturally cooling", "3", 55, 65, "1 kg", 35),
  p("p328", "Kharbooja (Muskmelon)", "खरबूजा", "Fragrant sweet muskmelon — perfect summer fruit, rich aroma", "3", 50, 60, "1 kg", 30),
  p("p329", "Chiku (Sapota)", "चीकू", "Soft brown chiku — naturally sweet caramel-like fruit", "3", 65, 75, "500 g", 35),
  p("p330", "Strawberry", "स्ट्रॉबेरी", "Fresh Mahabaleshwar strawberries — sweet-tart, premium pack", "3", 110, 130, "200 g", 30),
  p("p331", "Kiwi (4 pcs)", "कीवी", "Imported green kiwi — vitamin C powerhouse", "3", 130, 150, "4 pcs", 35),
  p("p332", "Pineapple (Anaras)", "अनानास", "Sweet juicy pineapple from Kerala — great for juice and dessert", "3", 75, 90, "1 pc", 30),
  p("p333", "Litchi", "लीची", "Fresh sweet litchis from Muzaffarpur — juicy summer treat", "3", 140, 160, "500 g", 25),
  p("p334", "Sahjan (Drumstick)", "सहजन", "Fresh drumsticks for sambar, dal and moringa sabzi (bundle)", "3", 40, 50, "250 g", 40),
  p("p335", "Kaddu (Pumpkin)", "कद्दू", "Tender orange pumpkin — perfect for kaddu sabzi and halwa", "3", 30, 35, "500 g", 40),
  p("p336", "Curry Patta (Curry Leaves)", "करी पत्ता", "Fresh aromatic curry leaves — for tadka, sambar and poha", "3", 15, 20, "50 g", 60),
  p("p337", "Pudina (Mint Leaves)", "पुदीना", "Fresh mint leaves — for chutney, raita and mint lemonade", "3", 15, 20, "100 g", 55),
  p("p338", "Hara Pyaaz (Spring Onion)", "हरा प्याज़", "Fresh spring onions with green stalks — for noodles and garnish", "3", 25, 30, "250 g", 50),
  p("p339", "Nariyal Hara (Tender Coconut)", "हरा नारियल", "Naturally chilled tender coconut — sweet refreshing nariyal pani", "3", 55, 65, "1 pc", 35),
  p("p1095", "Patta Gobhi (Cabbage)", "पत्ता गोभी", "Fresh tightly-packed green cabbage head — for stir fry, salad and rolls", "3", 35, 45, "1 pc", 50),
  p("p1096", "Broccoli", "ब्रोकोली", "Fresh green broccoli florets — antioxidant-rich, stir fry favourite", "3", 75, 90, "300 g", 35),
  p("p1097", "Lettuce Iceberg", "लेटस आइसबर्ग", "Crisp iceberg lettuce head — perfect for burgers, sandwiches and salads", "3", 70, 85, "1 pc", 30),
  p("p1098", "Spinach Pre-washed 250g", "धुली पालक", "Triple-washed ready-to-cook baby spinach — saves prep time", "3", 45, 55, "250 g", 40),
  p("p1099", "Sarson ka Saag (Mustard Greens)", "सरसों का साग", "Fresh Punjabi mustard greens — winter staple for makki ki roti", "3", 40, 50, "500 g", 35),
  p("p1100", "Bathua Saag", "बथुआ साग", "Fresh tender bathua leaves — for raita, parathas and winter dal", "3", 35, 45, "250 g", 35),
  p("p1101", "Chana Saag", "चना साग", "Tender green gram leaves — traditional winter sabzi with garlic tadka", "3", 35, 45, "250 g", 30),
  p("p1102", "Turai (Ridge Gourd)", "तुरई", "Fresh ridged gourd — light cooling sabzi with chana dal", "3", 40, 50, "500 g", 40),
  p("p1103", "Snake Gourd (Chichinda)", "चिचिंडा", "Long green snake gourd — South Indian sambar and stir fry favourite", "3", 50, 60, "500 g", 30),
  p("p1104", "Petha (Ash Gourd)", "पेठा कद्दू", "Fresh white ash gourd — for petha sweets, sambar and juice", "3", 35, 45, "1 kg", 30),
  p("p1105", "Zucchini Green", "हरा ज़ुकीनी", "Fresh imported green zucchini — for pasta, grills and Italian dishes", "3", 80, 95, "500 g", 30),
  p("p1106", "Zucchini Yellow", "पीला ज़ुकीनी", "Fresh yellow zucchini — vibrant Italian squash for stir fries", "3", 85, 100, "500 g", 25),
  p("p1107", "Bell Pepper Red", "लाल शिमला मिर्च", "Sweet red bell pepper — vitamin-rich, perfect for salads and stuffing", "3", 75, 90, "250 g", 35),
  p("p1108", "Bell Pepper Yellow", "पीली शिमला मिर्च", "Vibrant sweet yellow bell pepper — for fajitas and Mediterranean dishes", "3", 80, 95, "250 g", 30),
  p("p1109", "Cherry Tomato 200g", "चेरी टमाटर", "Sweet bite-sized cherry tomatoes — for salads, pasta and snacking", "3", 60, 70, "200 g", 40),
  p("p1110", "Baby Corn 200g", "बेबी कॉर्न", "Tender baby corn cobs — perfect for Manchurian, stir fry and soups", "3", 55, 65, "200 g", 35),
  p("p1111", "Mushroom Oyster", "ऑयस्टर मशरूम", "Delicate fresh oyster mushrooms — gourmet variety for stir fry and pasta", "3", 95, 110, "200 g", 25),
  p("p1112", "Mushroom Shiitake", "शिटाके मशरूम", "Premium dried-fresh shiitake mushrooms — earthy umami flavour", "3", 145, 165, "100 g", 20),
  p("p1113", "Suran (Yam)", "सुरन", "Fresh elephant foot yam — for traditional sabzi and chutney", "3", 65, 75, "500 g", 30),
  p("p1114", "Singhara (Water Chestnut)", "सिंघाड़ा", "Fresh water chestnuts — for vrat aata, chaat and stir fry", "3", 80, 95, "500 g", 25),
  p("p1115", "Avocado 1 pc", "एवोकाडो", "Creamy ripe Hass avocado — for toast, smoothies and guacamole", "3", 90, 110, "1 pc", 30),
  p("p1116", "Dragon Fruit 1 pc", "ड्रैगन फ्रूट", "Exotic pink-flesh dragon fruit — antioxidant superfruit, mildly sweet", "3", 95, 120, "1 pc", 25),
  p("p1117", "Passion Fruit 3 pc", "पैशन फ्रूट", "Aromatic ripe passion fruits — tangy tropical, perfect for desserts", "3", 145, 170, "3 pcs", 20),
  p("p1118", "Mosambi (Sweet Lime) 1kg", "मौसंबी", "Sweet juicy mosambi — perfect for fresh juice, vitamin-C rich", "3", 75, 90, "1 kg", 40),
  p("p1119", "Sitaphal (Custard Apple)", "सीताफल", "Creamy sweet custard apple — naturally sugary winter fruit", "3", 110, 130, "500 g", 30),
  p("p1120", "Jamun (Black Plum)", "जामुन", "Tart-sweet black jamun — seasonal monsoon fruit, diabetic-friendly", "3", 95, 110, "250 g", 25),
  p("p1121", "Cherries Imported 200g", "चेरी", "Premium imported red cherries — sweet juicy, premium snacking", "3", 285, 325, "200 g", 25),
  p("p1122", "Pear Imported", "नाशपाती", "Crisp imported sweet pears — refreshing snack, lunchbox favourite", "3", 145, 170, "500 g", 30),
  p("p1123", "Moong Sprouts 200g", "मूंग स्प्राउट्स", "Fresh moong bean sprouts — ready-to-use, high-protein salad mix", "3", 30, 35, "200 g", 40),
  p("p1124", "Mixed Sprouts 200g", "मिक्स्ड स्प्राउट्स", "Healthy mixed sprouts — moong, chana, moth, rajma combo", "3", 45, 55, "200 g", 35),
  p("p1125", "Stir Fry Veg Mix 250g", "स्टिर फ्राई मिक्स", "Pre-cut stir fry mix — broccoli, capsicum, baby corn, mushrooms", "3", 95, 115, "250 g", 30),
  p("p1126", "Sumeru Frozen Green Peas", "सुमेरू फ्रोज़न मटर", "Frozen IQF green peas — flash-frozen at peak ripeness, ready to cook", "3", 95, 110, "500 g", 50),
  p("p1127", "Sumeru Frozen Sweet Corn", "सुमेरू फ्रोज़न कॉर्न", "Frozen American sweet corn kernels — golden sweet, ready to use", "3", 110, 125, "500 g", 45),
  p("p1128", "Lemongrass 100g", "लेमनग्रास", "Fresh aromatic lemongrass stalks — for Thai curries, soup and tea", "3", 30, 40, "100 g", 40),
  p("p1129", "Grated Coconut Fresh 200g", "नारियल बूरा", "Freshly grated white coconut — for chutney, sweets and curries", "3", 55, 65, "200 g", 40),
];
