import type { Product } from "@/types";
import { p } from "./_helper";

/** Paan Corner — 12 products. Loaded lazily by the catalogue hook. */
export const products: Product[] = [
  p("p159", "Pulse Kachcha Aam Candy", "पल्स कच्चा आम कैंडी", "Pulse mango hard candy with tangy aam churan centre — India's iconic sweet-sour treat", "1", 1, 1, "1 pc", 60),
  p("p160", "Rajnigandha Silver Pearls Elaichi", "रजनीगंधा सिल्वर पर्ल्स", "Premium silver-coated cardamom mouth freshener — classic after-meal indulgence", "1", 60, 65, "6 g", 40),
  p("p161", "Dabur Hajmola Imli Candy", "डाबर हाजमोला इमली", "Tangy tamarind digestive candy — helps after heavy Indian meals, family favourite", "1", 55, 60, "120 g jar", 50),
  p("p162", "Center Fresh Spearmint Gum", "सेंटर फ्रेश चूइंग गम", "Liquid-filled spearmint chewing gum — freshens breath instantly, on-the-go", "1", 90, 100, "26 pcs", 45),
  p("p163", "Mentos Pure Fresh Mint Sugar Free", "मेंटोस प्योर फ्रेश मिंट गम", "Sugar-free mint chewing gum bottle — long-lasting freshness, dentist-friendly", "1", 91, 100, "54 g", 35),
  p("p164", "Happydent White Spearmint", "हैप्पीडेंट व्हाइट", "Sugar-free spearmint gum that whitens teeth while freshening breath", "1", 47, 50, "24 g", 50),
  p("p165", "Nestle Polo Mint", "पोलो मिंट", "Classic ring-shaped mint — refreshing peppermint flavour, the mint with the hole", "1", 44, 50, "100 g", 45),
  p("p166", "Pulse Guava Candy Jar", "पल्स अमरूद कैंडी", "Guava-flavour Pulse candy with chatpata churan filling — tangy treat", "1", 60, 60, "100 g jar", 40),
  p("p167", "Pass Pass Kacha Aam Mukhwas", "पास पास कच्चा आम", "Pocket-pack mouth freshener with raw mango, supari and saunf blend", "1", 5, 5, "10 g", 60),
  p("p168", "Vimal Elaichi Mukhwas", "विमल इलायची मुखवास", "Non-tobacco cardamom mouth freshener with saunf and sweet supari", "1", 10, 10, "8 g", 60),
  p("p169", "Mukhwas Saunf Sweet Mix", "मीठी सौंफ मुखवास", "Classic sugar-coated fennel mukhwas — traditional Indian after-meal digestive", "1", 65, 75, "200 g", 30),
  p("p170", "Mentos Assorted Fruit Roll", "मेंटोस फ्रूट कैंडी", "Chewy assorted fruit candy roll — mixed strawberry, orange and lemon flavours", "1", 20, 20, "37 g", 50),
  p("p1180", "Parle Mango Bite Roll", "मैंगो बाइट रोल", "Parle Mango Bite — chewy tangy-sweet mango candy in single roll", "1", 10, 10, "33 g", 60),
  p("p1181", "Parle Coffee Bite Roll", "कॉफी बाइट रोल", "Parle Coffee Bite — classic coffee-caramel chewy candy roll", "1", 10, 10, "33 g", 55),
  p("p1182", "Cadbury Chocolate Eclairs Roll", "चॉकलेट एक्लेयर्स", "Cadbury Eclairs — chocolate-filled caramel candy, all-time favourite", "1", 25, 25, "75 g", 55),
  p("p1183", "Alpenliebe Strawberry Candy", "अल्पेनलिबे स्ट्राबेरी", "Strawberry caramel candy — creamy with real strawberry flavour", "1", 10, 10, "47 g", 60),
  p("p1184", "Melody Chocolate Filled Toffee", "मेलोडी टॉफी", "Parle Melody — chocolate-filled coconut-caramel toffee, retro favourite", "1", 30, 35, "100 pcs jar", 40),
  p("p1185", "Fruitella Apple", "फ्रूटेला एप्पल", "Fruitella chewy apple candy — natural fruit flavour, kid-friendly roll", "1", 10, 10, "32 g", 55),
  p("p1186", "Mentos Strawberry Roll", "मेंटोस स्ट्राबेरी", "Mentos chewy strawberry candy roll — fresh fruity bursting flavour", "1", 10, 10, "37 g", 55),
  p("p1187", "Mentos Apple Roll", "मेंटोस एप्पल", "Mentos crisp apple chewy candy roll — refreshingly tangy", "1", 10, 10, "37 g", 55),
  p("p1188", "Mentos Sour Mix", "मेंटोस सावर मिक्स", "Sour mixed-fruit Mentos chews — assorted tangy flavours roll", "1", 10, 10, "37 g", 50),
  p("p1189", "Vimal Pan Masala 200g", "विमल पान मसाला", "Vimal premium pan masala without tobacco — for paan masala lovers", "1", 95, 110, "200 g", 30),
  p("p1190", "Manikchand Saffron Mukhwas 90g", "माणिकचंद केसर मुखवास", "Premium kesar mukhwas — saffron-infused mouth freshener, royal taste", "1", 175, 195, "90 g", 25),
  p("p1191", "Pass Pass Pulse Litchi", "पास पास लीची", "Pass Pass Pulse litchi-flavour candy — pocket-sized tangy treat", "1", 10, 10, "15 g", 60),
  p("p1192", "Center Fresh Strawberry Gum", "सेंटर फ्रेश स्ट्राबेरी", "Liquid-filled strawberry chewing gum — sweet fruity burst", "1", 90, 100, "26 pcs", 40),
  p("p1193", "Center Fresh Watermelon Gum", "सेंटर फ्रेश तरबूज", "Liquid-filled watermelon gum — juicy summer flavour, kid favourite", "1", 90, 100, "26 pcs", 40),
  p("p1194", "Boomer Strawberry Gum", "बूमर स्ट्राबेरी गम", "Boomer pink chewing gum — strawberry flavour, blow big bubbles", "1", 5, 5, "4 g", 65),
  p("p1195", "Big Babol Cola Bubblegum", "बिग बबल कोला", "Big Babol cola flavour bubblegum — long-lasting cola fizz, big bubbles", "1", 5, 5, "5 g", 60),
  p("p1196", "Big Babol Mixed Fruit", "बिग बबल मिक्स्ड फ्रूट", "Big Babol mixed fruit bubblegum — assorted fruity flavours", "1", 5, 5, "5 g", 60),
  p("p1197", "Hajmola Pudina", "हाजमोला पुदीना", "Dabur Hajmola pudina — cooling mint digestive candy after meals", "1", 55, 60, "120 g jar", 45),
  p("p1198", "Hajmola Anardana", "हाजमोला अनारदाना", "Dabur Hajmola anardana — pomegranate-tang digestive candy", "1", 55, 60, "120 g jar", 45),
  p("p1199", "Hajmola Chatpata Imli", "हाजमोला चटपटा इमली", "Dabur Hajmola chatpata imli — extra-tangy tamarind digestive candy", "1", 55, 60, "120 g jar", 45),
  p("p1200", "Mukhwas Mixed Saunf 100g", "मिक्स सौंफ मुखवास", "Mixed sugar-coated saunf — colourful traditional mukhwas with dhania", "1", 55, 65, "100 g", 35),
  p("p1201", "Sweet Supari Mukhwas 100g", "मीठी सुपारी", "Sweet roasted supari — natural after-meal mukhwas, sugar-coated", "1", 65, 75, "100 g", 30),
  p("p1202", "Center Fruit Lollipop", "सेंटर फ्रूट लॉलीपॉप", "Cadbury Center Fruit lollipops — chewy fruit centre, party pack", "1", 30, 35, "10 pcs", 40),
  p("p1203", "Chupa Chups Mega Lollipop", "चूपा चूप्स लॉलीपॉप", "Chupa Chups assorted lollipops — fruity flavours, family pack of 8", "1", 80, 90, "8 pcs", 35),
  p("p1204", "Halls Mango Lozenges", "हॉल्स मैंगो", "Mondelez Halls mango-flavour throat lozenges — sweet and soothing", "1", 12, 15, "10 pcs", 60),
];
