import type { Product } from "@/types";
import { p } from "./_helper";

/** Masala, Oil & More — 21 products. Loaded lazily by the catalogue hook. */
export const products: Product[] = [
  p("p46", "Fortune Soyabean Oil", "फॉर्च्यून तेल", "Fortune refined soyabean oil — light and healthy, ideal for everyday cooking", "11", 155, 175, "1 L", 25),
  p("p47", "Fortune Sunflower Oil", "फॉर्च्यून सनफ्लावर", "Fortune refined sunflower oil — heart-friendly, low in saturated fat", "11", 155, 175, "1 L", 20),
  p("p48", "Amul Ghee", "अमूल घी", "Amul pure cow ghee — granular, aromatic, made from rich Indian milk", "11", 290, 320, "500 ml", 15),
  p("p49", "Patanjali Mustard Oil", "पतंजलि सरसों तेल", "Patanjali kachi ghani mustard oil — cold-pressed, traditional pungent flavour", "11", 170, 190, "1 L", 20),
  p("p50", "Saffola Gold Oil", "सैफोला गोल्ड", "Saffola Gold blended oil — rice bran + corn oil, supports heart health", "11", 185, 210, "1 L", 15),
  p("p51", "Sundrop Refined Oil", "सनड्रॉप तेल", "Sundrop refined sunflower oil — light, clean taste for daily cooking", "11", 150, 168, "1 L", 18),
  p("p52", "MDH Garam Masala", "एमडीएच गरम मसाला", "MDH Garam Masala — authentic blend of 11 spices, signature aroma for curries", "11", 72, 80, "100 g", 35),
  p("p53", "Haldi Powder (Turmeric)", "हल्दी पाउडर", "Pure turmeric powder (haldi) — bright yellow, high-curcumin, daily essential", "11", 40, 48, "100 g", 40),
  p("p54", "Lal Mirch Powder", "लाल मिर्च पाउडर", "Kashmiri red chilli powder (lal mirch) — rich colour with balanced heat", "11", 55, 65, "100 g", 35),
  p("p55", "Dhaniya Powder (Coriander)", "धनिया पाउडर", "Fresh-ground coriander powder (dhaniya) — earthy aroma, base spice for curries", "11", 32, 38, "100 g", 40),
  p("p56", "Jeera Powder (Cumin)", "जीरा पाउडर", "Roasted cumin powder (jeera) — warm nutty flavour, perfect for raita and chaat", "11", 58, 68, "100 g", 30),
  p("p57", "Sabut Jeera (Cumin Seeds)", "साबुत जीरा", "Whole cumin seeds (sabut jeera) — for tadka, jeera rice, and tempering", "11", 65, 75, "100 g", 35),
  p("p58", "Sabut Dhaniya (Coriander Seeds)", "साबुत धनिया", "Whole coriander seeds (sabut dhaniya) — roast and grind fresh, full aroma", "11", 28, 35, "100 g", 40),
  p("p59", "Rai / Sarson (Mustard Seeds)", "राई / सरसों", "Black mustard seeds (rai/sarson) — essential for South Indian tadka and pickles", "11", 20, 25, "100 g", 50),
  p("p60", "Kali Mirch (Black Pepper)", "काली मिर्च", "Whole black peppercorns (kali mirch) — grind fresh for maximum flavour", "11", 85, 99, "50 g", 25),
  p("p61", "Hing (Asafoetida)", "हींग", "Strong asafoetida (hing) powder — aids digestion, signature smoky aroma", "11", 55, 65, "10 g", 30),
  p("p62", "Chaat Masala", "चाट मसाला", "Tangy chaat masala — sprinkle on fruits, chaat, and salads for instant zing", "11", 30, 35, "100 g", 40),
  p("p63", "Pav Bhaji Masala", "पाव भाजी मसाला", "MDH Pav Bhaji Masala — Mumbai-style authentic blend, ready in minutes", "11", 45, 52, "100 g", 25),
  p("p64", "Kitchen King Masala", "किचन किंग मसाला", "MDH Kitchen King Masala — versatile all-purpose blend for everyday sabzi", "11", 55, 62, "100 g", 28),
  p("p65", "Namak (Salt)", "नमक", "Tata Salt iodized — India's most trusted, fine free-flowing salt", "11", 24, 28, "1 kg", 60),
  p("p66", "Cheeni (Sugar)", "चीनी", "Pure refined white sugar — fine grain, perfect for tea, sweets, and baking", "11", 42, 48, "1 kg", 40),
  p("p505", "MDH Sambhar Masala", "एमडीएच सांभर", "MDH Sambhar Masala — authentic South Indian tangy spice blend", "11", 55, 65, "100 g", 30),
  p("p506", "MDH Biryani Masala", "एमडीएच बिरयानी", "MDH Biryani Masala — aromatic blend for fragrant chicken or veg biryani", "11", 65, 75, "100 g", 30),
  p("p507", "MDH Chana Masala", "एमडीएच चना मसाला", "MDH Chana Masala — perfect spice mix for restaurant-style chole", "11", 55, 62, "100 g", 35),
  p("p508", "MDH Chicken Masala", "एमडीएच चिकन", "MDH Chicken Masala — special blend for spicy aromatic chicken curry", "11", 55, 65, "100 g", 25),
  p("p509", "MDH Meat Masala", "एमडीएच मीट मसाला", "MDH Meat Masala — robust blend for mutton, lamb, and goat curries", "11", 60, 70, "100 g", 22),
  p("p510", "MDH Rajma Masala", "एमडीएच राजमा", "MDH Rajma Masala — classic Punjabi blend for kidney bean curry", "11", 50, 60, "100 g", 25),
  p("p511", "MDH Tandoori Masala", "एमडीएच तंदूरी", "MDH Tandoori Mixed Masala — smoky tandoori blend for grills and tikka", "11", 55, 62, "100 g", 25),
  p("p512", "MDH Sabzi Masala", "एमडीएच सब्जी", "MDH Sabzi Masala — versatile blend for daily vegetable curries", "11", 50, 58, "100 g", 28),
  p("p513", "MDH Achaar Masala", "एमडीएच आचार", "MDH Achaar Masala — classic pickle blend for homemade Indian pickles", "11", 65, 75, "100 g", 22),
  p("p514", "MDH Madras Sambar Powder", "एमडीएच मद्रास", "MDH Madras Sambar Powder — authentic South Indian sambar blend", "11", 55, 65, "100 g", 25),
  p("p515", "Everest Garam Masala", "एवरेस्ट गरम", "Everest Garam Masala — premium blend, signature aroma for North Indian curries", "11", 70, 80, "100 g", 30),
  p("p516", "Everest Sabzi Masala", "एवरेस्ट सब्जी", "Everest Sabzi Masala — perfect everyday vegetable curry spice mix", "11", 50, 58, "100 g", 28),
  p("p517", "Everest Pav Bhaji Masala", "एवरेस्ट पाव भाजी", "Everest Pav Bhaji Masala — authentic Mumbai-style pav bhaji blend", "11", 45, 52, "100 g", 30),
  p("p518", "Everest Tikka Masala", "एवरेस्ट तिक्का", "Everest Tikka Masala — restaurant-style tikka blend for grills and curries", "11", 55, 65, "100 g", 25),
  p("p519", "Everest Tea Masala", "एवरेस्ट चाय मसाला", "Everest Tea Masala — aromatic spice blend for soothing masala chai", "11", 50, 58, "50 g", 25),
  p("p520", "Catch Sprinklers Chaat Masala", "कैच चाट मसाला", "Catch Sprinklers Chaat Masala — tangy chaat blend in convenient bottle", "11", 70, 80, "100 g", 28),
  p("p521", "Tata Sampann Chana Masala", "टाटा संपन्न चना", "Tata Sampann Chana Masala — natural ingredients, no artificial colour", "11", 55, 62, "100 g", 25),
  p("p522", "Tata Sampann Garam Masala", "टाटा संपन्न गरम", "Tata Sampann Garam Masala — chef-curated blend of 12 spices", "11", 75, 85, "100 g", 22),
  p("p523", "Dabur Hommade Ginger Garlic Paste", "अदरक लहसुन पेस्ट", "Dabur Hommade Ginger Garlic Paste — fresh paste, no preservatives", "11", 80, 90, "200 g", 25),
  p("p524", "Cumin Whole 200g Jar", "साबुत जीरा जार", "Premium Whole Cumin Seeds — fragrant tadka essential, family-size jar", "11", 130, 150, "200 g", 25),
  p("p525", "Mustard Whole 200g", "साबुत राई जार", "Premium Black Mustard Seeds — for South Indian tadka and pickle", "11", 50, 60, "200 g", 30),
  p("p526", "Tej Patta (Bay Leaves)", "तेज पत्ता", "Premium Dried Bay Leaves — aromatic essential for biryani and curries", "11", 35, 45, "25 g", 30),
  p("p527", "Dalchini (Cinnamon Stick)", "दालचीनी", "Whole Cinnamon Sticks — fragrant warm spice for biryani and chai", "11", 60, 70, "50 g", 25),
  p("p528", "Laung (Cloves)", "लौंग", "Whole Cloves (Laung) — intense warm spice essential for garam masala", "11", 90, 105, "50 g", 25),
  p("p529", "Elaichi Choti (Green Cardamom)", "छोटी इलायची", "Premium Green Cardamom Pods — fragrant essential for chai and sweets", "11", 220, 250, "50 g", 18),
  p("p530", "Elaichi Badi (Black Cardamom)", "बड़ी इलायची", "Black Cardamom Pods — smoky earthy spice for biryani and curries", "11", 120, 140, "50 g", 20),
  p("p531", "Methi Seeds (Fenugreek)", "मेथी दाना", "Whole Methi Seeds — bitter-aromatic spice for tadka and curry powders", "11", 30, 40, "100 g", 30),
  p("p532", "Ajwain (Carom Seeds)", "अजवायन", "Premium Ajwain Seeds — digestive aromatic spice for paratha and snacks", "11", 35, 45, "100 g", 35),
  p("p533", "Star Anise (Chakri Phool)", "चक्र फूल", "Whole Star Anise — exotic aromatic spice for biryani and stews", "11", 60, 75, "25 g", 22),
  p("p534", "Kalonji (Nigella Seeds)", "कलौंजी", "Premium Kalonji Seeds — onion-flavoured topping for naans and pickles", "11", 35, 45, "100 g", 30),
  p("p535", "Kasuri Methi", "कसूरी मेथी", "Premium Dried Kasuri Methi — fragrant fenugreek leaves for rich gravies", "11", 50, 60, "50 g", 30),
  p("p536", "Saffron / Kesar Kashmiri", "केसर", "Premium Kashmiri Saffron — pure aromatic strands for kheer and biryani", "11", 220, 260, "1 g", 18),
  p("p537", "Vanilla Essence", "वनिला एसेंस", "Pure Vanilla Essence — for baking cakes, ice creams, and desserts", "11", 50, 60, "100 ml", 25),
  p("p538", "Baking Powder", "बेकिंग पाउडर", "Premium Baking Powder — essential leavening agent for cakes and breads", "11", 40, 50, "100 g", 30),
  p("p539", "Baking Soda", "बेकिंग सोडा", "Pure Baking Soda — multipurpose leavening for baking and cooking", "11", 35, 42, "100 g", 30),
  p("p540", "Fortune Rice Bran Health Oil", "फॉर्च्यून राइस ब्रान", "Fortune Rice Bran Oil — heart-healthy with oryzanol, light cooking oil", "11", 175, 195, "1 L", 18),
  p("p541", "Saffola Active Oil", "सैफोला एक्टिव", "Saffola Active blended oil — promotes heart health, light taste", "11", 195, 220, "1 L", 18),
  p("p542", "Engine Brand Coconut Oil", "इंजन नारियल तेल", "Engine Brand Pure Coconut Oil — cold-pressed Kerala-style cooking oil", "11", 195, 220, "500 ml", 15),
  p("p543", "Bertolli Extra Virgin Olive Oil", "जैतून का तेल", "Bertolli Extra Virgin Olive Oil — premium Italian, salads and drizzling", "11", 650, 750, "500 ml", 12),
  p("p544", "Dalda Vanaspati Ghee", "डालडा वनस्पति", "Dalda Vanaspati Ghee — classic hydrogenated vegetable ghee for cooking", "11", 165, 185, "1 L", 15),
];
