import type { Product } from "@/types";
import { p } from "./_helper";

/** Cold Drinks & Juices — 29 products. Loaded lazily by the catalogue hook. */
export const products: Product[] = [
  p("p83", "Coca-Cola", "कोका-कोला", "Coca-Cola Original Taste — chilled fizzy refreshment, the classic cola", "4", 40, 45, "750 ml", 40),
  p("p84", "Thums Up", "थम्स अप", "Thums Up — strong, fizzy cola with kick, taste the thunder", "4", 40, 45, "750 ml", 35),
  p("p85", "Sprite", "स्प्राइट", "Sprite — clear lime-lemon drink, crisp and refreshing", "4", 40, 45, "750 ml", 30),
  p("p86", "Maaza Mango", "माज़ा आम", "Maaza Mango — thick rich mango drink, taste of Indian summer", "4", 25, 30, "250 ml", 45),
  p("p87", "Frooti Mango", "फ्रूटी आम", "Frooti Mango Drink — ripe sweet mango taste, India's favourite tetra pack", "4", 10, 12, "200 ml", 60),
  p("p94", "Rooh Afza Sharbat", "रूह अफ़ज़ा", "Hamdard Rooh Afza — classic rose-flavoured sharbat, summer cooler", "4", 120, 135, "750 ml", 15),
  p("p95", "Paper Boat Aam Panna", "पेपर बोट आम पन्ना", "Paper Boat Aam Panna — traditional raw mango drink, authentic desi taste", "4", 30, 35, "200 ml", 25),
  p("p96", "Limca", "लिम्का", "Limca — sparkling lime-lemon drink, India's original thirst-quencher", "4", 40, 45, "750 ml", 30),
  p("p97", "Real Fruit Juice Mixed", "रियल जूस मिक्स", "Real Mixed Fruit Juice — no added preservatives, daily fruit goodness", "4", 90, 99, "1 L", 15),
  p("p340", "Pepsi", "पेप्सी", "Iconic cola fizz — perfect with biryani and pizza, family pack", "4", 45, 50, "750 ml", 60),
  p("p341", "Mountain Dew", "माउंटेन ड्यू", "Citrus-charged Mountain Dew — bold thrill drink for parties", "4", 45, 50, "750 ml", 55),
  p("p342", "7UP", "सेवन अप", "Crisp lemon-lime fizz — refreshing clear soda for any meal", "4", 45, 50, "750 ml", 50),
  p("p343", "Mirinda Orange", "मिरिंडा ऑरेंज", "Tangy orange-flavoured fizzy drink — kids' favourite", "4", 45, 50, "750 ml", 55),
  p("p344", "Fanta Orange", "फैंटा", "Sparkling orange Fanta — classic party and celebration drink", "4", 45, 50, "750 ml", 50),
  p("p345", "Slice Aamsutra Mango", "स्लाइस आम", "Slice Aamsutra with real Alphonso pulp — thick mango juice", "4", 95, 105, "1 L", 45),
  p("p346", "Tropicana Orange Juice", "ट्रॉपिकाना ऑरेंज", "100% orange juice — no added sugar, fortified with vitamins", "4", 130, 145, "1 L", 35),
  p("p347", "Real Apple Juice", "रियल सेब जूस", "Dabur Real apple juice — fruit power for daily health", "4", 120, 135, "1 L", 35),
  p("p348", "Real Litchi Juice", "रियल लीची जूस", "Dabur Real litchi juice — exotic summer fruit drink", "4", 120, 135, "1 L", 30),
  p("p349", "Minute Maid Pulpy Orange", "मिनट मेड पल्पी ऑरेंज", "Real orange juice with pulp bits — refreshing and natural", "4", 50, 55, "400 ml", 50),
  p("p350", "Paper Boat Kala Khatta", "पेपर बोट काला खट्टा", "Nostalgic kala khatta with jamun — tangy desi cooler", "4", 35, 40, "250 ml", 45),
  p("p351", "Paper Boat Aamras", "पेपर बोट आमरस", "Authentic Alphonso aamras — ready-to-drink mango pulp drink", "4", 40, 45, "250 ml", 40),
  p("p352", "Appy Fizz", "एप्पी फिज़", "Sparkling apple fizz — India's first apple drink", "4", 25, 30, "250 ml", 60),
  p("p353", "Red Bull Energy Drink", "रेड बुल", "Globally loved energy boost — caffeine and taurine", "4", 125, 135, "250 ml", 50),
  p("p354", "Sting Energy Drink", "स्टिंग एनर्जी", "Sting red berry energy fizz — affordable instant kick", "4", 25, 30, "250 ml", 65),
  p("p355", "Coca-Cola Zero Sugar", "कोका-कोला ज़ीरो", "Zero sugar cola with classic Coke taste — guilt-free fizz", "4", 45, 50, "750 ml", 50),
  p("p356", "B Natural Mixed Fruit Juice", "बी नैचुरल मिक्स्ड फ्रूट", "ITC B Natural mixed fruit juice — no preservatives", "4", 110, 130, "1 L", 30),
  p("p357", "Bisleri Mineral Water", "बिसलेरी पानी", "Trusted Bisleri packaged drinking water — 10-step purification", "4", 20, 22, "1 L", 70),
  p("p358", "Kinley Soda", "किनले सोडा", "Classic Kinley club soda — for mixers and nimbu pani", "4", 30, 35, "750 ml", 60),
  p("p359", "Rooh Afza Sharbat 750ml", "रूह अफ़ज़ा शरबत", "Iconic rose sharbat — Eid-Ramzan classic and summer cooler", "4", 215, 240, "750 ml", 35),
  p("p645", "Pepsi Black Zero Sugar", "पेप्सी ब्लैक", "Bold cola taste with zero sugar — guilt-free fizzy refreshment", "4", 45, 50, "750 ml", 45),
  p("p646", "Mountain Dew Ice", "माउंटेन ड्यू आइस", "Citrus-charged dew with icy cool menthol kick — bold thrill drink", "4", 45, 50, "750 ml", 40),
  p("p647", "Coca-Cola Mini Can", "कोका-कोला मिनी कैन", "Iconic Coke fizz in handy mini can — perfect personal serving", "4", 25, 30, "250 ml", 60),
  p("p648", "Limca Mini Can", "लिम्का मिनी कैन", "Crisp lime-lemon fizz in slim mini can — refreshing on-the-go", "4", 25, 30, "250 ml", 55),
  p("p649", "Sprite Mini Can", "स्प्राइट मिनी कैन", "Clear lime-lemon refreshment in mini can — chilled and crisp", "4", 25, 30, "250 ml", 55),
  p("p650", "Thums Up Mini Can", "थम्स अप मिनी कैन", "Strong fizzy thunder cola in mini can — taste the thunder", "4", 25, 30, "250 ml", 55),
  p("p651", "Schweppes Tonic Water", "श्वेप्स टॉनिक वाटर", "Classic Indian tonic water with quinine — perfect gin mixer", "4", 75, 85, "250 ml", 35),
  p("p652", "Schweppes Bitter Lemon", "श्वेप्स बिटर लेमन", "Crisp citrus mixer with bitter zest — cocktail-grade soda", "4", 75, 85, "250 ml", 30),
  p("p653", "Real Pomegranate Juice", "रियल अनार जूस", "Dabur Real pomegranate juice — antioxidant-rich daily fruit dose", "4", 130, 145, "1 L", 30),
  p("p654", "Real Pineapple Juice", "रियल पाइनएप्पल जूस", "Dabur Real pineapple juice — tropical sweetness from real fruit", "4", 120, 135, "1 L", 30),
  p("p655", "Real Cranberry Juice", "रियल क्रैनबेरी जूस", "Dabur Real cranberry juice — tangy berry vitality drink", "4", 130, 145, "1 L", 25),
  p("p656", "Real Guava Juice", "रियल अमरूद जूस", "Dabur Real guava juice — desi fruit goodness packed with vitamin C", "4", 120, 135, "1 L", 30),
  p("p657", "Tropicana Apple Juice", "ट्रॉपिकाना सेब जूस", "100% apple juice — no added sugar, fortified with vitamins", "4", 130, 145, "1 L", 30),
  p("p658", "Tropicana Mango Delight", "ट्रॉपिकाना मैंगो", "Alphonso mango delight juice — sun-ripened taste in every sip", "4", 130, 145, "1 L", 35),
  p("p659", "Tropicana Pineapple Delight", "ट्रॉपिकाना पाइनएप्पल", "Tropicana pineapple juice — tangy-sweet tropical refreshment", "4", 130, 145, "1 L", 25),
  p("p660", "Storia Coconut Water", "स्टोरिया नारियल पानी", "100% pure tender coconut water — natural electrolyte hydration", "4", 65, 75, "200 ml", 45),
  p("p661", "Monster Energy Drink", "मॉन्स्टर एनर्जी", "Global energy drink with taurine and ginseng — green-can power", "4", 125, 135, "350 ml", 40),
  p("p662", "Tzinga Tropical Trip", "ज़िंगा एनर्जी", "Indian energy drink with caffeine and ginseng — value tropical kick", "4", 30, 35, "250 ml", 60),
  p("p663", "Red Bull Sugarfree", "रेड बुल शुगरफ्री", "Zero-sugar energy boost — wings without the calories", "4", 125, 135, "250 ml", 35),
  p("p664", "Amul Kool Kesar Pista", "अमूल कूल केसर पिस्ता", "Saffron-pistachio flavoured milk drink — chilled treat in tetra pack", "4", 30, 35, "200 ml", 60),
  p("p665", "Amul Kool Strawberry", "अमूल कूल स्ट्रॉबेरी", "Sweet strawberry-flavoured milk drink — kids' chilled favourite", "4", 30, 35, "200 ml", 55),
  p("p666", "Bisleri Mineral Water 500ml", "बिसलेरी 500 मिली", "Trusted Bisleri packaged drinking water — handy bottle for on-the-go", "4", 10, 10, "500 ml", 80),
  p("p667", "Bisleri Mineral Water 2L", "बिसलेरी 2 लीटर", "Bisleri family-pack drinking water — 10-step purification process", "4", 35, 40, "2 L", 50),
  p("p668", "Himalayan Mineral Water", "हिमालयन वाटर", "Natural mineral water from Himalayas — premium hydration", "4", 60, 65, "1 L", 30),
  p("p669", "Mother Dairy Spiced Buttermilk", "मदर डेयरी मसाला छाछ", "Chilled spiced chaas with curry leaves and cumin — gut-cooling drink", "4", 20, 22, "200 ml", 55),
];
