import type { Product } from "@/types";
import { p } from "./_helper";

/** Cleaning Essentials — 13 products. Loaded lazily by the catalogue hook. */
export const products: Product[] = [
  p("p125", "Vim Dishwash Bar", "विम बार", "Vim Lemon Dishwash Bar — tough on grease, gentle on hands", "17", 10, 10, "140 g", 60),
  p("p126", "Vim Dishwash Gel", "विम जेल", "Vim Lemon Dishwash Gel — fast grease cut, fresh lemon fragrance", "17", 99, 115, "500 ml", 25),
  p("p127", "Surf Excel Detergent", "सर्फ एक्सेल", "Surf Excel Easy Wash Detergent — removes tough stains in fewer mugs of water", "17", 120, 135, "1 kg", 20),
  p("p128", "Rin Detergent Bar", "रिन बार", "Rin Detergent Bar — bright whites with chamak, value-for-money", "17", 25, 28, "250 g", 40),
  p("p129", "Harpic Toilet Cleaner", "हार्पिक", "Harpic Power Plus Toilet Cleaner — 10X stronger, kills 99.9% germs", "17", 85, 95, "500 ml", 20),
  p("p130", "Lizol Floor Cleaner", "लाइज़ॉल", "Lizol Citrus Floor Cleaner — disinfects floor, kills 1000 germs", "17", 115, 130, "500 ml", 18),
  p("p131", "Colin Glass Cleaner", "कॉलिन", "Colin Glass & Surface Cleaner — streak-free shine in seconds", "17", 85, 95, "500 ml", 15),
  p("p132", "Scotch-Brite Scrub Pad", "स्कॉच-ब्राइट", "Scotch-Brite Heavy Duty Scrub Pad — tough scrub power for stuck-on grime", "17", 30, 32, "1 pc", 40),
  p("p133", "Odonil Air Freshener", "ओडोनिल", "Odonil Room Freshener Block — long-lasting fragrance for bathrooms and rooms", "17", 45, 52, "75 g", 25),
  p("p134", "Good Knight Liquid Refill", "गुडनाइट", "Good Knight Liquid Refill — 45-night protection from mosquitoes", "17", 68, 75, "45 ml", 30),
  p("p135", "Hit Spray", "हिट स्प्रे", "Hit Cockroach & Ant Killer Spray — instant kill, deep reach formula", "17", 155, 175, "200 ml", 15),
  p("p136", "Garbage Bags (Black)", "कचरा बैग", "Heavy-duty black garbage bags — leak-proof, large capacity for kitchen waste", "17", 60, 70, "30 pcs", 25),
  p("p137", "Prill Dishwash Liquid", "प्रिल डिशवॉश", "Prill Dishwash Liquid — sparkling clean utensils with fresh lime fragrance", "17", 55, 62, "250 ml", 20),
  p("p895", "Surf Excel Matic Top Load", "सर्फ एक्सेल मैटिक टॉप लोड", "Surf Excel Matic Top Load detergent powder — engineered for top-load washing machines", "17", 245, 285, "1 kg", 30),
  p("p896", "Surf Excel Matic Front Load 1.5kg", "सर्फ एक्सेल मैटिक फ्रंट लोड", "Surf Excel Matic Front Load detergent — low foam formula for front-load machines", "17", 385, 435, "1.5 kg", 25),
  p("p897", "Surf Excel Quick Wash 1kg", "सर्फ एक्सेल क्विक वॉश", "Surf Excel Quick Wash detergent powder — removes tough stains in fewer mugs of water", "17", 175, 200, "1 kg", 28),
  p("p898", "Ariel Matic Top Load", "एरियल मैटिक टॉप लोड", "Ariel Matic Top Load detergent powder — tough stain removal in just one wash", "17", 260, 295, "1 kg", 30),
  p("p899", "Ariel Matic Front Load", "एरियल मैटिक फ्रंट लोड", "Ariel Matic Front Load detergent powder — low-foam, deep cleaning for front load", "17", 275, 310, "1 kg", 25),
  p("p900", "Tide Plus Double Power 1kg", "टाइड प्लस डबल पावर", "Tide Plus Double Power detergent — extra mile shine with jasmine and rose fragrance", "17", 145, 165, "1 kg", 35),
  p("p901", "Tide Plus Lemon 1kg", "टाइड प्लस लेमन", "Tide Plus Lemon and Mint detergent powder — extra fresh tough stain removal", "17", 140, 160, "1 kg", 30),
  p("p902", "Henko Stain Champion", "हेंको स्टेन चैंपियन", "Henko Stain Champion detergent — Japanese SBS technology for tough stain removal", "17", 215, 240, "1 kg", 22),
  p("p903", "Patanjali Detergent Powder", "पतंजलि डिटर्जेंट पाउडर", "Patanjali Superior Detergent Powder — herbal formula, ayurvedic clean", "17", 95, 110, "1 kg", 30),
  p("p904", "Rin Advanced 1kg", "रिन एडवांस्ड", "Rin Advanced detergent powder — brilliant whites and bright colours, chamak", "17", 105, 120, "1 kg", 35),
  p("p905", "Rin Refresh Lemon Bar 5x", "रिन रिफ्रेश लेमन बार", "Rin Refresh Lemon Detergent Bar — 5 pack pouch, lemon-fresh brilliant whites", "17", 105, 125, "5 x 250 g", 30),
  p("p906", "Wheel Active 2 Lemon 1kg", "व्हील एक्टिव 2 लेमन", "Wheel Active 2 Lemon and Jasmine detergent — value powder for everyday wash", "17", 65, 75, "1 kg", 40),
  p("p907", "Genteel Liquid Detergent", "जेंटल लिक्विड डिटर्जेंट", "Genteel Liquid Detergent — gentle on delicate fabrics, premium silk and woollens", "17", 235, 265, "1 L", 20),
  p("p908", "Ezee Liquid Detergent", "ईज़ी लिक्विड डिटर्जेंट", "Ezee Liquid Detergent for woollens and delicates — cold-water wash, no soaking", "17", 220, 250, "1 L", 22),
  p("p909", "Comfort Fabric Conditioner", "कम्फर्ट फैब्रिक कंडीशनर", "Comfort After Wash Fabric Conditioner Morning Fresh — long-lasting fragrance", "17", 220, 245, "860 ml", 25),
  p("p910", "Vanish Stain Remover", "वैनिश स्टेन रिमूवर", "Vanish Oxi Action Stain Remover Powder — removes 100 tough stains, colour safe", "17", 275, 310, "400 g", 20),
  p("p911", "Vim Power Liquid 1L Refill", "विम पावर लिक्विड रिफिल", "Vim Power Anti-Smell Dishwash Liquid refill pouch — cuts grease, fresh lemon", "17", 175, 195, "1 L", 30),
  p("p912", "Pril Lemon Liquid", "प्रिल लेमन लिक्विड", "Pril Concentrated Dishwash Liquid Lemon — fast grease cut, gentle on hands", "17", 195, 220, "750 ml", 25),
  p("p913", "Exo Round Bar", "एक्सो राउंड बार", "Exo Cyclozan Round Anti-Bacterial Dishwash Bar — kills 99.9% germs, sparkle clean", "17", 18, 22, "300 g", 50),
  p("p914", "Patanjali Super Dish Wash Bar", "पतंजलि सुपर डिश वॉश बार", "Patanjali Super Dish Wash Bar — herbal grease-cutting power, value pack", "17", 25, 30, "280 g", 45),
  p("p915", "Sufyaan Soak Dish Handwash", "सुफियान डिश हैंडवॉश", "Sufyaan Soak Handwash for dishes — gentle on hands while tough on grease", "17", 95, 110, "500 ml", 20),
  p("p916", "Ezee Dishwash", "ईज़ी डिशवॉश", "Ezee Dishwash Liquid — quick rinse formula, premium kitchen cleaning", "17", 110, 125, "500 ml", 18),
  p("p917", "Quick Bath Dish Wash Liquid", "क्विक बाथ डिशवॉश", "Quick Bath Dishwash Liquid — economical large pack, fresh lemon scent", "17", 145, 165, "1 L", 22),
  p("p918", "Finish Dishwasher Tablets", "फिनिश डिशवॉशर टैबलेट्स", "Finish Quantum Dishwasher Tablets — premium dishwashing machine tablets, 30 pcs", "17", 765, 850, "30 tablets", 15),
  p("p919", "Lemonex Dishwash Bar", "लेमोनेक्स डिशवॉश बार", "Lemonex Dishwash Bar — lemon-fresh utensil cleaner, value 5-pack", "17", 50, 60, "5 x 200 g", 30),
  p("p920", "Domex Toilet Cleaner", "डोमेक्स टॉयलेट क्लीनर", "Domex Disinfectant Toilet Cleaner — kills 100 illness-causing germs, ocean fresh", "17", 99, 115, "500 ml", 25),
  p("p921", "Harpic Bathroom Cleaner", "हार्पिक बाथरूम क्लीनर", "Harpic Bathroom Cleaner Floral — removes soap scum and hard water stains", "17", 165, 185, "500 ml", 22),
  p("p922", "Cif Bathroom Cleaner", "सिफ बाथरूम क्लीनर", "Cif Bathroom Cleaner Spray — power scrub removes stubborn dirt and limescale", "17", 195, 220, "500 ml", 20),
  p("p923", "Patanjali Toilet Cleaner", "पतंजलि टॉयलेट क्लीनर", "Patanjali Herbal Toilet Cleaner — natural ingredients, deep clean and germ kill", "17", 85, 95, "500 ml", 25),
  p("p924", "Pril Toilet Cleaner Power", "प्रिल टॉयलेट क्लीनर", "Pril Toilet Cleaner Power — disinfects and shines, removes tough stains", "17", 95, 110, "500 ml", 20),
  p("p925", "Mr. Muscle Bathroom", "मि मसल बाथरूम क्लीनर", "Mr. Muscle Bathroom Cleaner — power formula removes soap scum and hard water stains", "17", 185, 210, "500 ml", 18),
  p("p926", "Limescale Remover", "लाइमस्केल रिमूवर", "Premium limescale remover — dissolves hard water deposits and mineral buildup", "17", 175, 195, "500 ml", 15),
  p("p927", "Toilet Disinfectant Spray", "टॉयलेट डिसइंफेक्टेंट स्प्रे", "Lizol Toilet Disinfectant Spray — kills 99.9% germs, fresh fragrance", "17", 235, 260, "200 ml", 18),
  p("p928", "Domex Floor Cleaner", "डोमेक्स फ्लोर क्लीनर", "Domex Disinfectant Floor Cleaner — kills 100 illness-causing germs, fresh fragrance", "17", 115, 130, "500 ml", 22),
  p("p929", "Mr. Muscle Floor Cleaner", "मि मसल फ्लोर क्लीनर", "Mr. Muscle Floor Cleaner — pH neutral formula, safe for marble and tile floors", "17", 165, 185, "500 ml", 20),
  p("p930", "Patanjali Floor Cleaner", "पतंजलि फ्लोर क्लीनर", "Patanjali Herbal Floor Cleaner — neem and tulsi, natural antibacterial action", "17", 95, 110, "1 L", 25),
  p("p931", "Lizol Lavender", "लाइज़ॉल लैवेंडर", "Lizol Lavender Disinfectant Floor Cleaner — kills 1000 germs, calming fragrance", "17", 215, 240, "975 ml", 20),
  p("p932", "Lizol Pine", "लाइज़ॉल पाइन", "Lizol Pine Disinfectant Floor Cleaner — fresh forest scent, kills 1000 germs", "17", 215, 240, "975 ml", 20),
  p("p933", "Tile Cleaner", "टाइल क्लीनर", "Premium Tile Cleaner — removes tough stains and grout buildup, all-tile safe", "17", 175, 195, "500 ml", 18),
  p("p934", "Mr. Muscle Glass Cleaner", "मि मसल ग्लास क्लीनर", "Mr. Muscle Glass Cleaner — streak-free shine, ammonia-based formula", "17", 175, 195, "500 ml", 18),
  p("p935", "Colin Glass Lemon", "कॉलिन ग्लास लेमन", "Colin Glass and Surface Cleaner Lemon — streak-free shine, refreshing scent", "17", 95, 110, "500 ml", 22),
  p("p936", "Mr. Muscle Kitchen Cleaner", "मि मसल किचन क्लीनर", "Mr. Muscle Kitchen Cleaner — degreaser spray for hobs, chimneys and counters", "17", 185, 210, "500 ml", 20),
  p("p937", "Jeyes Cleaner", "जेज़ क्लीनर", "Jeyes All-Purpose Disinfectant Cleaner — deep clean kitchens, bathrooms and floors", "17", 215, 240, "500 ml", 15),
  p("p938", "All-Purpose Spray Cleaner", "ऑल पर्पस क्लीनर", "Multi-Surface All-Purpose Spray Cleaner — works on glass, wood, plastic, marble", "17", 155, 175, "500 ml", 20),
  p("p939", "Drainex Drain Cleaner", "ड्रेनेक्स ड्रेन क्लीनर", "Drainex Drain Cleaner Powder — unclogs sinks and drains in 60 seconds", "17", 95, 110, "100 g", 25),
  p("p940", "Suction Plunger", "सक्शन प्लंजर", "Heavy-duty rubber suction plunger — for clogged sinks and toilets", "17", 165, 195, "1 pc", 15),
  p("p941", "Garbage Bags Medium 60pc", "गार्बेज बैग मीडियम", "Medium garbage bags — leak-proof, 60-piece value pack for kitchen waste", "17", 175, 200, "60 pcs", 25),
  p("p942", "Garbage Bags Small 90pc", "गार्बेज बैग स्मॉल", "Small garbage bags — perfect for bedroom and bathroom bins, 90 pieces", "17", 195, 225, "90 pcs", 25),
  p("p943", "Garbo Bin Bags Big", "गार्बो बिन बैग बिग", "Garbo Large Garbage Bin Bags — heavy-duty, leak-proof, 30 pieces", "17", 155, 175, "30 pcs", 20),
  p("p944", "Disposable Gloves", "डिस्पोजेबल ग्लव्स", "Disposable Latex-Free Gloves — for cleaning and food handling, 50 pieces", "17", 145, 165, "50 pcs", 25),
  p("p945", "Air Wick Refill", "एयर विक रिफिल", "Air Wick Aroma Diffuser Refill — long-lasting fresh fragrance, 60 days", "17", 245, 275, "19 ml", 18),
  p("p946", "Godrej Aer Lemongrass", "गोदरेज एयर लेमनग्रास", "Godrej Aer Spray Lemongrass — instant freshness for living rooms and bedrooms", "17", 185, 210, "240 ml", 20),
  p("p947", "Godrej Aer Coffee Walnut", "गोदरेज एयर कॉफी वॉलनट", "Godrej Aer Spray Coffee Walnut — rich aromatic blend for home freshness", "17", 185, 210, "240 ml", 20),
  p("p948", "Godrej Aer Twist", "गोदरेज एयर ट्विस्ट", "Godrej Aer Twist Air Freshener Cool Surf Blue — gel-based, 45 days fragrance", "17", 95, 110, "45 g", 25),
  p("p949", "Odonil Pure Spice", "ओडोनिल प्योर स्पाइस", "Odonil Pure and Spice Room Air Freshener Block — long-lasting spice fragrance", "17", 55, 65, "75 g", 30),
  p("p950", "Ambi Pur Plug-in Refill", "एम्बी प्योर प्लग इन रिफिल", "Ambi Pur Plug-in Refill — 70 days continuous fragrance, lavender", "17", 235, 265, "20 ml", 18),
  p("p951", "Good Knight All-Out Machine", "गुडनाइट ऑल आउट मशीन", "Good Knight All Out Liquid Vaporiser Machine with Refill — 100% mosquito kill", "17", 145, 165, "Machine + Refill", 25),
  p("p952", "Good Knight Naturals Refill", "गुडनाइट नेचुरल्स रिफिल", "Good Knight Naturals Mosquito Refill — neem-based, safe for kids and pregnancy", "17", 85, 95, "45 ml", 30),
  p("p953", "Hit Anti Mosquito Spray", "हिट एंटी मच्छर स्प्रे", "Hit Anti Mosquito Flying Insect Killer Spray — instant kill, fresh fragrance", "17", 235, 265, "400 ml", 18),
  p("p954", "Hit Anti Roach Gel", "हिट एंटी रोच जेल", "Hit Anti Roach Cockroach Killer Gel — odourless, deep crack penetration", "17", 175, 195, "20 g", 22),
  p("p955", "Hit Lizard Killer", "हिट लिज़ार्ड किलर", "Hit Lizard Repellent Spray — keeps lizards away from kitchen and walls", "17", 185, 210, "200 ml", 20),
  p("p956", "Mortein Liquid Vaporiser", "मॉर्टीन लिक्विड वेपोराइज़र", "Mortein Power Booster Liquid Vaporiser — 60 nights mosquito protection", "17", 95, 110, "45 ml", 30),
  p("p957", "Mortein Roach Killer", "मॉर्टीन रोच किलर", "Mortein Power Gard Cockroach Killer Spray — kills hidden cockroaches", "17", 245, 275, "425 ml", 18),
  p("p958", "Termite Spray", "टर्माइट स्प्रे", "Anti-Termite Spray — preventive treatment for wood, walls and books", "17", 285, 320, "500 ml", 12),
  p("p959", "Lakshman Rekha Cockroach Chalk", "लक्ष्मण रेखा चॉक", "Lakshman Rekha Anti-Cockroach Chalk — effective barrier against ants and roaches", "17", 30, 35, "2 pcs", 50),
  p("p960", "Pee Safe Roach Killer", "पी सेफ रोच किलर", "Pee Safe Cockroach Killer Spray — herbal formula, child and pet safe", "17", 225, 250, "350 ml", 18),
  p("p961", "Spotzero Mop", "स्पॉटज़ीरो मॉप", "Spotzero by Milton Spin Mop with Bucket — 360 degree spin, easy wring", "17", 1495, 1750, "1 set", 10),
  p("p962", "Gala Spin Mop", "गाला स्पिन मॉप", "Gala Spin Mop with Bucket Set — superior absorption, microfiber refill", "17", 1195, 1395, "1 set", 12),
  p("p963", "Microfiber Cloth 3pc", "माइक्रोफाइबर क्लॉथ", "Microfiber Cleaning Cloth — lint-free, super absorbent, 3-piece pack", "17", 165, 195, "3 pcs", 25),
  p("p964", "Floor Wiper", "फ्लोर वाइपर", "Heavy-duty rubber Floor Wiper — long handle, perfect for bathroom and floor", "17", 245, 285, "1 pc", 20),
];
