import type { Product } from "@/types";
import { p } from "./_helper";

/** Pharma & Wellness — 22 products. Loaded lazily by the catalogue hook. */
export const products: Product[] = [
  p("p122", "Vicks VapoRub", "विक्स वेपोरब", "Vicks VapoRub — soothing balm for cold, cough, and blocked nose", "16", 72, 80, "25 ml", 20),
  p("p123", "Band-Aid (Johnson's)", "बैंड-एड", "Johnson's Band-Aid Bandages — quick-stick wound care for minor cuts", "16", 40, 45, "10 pcs", 30),
  p("p268", "Crocin 650 Advance", "क्रोसिन 650 एडवांस", "Paracetamol 650mg for fast fever and pain relief — GSK trusted strip", "16", 42, 48, "15 tabs", 50),
  p("p269", "Dolo 650", "डोलो 650", "Paracetamol 650mg tablet for fever and body pain — doctor-preferred brand", "16", 32, 38, "15 tabs", 60),
  p("p270", "Saridon Headache Relief", "सैरिडॉन सिरदर्द", "Triple-action headache relief tablet — works in 30 minutes", "16", 50, 55, "10 tabs", 50),
  p("p271", "Eno Lemon Fruit Salt", "ईनो लेमन", "Instant antacid fruit salt sachets for acidity and gas relief — 6 sachets", "16", 48, 55, "6 sachets", 50),
  p("p272", "Digene Mint Gel", "डाइजीन मिंट जेल", "Cooling mint antacid gel for acidity, gas and heartburn — Abbott", "16", 165, 180, "200 ml", 35),
  p("p273", "Dabur Pudin Hara Pearls", "डाबर पुदीन हरा", "Peppermint oil pearls for instant relief from gas, acidity and indigestion", "16", 63, 70, "10 capsules", 45),
  p("p274", "Volini Pain Relief Spray", "वोलिनी स्प्रे", "Diclofenac spray for muscle and joint pain — sports-quick action relief", "16", 320, 355, "60 g", 30),
  p("p275", "Moov Pain Relief Cream", "मूव क्रीम", "Ayurvedic pain relief cream for back, neck and muscle pain — deep heal", "16", 145, 160, "50 g", 35),
  p("p276", "Disprin Regular", "डिस्प्रिन", "Aspirin-paracetamol dispersible tablets for quick headache relief", "16", 22, 25, "10 tabs", 50),
  p("p277", "Strepsils Original", "स्ट्रेप्सिल्स", "Medicated throat lozenges for sore throat and cough relief — classic flavour", "16", 65, 75, "8 lozenges", 45),
  p("p278", "Hansaplast Crepe Bandage", "हंसप्लास्ट क्रेप बैंडेज", "Stretchable elastic crepe bandage for sprains and sports injuries — 6cm", "16", 175, 195, "1 pc", 30),
  p("p279", "Savlon Antiseptic Liquid", "सेवलॉन एंटीसेप्टिक", "Trusted antiseptic disinfectant liquid for wounds, cuts and bathing", "16", 145, 165, "500 ml", 40),
  p("p280", "Iodex Pain Balm", "आयोडेक्स बाम", "Strong-smelling rub-on balm for muscle pain and body ache — GSK classic", "16", 99, 110, "40 g", 35),
  p("p281", "Electral ORS Orange", "इलेक्ट्रल ORS", "WHO-formula oral rehydration salts for dehydration and diarrhoea — FDC", "16", 22, 25, "21.8 g", 50),
  p("p282", "Himalaya Liv.52 DS", "हिमालय लिव 52 DS", "Ayurvedic liver tonic tablets for healthy liver function — double strength", "16", 155, 170, "60 tabs", 30),
  p("p283", "Combiflam", "कॉम्बिफ्लाम", "Ibuprofen + paracetamol for body pain, inflammation and fever relief", "16", 38, 44, "20 tabs", 45),
  p("p284", "Dabur Chyawanprash", "डाबर च्यवनप्राश", "Ayurvedic immunity-booster with 40+ herbs — daily wellness for whole family", "16", 285, 320, "1 kg", 35),
  p("p285", "Dabur Honitus Cough Syrup", "डाबर हनिटस सिरप", "Ayurvedic non-drowsy cough syrup with tulsi and honey — dry and wet cough", "16", 110, 125, "100 ml", 40),
  p("p286", "Becosules Capsules", "बेकोसूल्स कैप्सूल", "Vitamin B-complex with vitamin C capsules — daily energy and immunity", "16", 45, 52, "20 capsules", 40),
  p("p287", "Revital H Multivitamin", "रिवाइटल H", "Daily multivitamin and ginseng capsules for energy, stamina and immunity", "16", 285, 315, "30 capsules", 30),
  p("p965", "Sinarest Tablet", "साइनारेस्ट टैबलेट", "Sinarest tablets for cold, runny nose, sinusitis and allergic rhinitis relief", "16", 95, 110, "10 tabs", 40),
  p("p966", "Allegra 120mg", "एलेग्रा 120mg", "Allegra 120mg antihistamine tablets for hay fever and allergy relief", "16", 175, 195, "10 tabs", 35),
  p("p967", "Cetirizine 10mg", "सेट्रिज़ीन 10mg", "Cetirizine 10mg tablets for allergic rhinitis, urticaria and skin allergies", "16", 22, 28, "10 tabs", 50),
  p("p968", "Avil 50mg", "एविल 50mg", "Avil 50mg tablets — antihistamine for severe allergic reactions and itching", "16", 25, 30, "10 tabs", 45),
  p("p969", "Sumo Tablet", "सूमो टैबलेट", "Sumo tablets — nimesulide-paracetamol combo for body pain and inflammation", "16", 38, 45, "10 tabs", 40),
  p("p970", "Pudin Hara Liquid", "पुदीन हरा लिक्विड", "Dabur Pudin Hara Liquid — instant relief from indigestion, gas and stomach ache", "16", 75, 85, "30 ml", 35),
  p("p971", "Gelusil MPS", "जेलूसिल MPS", "Gelusil MPS antacid suspension — fast relief from acidity and heartburn, mint", "16", 165, 185, "200 ml", 30),
  p("p972", "ENO Strawberry", "ईनो स्ट्रॉबेरी", "ENO Strawberry Fruit Salt Sachets — fast antacid for acidity, 6 sachets", "16", 48, 55, "6 sachets", 45),
  p("p973", "ENO Apple Sachets", "ईनो एप्पल", "ENO Apple Fruit Salt Sachets — instant gas and acidity relief, 6 sachets", "16", 48, 55, "6 sachets", 45),
  p("p974", "Combiflam Plus", "कॉम्बिफ्लाम प्लस", "Combiflam Plus tablets — paracetamol ibuprofen for severe pain and inflammation", "16", 55, 65, "10 tabs", 40),
  p("p975", "Brufen 400mg", "ब्रूफेन 400mg", "Brufen 400mg ibuprofen tablets — pain relief for headaches, joint and dental pain", "16", 45, 52, "15 tabs", 40),
  p("p976", "Voveran SR", "वोवेरान SR", "Voveran SR diclofenac tablets — sustained release relief from arthritis pain", "16", 95, 110, "10 tabs", 30),
  p("p977", "Iodex Ultra Gel", "आयोडेक्स अल्ट्रा जेल", "Iodex Ultra Gel — fast-absorbing pain relief gel for muscle and joint pain", "16", 165, 185, "50 g", 30),
  p("p978", "Tiger Balm", "टाइगर बाम", "Tiger Balm Red — Singapore-original analgesic balm for headache and muscle pain", "16", 145, 165, "21 ml", 30),
  p("p979", "Zandu Balm", "ज़ंडू बाम", "Zandu Balm — ayurvedic pain relief balm for headache, body ache and cold", "16", 75, 85, "25 ml", 40),
  p("p980", "Amrutanjan Balm", "अमृतांजन बाम", "Amrutanjan Pain Balm — relieves headache, cold and muscular pain, classic balm", "16", 65, 75, "30 ml", 35),
  p("p981", "Vicks Inhaler", "विक्स इनहेलर", "Vicks Inhaler — pocket-sized nasal decongestant for cold and stuffy nose", "16", 65, 75, "1 pc", 45),
  p("p982", "Vicks Cough Drops", "विक्स कफ ड्रॉप्स", "Vicks Cough Drops Ginger Mint — soothes sore throat and cough, 20 drops", "16", 35, 40, "20 drops", 50),
  p("p983", "Halls Strawberry", "हॉल्स स्ट्रॉबेरी", "Halls Strawberry Cough Drops — soothing throat lozenges, 10-piece stick pack", "16", 18, 22, "10 drops", 50),
  p("p984", "Halls Mint", "हॉल्स मिंट", "Halls Extra Strong Mint Cough Drops — powerful menthol throat relief, 10 drops", "16", 18, 22, "10 drops", 50),
  p("p985", "Strepsils Honey Lemon", "स्ट्रेप्सिल्स हनी लेमन", "Strepsils Honey and Lemon lozenges — soothing throat relief, 8 lozenges", "16", 65, 75, "8 lozenges", 40),
  p("p986", "Otrivin Nasal Spray", "ओट्रिविन नाक स्प्रे", "Otrivin Adult Nasal Spray — fast relief from blocked nose, 10 ml bottle", "16", 165, 185, "10 ml", 30),
  p("p987", "Otrivin Saline Drops", "ओट्रिविन सेलाइन ड्रॉप्स", "Otrivin Saline Nasal Drops — gentle for daily nasal hygiene, infant safe", "16", 95, 110, "15 ml", 35),
  p("p988", "Murine Eye Drops", "मूरीन आई ड्रॉप्स", "Murine Eye Drops — relieves dry, tired and irritated eyes, lubricating formula", "16", 95, 110, "10 ml", 30),
  p("p989", "Refresh Tears", "रिफ्रेश टीयर्स", "Refresh Tears Lubricant Eye Drops — for dry eye and computer vision syndrome", "16", 145, 165, "10 ml", 25),
  p("p990", "Betadine Antiseptic", "बीटाडीन एंटीसेप्टिक", "Betadine Povidone Iodine Antiseptic Solution — wound cleaning, 100 ml bottle", "16", 95, 110, "100 ml", 35),
  p("p991", "Hansaplast Wet Wipes", "हंसप्लास्ट वेट वाइप्स", "Hansaplast Antibacterial Wet Wipes — cleans wounds before first aid, 20 wipes", "16", 95, 110, "20 wipes", 30),
  p("p992", "Hansaplast First Aid Spray", "हंसप्लास्ट फर्स्ट एड स्प्रे", "Hansaplast First Aid Spray — antiseptic spray for cuts and wounds, painless", "16", 215, 240, "50 ml", 25),
  p("p993", "Anchor Mouth Care", "एंकर माउथ केयर", "Anchor Mouth Care Mouthwash — fresh breath all day, kills 99.9% germs", "16", 115, 135, "250 ml", 30),
  p("p994", "Liv 52 Drops", "लिव 52 ड्रॉप्स", "Himalaya Liv 52 Drops paediatric — ayurvedic liver tonic for children", "16", 95, 110, "60 ml", 35),
  p("p995", "Glucon-D Tangy Orange", "ग्लूकॉन डी टैंगी ऑरेंज", "Glucon-D Tangy Orange — instant glucose energy drink mix, refreshing taste", "16", 145, 165, "450 g", 30),
  p("p996", "Sugar Free Gold", "शुगर फ्री गोल्ड", "Sugar Free Gold Aspartame Tablets — diabetic-friendly sweetener, 300 tablets", "16", 165, 185, "300 tabs", 25),
  p("p997", "Stevia Sweetener Sachets", "स्टीविया स्वीटनर", "Stevia Natural Sweetener Sachets — zero calorie plant-based sweetener, 50 sachets", "16", 245, 275, "50 sachets", 20),
  p("p998", "Patanjali Aloe Vera Juice", "पतंजलि एलोवेरा जूस", "Patanjali Aloe Vera Juice — ayurvedic immunity and digestion booster", "16", 175, 195, "1 L", 25),
  p("p999", "Patanjali Amla Juice", "पतंजलि आंवला जूस", "Patanjali Amla Juice — rich source of vitamin C, hair and skin wellness", "16", 165, 185, "1 L", 25),
  p("p1000", "Patanjali Karela Juice", "पतंजलि करेला जूस", "Patanjali Karela Juice — natural blood sugar control, diabetic wellness", "16", 165, 185, "1 L", 22),
  p("p1001", "Himalaya Cystone", "हिमालय सिस्टोन", "Himalaya Cystone tablets — ayurvedic for kidney stones and UTI support", "16", 195, 220, "100 tabs", 28),
  p("p1002", "Himalaya Septilin", "हिमालय सेप्टिलिन", "Himalaya Septilin tablets — ayurvedic immunity booster, 60 tablets", "16", 175, 195, "60 tabs", 30),
  p("p1003", "Patanjali Triphala Churna", "पतंजलि त्रिफला चूर्ण", "Patanjali Divya Triphala Churna — classic ayurvedic digestion and detox powder", "16", 95, 110, "100 g", 30),
  p("p1004", "Patanjali Madhunashini Vati", "पतंजलि मधुनाशिनी वटी", "Patanjali Divya Madhunashini Vati — ayurvedic blood sugar management tablets", "16", 295, 330, "120 tabs", 22),
];
