import type { Product } from "@/types";
import { p } from "./_helper";

/** Sweet Tooth — 19 products. Loaded lazily by the catalogue hook. */
export const products: Product[] = [
  p("p80", "Cadbury Dairy Milk", "कैडबरी डेयरी मिल्क", "Cadbury Dairy Milk — smooth creamy milk chocolate, India's #1 chocolate bar", "7", 40, 45, "50 g", 50),
  p("p81", "5 Star Chocolate", "5 स्टार चॉकलेट", "Cadbury 5 Star — chewy caramel chocolate bar, India's iconic treat", "7", 20, 25, "40 g", 55),
  p("p82", "KitKat", "किटकैट", "Nestlé KitKat — crisp chocolate wafer fingers, have a break, have a KitKat", "7", 30, 35, "37.3 g", 45),
  p("p220", "Haldiram's Rasgulla Tin", "हलदीराम रसगुल्ला", "Soft spongy bengali rasgulla in sugar syrup — easy-open tin, festive favourite", "7", 230, 270, "1 kg", 30),
  p("p221", "Haldiram's Soan Papdi", "हलदीराम सोन पापड़ी", "Flaky desi ghee soan papdi — classic Indian mithai for gifting and tea-time", "7", 215, 260, "500 g", 35),
  p("p222", "Haldiram's Gulab Jamun Tin", "हलदीराम गुलाब जामुन", "Soft khoya gulab jamun in cardamom sugar syrup — ready-to-serve tin", "7", 240, 280, "1 kg", 30),
  p("p223", "Bikaji Kaju Katli", "बीकाजी काजू कतली", "Premium cashew fudge with silver vark — melts-in-mouth festive mithai", "7", 320, 380, "250 g", 25),
  p("p224", "Cadbury Dairy Milk Silk", "कैडबरी डेयरी मिल्क सिल्क", "Smooth creamy milk chocolate bar — signature melt-in-mouth indulgence", "7", 102, 115, "60 g", 50),
  p("p225", "Cadbury Bournville Rich Cocoa", "कैडबरी बोर्नविले", "70% dark chocolate with deep cocoa notes — premium adult indulgence", "7", 135, 150, "80 g", 40),
  p("p226", "Cadbury Gems", "कैडबरी जेम्स", "Colourful candy-coated milk chocolate buttons — loved by kids", "7", 20, 25, "16.5 g", 60),
  p("p227", "Cadbury Eclairs Party Pack", "कैडबरी एक्लेयर्स", "Chewy caramel toffee with rich Cadbury chocolate centre — party pack", "7", 80, 100, "63 pcs", 45),
  p("p228", "Hershey's Kisses Milk Chocolate", "हर्शीज़ किसेस", "Iconic foil-wrapped American milk chocolate drops — sharing pouch", "7", 199, 225, "100 g", 30),
  p("p229", "Ferrero Rocher (4 pcs)", "फेरेरो रोशे", "Premium hazelnut chocolate praline with crispy wafer and golden foil", "7", 169, 185, "50 g", 40),
  p("p230", "Amul Milk Chocolate Bar", "अमूल मिल्क चॉकलेट", "Classic Amul fresh milk chocolate bar — smooth and creamy at value price", "7", 80, 90, "150 g", 45),
  p("p231", "Nestle Munch", "नेस्ले मंच", "Crunchy wafer with chocolate coating — the original crunchilicious bar", "7", 10, 10, "18.7 g", 60),
  p("p232", "Cadbury Perk", "कैडबरी पर्क", "Light crispy wafer chocolate bar — for everyday chhota-bada bhook", "7", 10, 10, "13.2 g", 60),
  p("p233", "Pulse Candy Mango Jar", "पल्स कैंडी मैंगो", "Tangy mango candy with kachcha aam masala centre — India's iconic hard candy", "7", 50, 50, "100 pcs", 50),
  p("p234", "Mentos Mint Roll", "मेंटोस मिंट", "Chewy mint dragees in classic roll pack — fresh breath on the go", "7", 25, 25, "37 g", 50),
  p("p235", "Lotte Choco Pie", "लोट्टे चोको पाई", "Soft marshmallow sandwich biscuit coated in chocolate — family pack 6 pcs", "7", 95, 110, "168 g", 40),
  p("p580", "Cadbury Dairy Milk Crackle", "कैडबरी डेयरी मिल्क क्रैकल", "Smooth milk chocolate loaded with crunchy caramelised rice crispies", "7", 85, 95, "80 g", 45),
  p("p581", "Cadbury Dairy Milk Roast Almond", "कैडबरी डेयरी मिल्क रोस्ट आल्मंड", "Creamy milk chocolate with crunchy whole roasted almonds in every bite", "7", 95, 105, "80 g", 40),
  p("p582", "Cadbury Dairy Milk Fruit & Nut", "कैडबरी डेयरी मिल्क फ्रूट एंड नट", "Classic milk chocolate with juicy raisins and California almonds", "7", 95, 110, "80 g", 40),
  p("p583", "Cadbury Dairy Milk Silk Oreo", "कैडबरी सिल्क ओरियो", "Silky-smooth chocolate with crunchy Oreo cookie chunks — premium indulgence", "7", 145, 165, "130 g", 35),
  p("p584", "Cadbury Dairy Milk Silk Hazelnut", "कैडबरी सिल्क हेज़लनट", "Silk chocolate with crunchy hazelnut bits — luxurious melt-in-mouth treat", "7", 175, 200, "143 g", 30),
  p("p585", "Cadbury Dairy Milk Silk Mousse", "कैडबरी सिल्क मूस", "Silk chocolate with airy mousse centre — pillowy soft cocoa indulgence", "7", 80, 90, "50 g", 40),
  p("p586", "Cadbury Bournville Cranberry", "कैडबरी बोर्नविले क्रैनबेरी", "70% dark chocolate with tangy dried cranberries — premium adult treat", "7", 135, 150, "80 g", 30),
  p("p587", "Cadbury Bournville Raisin & Nut", "कैडबरी बोर्नविले रेज़िन एंड नट", "Rich dark chocolate with plump raisins and crunchy almonds", "7", 135, 150, "80 g", 30),
  p("p588", "Hershey's Cookies n Creme", "हर्शीज़ कुकीज़ एन क्रीम", "Sweet white creme chocolate with crunchy cocoa cookie bits — iconic American bar", "7", 175, 195, "100 g", 30),
  p("p589", "Hershey's Milk Chocolate Bar", "हर्शीज़ मिल्क चॉकलेट बार", "Classic American milk chocolate bar — smooth, creamy and rich", "7", 165, 185, "100 g", 30),
  p("p590", "Haldiram's Kaju Katli", "हलदीराम काजू कतली", "Diamond-cut cashew fudge with silver vark — premium festive mithai", "7", 350, 395, "250 g", 25),
  p("p591", "Bikaji Soan Papdi", "बीकाजी सोन पापड़ी", "Flaky desi ghee soan papdi with cardamom and pistachio — gift pack", "7", 195, 230, "500 g", 30),
  p("p592", "Bikaji Rasgulla", "बीकाजी रसगुल्ला", "Spongy chenna rasgulla in cardamom sugar syrup — ready-to-serve tin", "7", 210, 250, "1 kg", 25),
  p("p593", "Bikaji Gulab Jamun", "बीकाजी गुलाब जामुन", "Soft khoya gulab jamun in saffron syrup — Rajasthani sweet shop classic", "7", 225, 265, "1 kg", 25),
  p("p594", "Bikaji Cham Cham", "बीकाजी चम चम", "Soft Bengali cham cham soaked in sugar syrup — authentic mishti", "7", 245, 285, "1 kg", 20),
  p("p595", "Haldiram's Mysore Pak", "हलदीराम मैसूर पाक", "Ghee-laden gram flour fudge — South Indian festive specialty", "7", 230, 270, "500 g", 25),
  p("p596", "Haldiram's Petha", "हलदीराम पेठा", "Translucent ash-gourd candy from Agra — soft melt-in-mouth dry petha", "7", 185, 215, "400 g", 20),
  p("p597", "Haldiram's Besan Laddu", "हलदीराम बेसन लड्डू", "Roasted besan laddu with desi ghee and dry fruits — classic festive sweet", "7", 235, 275, "500 g", 25),
  p("p598", "Haldiram's Motichoor Laddu", "हलदीराम मोतीचूर लड्डू", "Soft melt-in-mouth motichoor laddu with saffron and cardamom", "7", 245, 285, "500 g", 25),
  p("p599", "Haldiram's Dry Fruit Mix Mithai", "हलदीराम ड्राई फ्रूट मिक्स", "Premium assorted mithai box with kaju, badam and pista barfi", "7", 595, 660, "500 g", 20),
  p("p600", "Mars Chocolate Bar", "मार्स चॉकलेट", "Smooth milk chocolate with nougat and caramel — iconic global treat", "7", 95, 110, "51 g", 35),
  p("p601", "Snickers Chocolate Bar", "स्निकर्स", "Roasted peanuts, caramel and nougat in milk chocolate — hunger satisfier", "7", 80, 90, "45 g", 40),
  p("p602", "Twix Chocolate Bar", "ट्विक्स", "Crunchy biscuit with caramel and milk chocolate — twin-finger pack", "7", 95, 110, "50 g", 30),
  p("p603", "Bounty Coconut Bar", "बाउंटी", "Tender coconut filling enrobed in milk chocolate — tropical paradise bite", "7", 80, 90, "57 g", 30),
  p("p604", "Toblerone Milk Chocolate", "टॉब्लरोन", "Iconic Swiss triangular chocolate with honey-almond nougat", "7", 425, 475, "100 g", 20),
  p("p605", "Lindt Lindor Milk Truffles", "लिंट लिंडोर ट्रफल", "Premium Swiss milk chocolate truffles with smooth melting centre", "7", 695, 775, "100 g", 18),
  p("p606", "Nestle Quality Street Assorted", "क्वालिटी स्ट्रीट", "British assorted chocolates and toffees tin — premium gifting", "7", 1295, 1450, "650 g", 12),
  p("p607", "Alpenliebe Original Toffee", "अल्पेनलीबे", "Creamy caramel hard candy with milky centre — pocket-friendly classic", "7", 50, 50, "100 pcs", 50),
  p("p608", "Melody Chocolaty Toffee", "मेलोडी टॉफी", "Khane wali nahin sochne wali — chewy chocolate toffee jar", "7", 40, 40, "100 pcs", 50),
  p("p609", "Parle Coffee Bite", "पार्ले कॉफी बाइट", "Real coffee-flavoured hard candy — Indian classic since decades", "7", 50, 50, "100 pcs", 50),
  p("p610", "Parle Mango Bite", "पार्ले मैंगो बाइट", "Pulpy mango-flavoured chewy candy — taste of Indian summer", "7", 50, 50, "100 pcs", 50),
  p("p611", "Fruitella Strawberry Candy", "फ्रूटेला स्ट्रॉबेरी", "Chewy strawberry-flavoured candies — fruity burst in every bite", "7", 25, 25, "32.4 g", 50),
  p("p612", "Big Babol Bubble Gum", "बिग बबल गम", "Soft chewy bubble gum for blowing big bubbles — kids' favourite", "7", 25, 25, "50 pcs", 55),
  p("p613", "Ferrero Rocher Gift Box (16 pcs)", "फेरेरो रोशे गिफ्ट बॉक्स", "Premium hazelnut praline chocolates with crispy wafer — 16-pcs gift box", "7", 685, 750, "200 g", 20),
  p("p614", "Nestle KitKat 4-Finger", "नेस्ले किटकैट 4-फिंगर", "Four-finger crisp wafer chocolate bar — share or break the moment", "7", 60, 70, "41.5 g", 45),
];
