// GENERATED by scripts/build-brand-cards.py — do not hand-edit.
// The 24 brands the home-page rail shows: a slim slice of brands-data.ts so the
// home bundle does not carry the full 161-entry manifest.
import type { BrandCard } from "@/lib/brands-data";

export const BRAND_RAIL: BrandCard[] = [
  {"slug": "amul", "name": "Amul", "parent": "Amul (GCMMF)", "logo": "/brands/amul.webp", "search": "Amul", "products": 53, "tile": false, "lowRes": false},
  {"slug": "britannia", "name": "Britannia", "parent": "Britannia", "logo": "/brands/britannia.webp", "search": "Britannia", "products": 37, "tile": false, "lowRes": false},
  {"slug": "aashirvaad", "name": "Aashirvaad", "parent": "ITC", "logo": "/brands/aashirvaad.webp", "search": "Aashirvaad", "products": 20, "tile": false, "lowRes": false},
  {"slug": "sunfeast", "name": "Sunfeast", "parent": "ITC", "logo": "/brands/sunfeast.webp", "search": "Sunfeast", "products": 20, "tile": false, "lowRes": false},
  {"slug": "nescafe", "name": "Nescafé", "parent": "Nestlé", "logo": "/brands/nescafe.webp", "search": "Nescafé", "products": 17, "tile": false, "lowRes": false},
  {"slug": "maggi", "name": "Maggi", "parent": "Nestlé", "logo": "/brands/maggi.webp", "search": "Maggi", "products": 16, "tile": false, "lowRes": false},
  {"slug": "yippee", "name": "YiPPee!", "parent": "ITC", "logo": "/brands/yippee.webp", "search": "Yippee", "products": 14, "tile": true, "lowRes": false},
  {"slug": "cadbury", "name": "Cadbury", "parent": "Mondelez (Cadbury)", "logo": "/brands/cadbury.webp", "search": "Cadbury", "products": 13, "tile": false, "lowRes": false},
  {"slug": "dabur", "name": "Dabur", "parent": "Dabur", "logo": "/brands/dabur.webp", "search": "Dabur", "products": 9, "tile": false, "lowRes": false},
  {"slug": "cerelac", "name": "Cerelac", "parent": "Nestlé", "logo": "/brands/cerelac.webp", "search": "Cerelac", "products": 8, "tile": false, "lowRes": false},
  {"slug": "kurkure", "name": "Kurkure", "parent": "PepsiCo", "logo": "/brands/kurkure.webp", "search": "Kurkure", "products": 7, "tile": false, "lowRes": false},
  {"slug": "pampers", "name": "Pampers", "parent": "Procter & Gamble", "logo": "/brands/pampers.webp", "search": "Pampers", "products": 7, "tile": false, "lowRes": false},
  {"slug": "ching-s-secret", "name": "Ching's Secret", "parent": "Tata Consumer", "logo": "/brands/ching-s-secret.webp", "search": "Ching's", "products": 6, "tile": false, "lowRes": false},
  {"slug": "colgate", "name": "Colgate", "parent": "Colgate-Palmolive", "logo": "/brands/colgate.webp", "search": "Colgate", "products": 6, "tile": true, "lowRes": false},
  {"slug": "lay-s", "name": "Lay's", "parent": "PepsiCo", "logo": "/brands/lay-s.webp", "search": "Lays", "products": 6, "tile": false, "lowRes": false},
  {"slug": "saffola", "name": "Saffola", "parent": "Marico", "logo": "/brands/saffola.webp", "search": "Saffola", "products": 6, "tile": false, "lowRes": true},
  {"slug": "horlicks", "name": "Horlicks", "parent": "Hindustan Unilever", "logo": "/brands/horlicks.webp", "search": "Horlicks", "products": 5, "tile": false, "lowRes": false},
  {"slug": "dettol", "name": "Dettol", "parent": "Reckitt", "logo": "/brands/dettol.webp", "search": "Dettol", "products": 4, "tile": false, "lowRes": false},
  {"slug": "kissan", "name": "Kissan", "parent": "Hindustan Unilever", "logo": "/brands/kissan.webp", "search": "Kissan", "products": 4, "tile": false, "lowRes": false},
  {"slug": "knorr", "name": "Knorr", "parent": "Hindustan Unilever", "logo": "/brands/knorr.webp", "search": "Knorr", "products": 4, "tile": false, "lowRes": false},
  {"slug": "lakme", "name": "Lakmé", "parent": "Hindustan Unilever", "logo": "/brands/lakme.webp", "search": "Lakmé", "products": 4, "tile": false, "lowRes": false},
  {"slug": "lifebuoy", "name": "Lifebuoy", "parent": "Hindustan Unilever", "logo": "/brands/lifebuoy.webp", "search": "Lifebuoy", "products": 4, "tile": false, "lowRes": false},
  {"slug": "surf-excel", "name": "Surf Excel", "parent": "Hindustan Unilever", "logo": "/brands/surf-excel.webp", "search": "Surf Excel", "products": 4, "tile": false, "lowRes": false},
  {"slug": "tropicana", "name": "Tropicana", "parent": "PepsiCo", "logo": "/brands/tropicana.webp", "search": "Tropicana", "products": 4, "tile": false, "lowRes": false},
];
