import type { Product, Category } from "@/types";

export const demoCategories: Category[] = [
  { id: "1", name: "Paan Corner", name_hi: "पान कॉर्नर", icon: "🥥", sort_order: 1, active: true },
  { id: "2", name: "Dairy", name_hi: "डेयरी", icon: "🥛", sort_order: 2, active: true },
  { id: "3", name: "Fruits & Vegetables", name_hi: "फल और सब्जी", icon: "🥬", sort_order: 3, active: true },
  { id: "4", name: "Cold Drinks & Juices", name_hi: "कोल्ड ड्रिंक्स और जूस", icon: "🥤", sort_order: 4, active: true },
  { id: "5", name: "Snacks & Munchies", name_hi: "स्नैक्स", icon: "🍿", sort_order: 5, active: true },
  { id: "6", name: "Breakfast & Instant Food", name_hi: "ब्रेकफास्ट और इंस्टेंट फूड", icon: "🍜", sort_order: 6, active: true },
  { id: "7", name: "Chocolates & Sweets", name_hi: "मीठा", icon: "🍫", sort_order: 7, active: true },
  { id: "8", name: "Bakery & Biscuits", name_hi: "बेकरी और बिस्किट", icon: "🍪", sort_order: 8, active: true },
  { id: "9", name: "Tea, Coffee & Health Drink", name_hi: "चाय, कॉफी और हेल्थ ड्रिंक", icon: "☕", sort_order: 9, active: true },
  { id: "10", name: "Atta, Rice & Dal", name_hi: "आटा, चावल और दाल", icon: "🌾", sort_order: 10, active: true },
  { id: "11", name: "Masala, Oil & More", name_hi: "मसाले, तेल और बहुत कुछ", icon: "🌶️", sort_order: 11, active: true },
  { id: "12", name: "Sauces & Spreads", name_hi: "सॉस और स्प्रेड", icon: "🍯", sort_order: 12, active: true },
  { id: "13", name: "Chicken, Meat & Fish", name_hi: "चिकन, मांस और मछली", icon: "🍗", sort_order: 13, active: true },
  { id: "15", name: "Baby Care", name_hi: "बेबी केयर", icon: "🍼", sort_order: 15, active: true },
  { id: "16", name: "Pharma & Wellness", name_hi: "दवाई और स्वास्थ्य", icon: "💊", sort_order: 16, active: true },
  { id: "17", name: "Cleaning Essentials", name_hi: "सफाई", icon: "🧹", sort_order: 17, active: true },
  { id: "18", name: "Stationery, Office & School", name_hi: "स्टेशनरी, ऑफिस और स्कूल", icon: "✏️", sort_order: 18, active: true },
  { id: "19", name: "Personal Care", name_hi: "पर्सनल केयर", icon: "🧴", sort_order: 19, active: true },
  { id: "20", name: "Pet Care", name_hi: "पेट केयर", icon: "🐶", sort_order: 20, active: true },
];

const p = (id: string, name: string, name_hi: string, desc: string, cat: string, price: number, mrp: number, unit: string, stock: number, img?: string): Product => ({
  id, name, name_hi, description: desc, category_id: cat, price, mrp, unit, image_url: img ?? null, stock, active: true, created_at: "",
});

export const demoProducts: Product[] = [
  // ─── Fruits & Vegetables (cat 1) ───
  p("p1", "Tamatar (Tomato)", "टमाटर", "Hand-picked farm-fresh tomatoes, ripe and juicy — perfect for sabzi, curry, and salads", "3", 30, 40, "500 g", 50, "/products/p1.webp"),
  p("p2", "Pyaz (Onion)", "प्याज", "Premium red onions sourced from Nashik farms — strong flavour, ideal for daily cooking", "3", 35, 45, "1 kg", 60),
  p("p3", "Aloo (Potato)", "आलू", "Farm-fresh raw potatoes, washed and graded — versatile for sabzi, fries, and curries", "3", 28, 35, "1 kg", 70),
  p("p4", "Kela (Banana)", "केला", "Naturally ripened bananas, rich in potassium — great for breakfast and post-workout snack", "3", 45, 50, "1 dozen", 30),
  p("p5", "Shimla Mirch (Capsicum)", "शिमला मिर्च", "Crunchy green capsicum, freshly harvested — adds colour and flavour to stir-fries and pizzas", "3", 40, 50, "250 g", 25),
  p("p6", "Palak (Spinach)", "पालक", "Tender baby spinach leaves, washed and ready — packed with iron, perfect for palak dishes", "3", 20, 25, "1 bunch", 35),
  p("p7", "Gajar (Carrot)", "गाजर", "Bright orange carrots, naturally sweet — eat raw, juice, or cook in halwa and sabzi", "3", 35, 42, "500 g", 40),
  p("p8", "Gobhi (Cauliflower)", "गोभी", "Tightly-packed fresh cauliflower head — versatile for aloo gobi, parathas, and pakoras", "3", 30, 40, "1 pc", 20),
  p("p9", "Bhindi (Lady Finger)", "भिंडी", "Tender young okra (bhindi), hand-picked — ideal for masala bhindi and kurkuri preparations", "3", 35, 45, "250 g", 30),
  p("p10", "Mirchi Hari (Green Chilli)", "हरी मिर्च", "Spicy fresh green chillies (hari mirch) — essential tadka and garnish ingredient", "3", 10, 15, "100 g", 60),
  p("p11", "Adrak (Ginger)", "अदरक", "Aromatic fresh ginger root — adds zing to chai, sabzi, and Indian curries", "3", 25, 30, "100 g", 40),
  p("p12", "Lehsun (Garlic)", "लहसुन", "Plump garlic cloves with natural skin — strong aroma, key for tadka and marinades", "3", 30, 40, "200 g", 35),
  p("p13", "Dhaniya Patta (Coriander)", "धनिया पत्ता", "Fresh coriander leaves with stems (dhaniya patta) — finishing touch for every Indian dish", "3", 10, 12, "1 bunch", 50),
  p("p14", "Nimbu (Lemon)", "नींबू", "Juicy thin-skinned lemons — perfect for nimbu pani, dal, and salad dressings", "3", 20, 25, "4 pcs", 45),
  p("p15", "Seb (Apple)", "सेब", "Crisp Shimla apples, naturally sweet — ideal for snacking and lunchbox", "3", 120, 150, "500 g", 20),
  p("p16", "Santra (Orange)", "संतरा", "Sweet seedless Nagpur oranges — refreshing, rich in vitamin C", "3", 60, 70, "500 g", 25),
  p("p17", "Papita (Papaya)", "पपीता", "Ripe sweet papaya — eat fresh or use in smoothies and salads", "3", 40, 50, "1 pc", 15),
  p("p18", "Aam (Mango)", "आम", "Sweet seasonal desi mango — enjoy chilled or in shakes, raita, and aamras", "3", 80, 100, "500 g", 30),

  // ─── Dairy & Bread (cat 2) ───
  p("p19", "Amul Taaza Milk", "अमूल ताज़ा दूध", "Amul Taaza pasteurised toned milk — 3% fat, perfect for chai, coffee, and daily use", "2", 28, 30, "500 ml", 40),
  p("p20", "Amul Gold Milk", "अमूल गोल्ड दूध", "Amul Gold full cream milk — 6% fat, rich and creamy, ideal for kheer and sweets", "2", 34, 36, "500 ml", 35),
  p("p21", "Mother Dairy Milk", "मदर डेयरी दूध", "Mother Dairy full cream pasteurised milk — fresh, thick, and rich in protein", "2", 32, 34, "500 ml", 30),
  p("p22", "Amul Butter", "अमूल मक्खन", "Amul pasteurised butter — utterly butterly delicious, perfect for parathas and toast", "2", 56, 58, "100 g", 25),
  p("p23", "Bread (White)", "ब्रेड सफ़ेद", "Soft white bread loaf, freshly baked — ideal for sandwiches and breakfast toast", "2", 40, 45, "400 g", 20),
  p("p24", "Bread (Brown/Wheat)", "ब्रेड ब्राउन", "Whole wheat brown bread — high-fibre, healthier choice for everyday breakfast", "2", 45, 50, "400 g", 18),
  p("p25", "Paneer (Fresh)", "पनीर", "Soft fresh paneer, made daily — high-protein, perfect for paneer butter masala and tikka", "2", 80, 90, "200 g", 15),
  p("p26", "Dahi (Curd)", "दही", "Thick fresh curd (dahi) — naturally fermented, great for raita, lassi, and digestion", "2", 30, 35, "400 g", 30),
  p("p27", "Amul Cheese Slices", "अमूल चीज़ स्लाइस", "Amul processed cheese slices — melts smoothly, perfect for sandwiches and burgers", "2", 95, 105, "200 g (10 slices)", 20),
  p("p28", "Amul Lassi Mango", "अमूल लस्सी आम", "Amul Mango Lassi — chilled creamy mango drink, ready to enjoy", "2", 25, 25, "200 ml", 40),
  p("p29", "Egg (Anda)", "अंडा", "Farm-fresh table eggs — rich in protein, white shell, ideal for omelette and bhurji", "2", 75, 84, "6 pcs", 25),
  p("p30", "Cream (Amul)", "अमूल क्रीम", "Amul fresh cream — rich and silky, use in soups, gravies, and desserts", "2", 42, 45, "200 ml", 15),

  // ─── Rice, Atta & Dal (cat 3) ───
  p("p31", "Aashirvaad Atta", "आशीर्वाद आटा", "Aashirvaad Shudh Chakki Atta — 100% whole wheat, stone-ground, soft rotis guaranteed", "10", 240, 280, "5 kg", 20),
  p("p32", "Aashirvaad Atta", "आशीर्वाद आटा", "Aashirvaad Shudh Chakki Atta — convenient 1 kg pack, stone-ground whole wheat", "10", 55, 62, "1 kg", 35),
  p("p33", "India Gate Basmati", "इंडिया गेट बासमती", "India Gate Super Basmati — extra-long aged grains, fluffy biryani and pulao", "10", 180, 210, "1 kg", 25),
  p("p34", "Dawat Rozana Basmati", "दावत रोज़ाना", "Dawat Rozana basmati rice — everyday long-grain rice for daily meals", "10", 85, 99, "1 kg", 30),
  p("p35", "Toor Dal (Arhar)", "तूर दाल", "Premium toor dal (arhar) — unpolished split pigeon peas, the heart of dal tadka", "10", 140, 160, "1 kg", 30),
  p("p36", "Moong Dal", "मूंग दाल", "Yellow moong dal (split) — light and easy to digest, perfect for khichdi and dal", "10", 120, 140, "1 kg", 28),
  p("p37", "Chana Dal", "चना दाल", "Chana dal (Bengal gram split) — protein-rich, ideal for dal, mithai, and snacks", "10", 95, 110, "1 kg", 25),
  p("p38", "Masoor Dal", "मसूर दाल", "Masoor dal (red lentils) — quick-cooking, mildly sweet, perfect for daily dal", "10", 90, 105, "1 kg", 22),
  p("p39", "Urad Dal", "उड़द दाल", "Whole urad dal (black gram) — base for dal makhani and idli-dosa batter", "10", 130, 150, "1 kg", 20),
  p("p40", "Rajma (Kidney Beans)", "राजमा", "Premium Chitra rajma (kidney beans) — soft texture, ideal for rajma chawal", "10", 120, 140, "500 g", 18),
  p("p41", "Chole (Chickpeas)", "छोले", "Kabuli chana (white chickpeas) — large grain, perfect for chole and chaat", "10", 85, 99, "500 g", 25),
  p("p42", "Poha (Flattened Rice)", "पोहा", "Thick variety poha (flattened rice) — quick breakfast staple, ready in minutes", "10", 35, 40, "500 g", 30),
  p("p43", "Suji (Semolina)", "सूजी", "Fine semolina (suji/rava) — ideal for upma, halwa, and idli batter", "10", 38, 42, "500 g", 28),
  p("p44", "Besan (Gram Flour)", "बेसन", "Pure gram flour (besan) — fine-milled, essential for pakoras, kadhi, and laddoos", "10", 55, 65, "500 g", 25),
  p("p45", "Maida", "मैदा", "Refined wheat flour (maida) — for cakes, puris, parathas, and bakery items", "10", 35, 40, "500 g", 30),

  // ─── Oil & Ghee (cat 4) ───
  p("p46", "Fortune Soyabean Oil", "फॉर्च्यून तेल", "Fortune refined soyabean oil — light and healthy, ideal for everyday cooking", "11", 145, 165, "1 L", 25),
  p("p47", "Fortune Sunflower Oil", "फॉर्च्यून सनफ्लावर", "Fortune refined sunflower oil — heart-friendly, low in saturated fat", "11", 155, 175, "1 L", 20),
  p("p48", "Amul Ghee", "अमूल घी", "Amul pure cow ghee — granular, aromatic, made from rich Indian milk", "11", 290, 320, "500 ml", 15),
  p("p49", "Patanjali Mustard Oil", "पतंजलि सरसों तेल", "Patanjali kachi ghani mustard oil — cold-pressed, traditional pungent flavour", "11", 170, 190, "1 L", 20),
  p("p50", "Saffola Gold Oil", "सैफोला गोल्ड", "Saffola Gold blended oil — rice bran + corn oil, supports heart health", "11", 185, 210, "1 L", 15),
  p("p51", "Sundrop Refined Oil", "सनड्रॉप तेल", "Sundrop refined sunflower oil — light, clean taste for daily cooking", "11", 150, 168, "1 L", 18),

  // ─── Masala & Spices (cat 5) ───
  p("p52", "MDH Garam Masala", "एमडीएच गरम मसाला", "MDH Garam Masala — authentic blend of 11 spices, signature aroma for curries", "11", 72, 80, "100 g", 35),
  p("p53", "Haldi Powder (Turmeric)", "हल्दी पाउडर", "Pure turmeric powder (haldi) — bright yellow, high-curcumin, daily essential", "11", 40, 48, "100 g", 40),
  p("p54", "Lal Mirch Powder", "लाल मिर्च पाउडर", "Kashmiri red chilli powder (lal mirch) — rich colour with balanced heat", "11", 55, 65, "100 g", 35),
  p("p55", "Dhaniya Powder (Coriander)", "धनिया पाउडर", "Fresh-ground coriander powder (dhaniya) — earthy aroma, base spice for curries", "11", 32, 38, "100 g", 40),
  p("p56", "Jeera Powder (Cumin)", "जीरा पाउडर", "Roasted cumin powder (jeera) — warm nutty flavour, perfect for raita and chaat", "11", 58, 68, "100 g", 30),
  p("p57", "Sabut Jeera (Cumin Seeds)", "साबुत जीरा", "Whole cumin seeds (sabut jeera) — for tadka, jeera rice, and tempering", "11", 65, 75, "100 g", 35),
  p("p58", "Sabut Dhaniya (Coriander Seeds)", "साबुत धनिया", "Whole coriander seeds (sabut dhaniya) — roast and grind fresh, full aroma", "11", 28, 35, "100 g", 40),
  p("p59", "Rai / Sarson (Mustard Seeds)", "राई / सरसों", "Black mustard seeds (rai/sarson) — essential for South Indian tadka and pickles", "11", 20, 25, "100 g", 50),
  p("p60", "Kali Mirch (Black Pepper)", "काली मिर्च", "Whole black peppercorns (kali mirch) — grind fresh for maximum flavour", "11", 85, 99, "50 g", 25),
  p("p61", "Hing (Asafoetida)", "हींग", "Strong asafoetida (hing) powder — aids digestion, signature smoky aroma", "11", 55, 65, "10 g", 30),
  p("p62", "Chaat Masala", "चाट मसाला", "Tangy chaat masala — sprinkle on fruits, chaat, and salads for instant zing", "11", 30, 35, "100 g", 40),
  p("p63", "Pav Bhaji Masala", "पाव भाजी मसाला", "MDH Pav Bhaji Masala — Mumbai-style authentic blend, ready in minutes", "11", 45, 52, "100 g", 25),
  p("p64", "Kitchen King Masala", "किचन किंग मसाला", "MDH Kitchen King Masala — versatile all-purpose blend for everyday sabzi", "11", 55, 62, "100 g", 28),
  p("p65", "Namak (Salt)", "नमक", "Tata Salt iodized — India's most trusted, fine free-flowing salt", "11", 22, 22, "1 kg", 60),
  p("p66", "Cheeni (Sugar)", "चीनी", "Pure refined white sugar — fine grain, perfect for tea, sweets, and baking", "11", 42, 48, "1 kg", 40),

  // ─── Snacks & Biscuits (cat 6) ───
  p("p67", "Lays Classic Salted", "लेज़ क्लासिक", "Lay's Classic Salted — crispy thinly-sliced potato chips, irresistible taste", "5", 20, 20, "52 g", 60),
  p("p68", "Lays Magic Masala", "लेज़ मैजिक मसाला", "Lay's India's Magic Masala — bold spicy flavour, India's most loved chip", "5", 20, 20, "52 g", 55),
  p("p69", "Kurkure Masala Munch", "कुरकुरे", "Kurkure Masala Munch — crunchy corn puffs with tangy masala, iconic snack", "5", 20, 20, "75 g", 50),
  p("p70", "Haldiram Aloo Bhujia", "हल्दीराम आलू भुजिया", "Haldiram's Aloo Bhujia — crispy spiced potato sticks, perfect chai-time namkeen", "5", 50, 55, "200 g", 30),
  p("p71", "Haldiram Moong Dal", "हल्दीराम मूंग दाल", "Haldiram's Moong Dal — crunchy roasted dal, lightly salted, healthy bites", "5", 45, 50, "200 g", 28),
  p("p72", "Parle-G Biscuits", "पारले-जी", "Parle-G Original Glucose Biscuits — India's favourite, energy in every bite", "8", 10, 10, "80 g", 80),
  p("p73", "Britannia Good Day", "ब्रिटानिया गुड डे", "Britannia Good Day Butter Cookies — buttery, rich, melt-in-mouth cookies", "8", 30, 30, "75 g", 45),
  p("p74", "Britannia Marie Gold", "ब्रिटानिया मारी गोल्ड", "Britannia Marie Gold — light, crispy tea-time biscuit, India's classic choice", "8", 30, 30, "250 g", 40),
  p("p75", "Dark Fantasy Choco Fills", "डार्क फैंटेसी", "Sunfeast Dark Fantasy Choco Fills — crunchy outside, molten chocolate inside", "8", 40, 40, "75 g", 35),
  p("p76", "Oreo Biscuit", "ओरियो", "Cadbury Oreo Vanilla Cream — chocolate biscuit with classic vanilla filling", "8", 30, 30, "120 g", 50),
  p("p77", "Bingo Mad Angles", "बिंगो मैड एंगल्स", "Bingo Mad Angles Achari Masti — triangle chips, achaari Indian flavour", "5", 20, 20, "66 g", 40),
  p("p78", "Uncle Chipps", "अंकल चिप्स", "Uncle Chipps Spicy Treat — bold masala potato chips, full of crunch", "5", 20, 20, "55 g", 35),
  p("p79", "Haldiram Namkeen Mixture", "हल्दीराम नमकीन मिक्स", "Haldiram's Classic Namkeen Mixture — assorted crispy mix, perfect with chai", "5", 55, 60, "200 g", 25),
  p("p80", "Cadbury Dairy Milk", "कैडबरी डेयरी मिल्क", "Cadbury Dairy Milk — smooth creamy milk chocolate, India's #1 chocolate bar", "7", 40, 40, "50 g", 50),
  p("p81", "5 Star Chocolate", "5 स्टार चॉकलेट", "Cadbury 5 Star — chewy caramel chocolate bar, eat one to lose focus", "7", 20, 20, "40 g", 55),
  p("p82", "KitKat", "किटकैट", "Nestlé KitKat — crisp chocolate wafer fingers, have a break, have a KitKat", "7", 30, 30, "37.3 g", 45),

  // ─── Beverages (cat 7) ───
  p("p83", "Coca-Cola", "कोका-कोला", "Coca-Cola Original Taste — chilled fizzy refreshment, the classic cola", "4", 40, 40, "750 ml", 40),
  p("p84", "Thums Up", "थम्स अप", "Thums Up — strong, fizzy cola with kick, taste the thunder", "4", 40, 40, "750 ml", 35),
  p("p85", "Sprite", "स्प्राइट", "Sprite — clear lime-lemon drink, crisp and refreshing", "4", 40, 40, "750 ml", 30),
  p("p86", "Maaza Mango", "माज़ा आम", "Maaza Mango — thick rich mango drink, taste of Indian summer", "4", 25, 25, "250 ml", 45),
  p("p87", "Frooti Mango", "फ्रूटी आम", "Frooti Mango Drink — ripe sweet mango taste, India's favourite tetra pack", "4", 10, 10, "200 ml", 60),
  p("p88", "Tata Tea Gold", "टाटा टी गोल्ड", "Tata Tea Gold — premium long-leaf tea with assam blend, full-bodied chai", "9", 165, 180, "250 g", 20),
  p("p89", "Red Label Tea", "रेड लेबल चाय", "Brooke Bond Red Label — strong, fragrant Indian tea, the family favourite", "9", 140, 155, "250 g", 22),
  p("p90", "Nescafe Classic Coffee", "नेस्कैफे क्लासिक", "Nescafé Classic — 100% pure instant coffee, rich aroma in every cup", "9", 195, 220, "100 g", 18),
  p("p91", "Bru Instant Coffee", "ब्रू कॉफ़ी", "Bru Instant Coffee — smooth coffee-chicory blend, energising taste", "9", 165, 185, "100 g", 15),
  p("p92", "Bournvita", "बोर्नविटा", "Cadbury Bournvita — chocolate health drink with vitamins and minerals", "9", 210, 240, "500 g", 20),
  p("p93", "Horlicks Classic Malt", "हॉर्लिक्स", "Horlicks Classic Malt — nutritious malt drink with 24 vital nutrients", "9", 225, 255, "500 g", 18),
  p("p94", "Rooh Afza Sharbat", "रूह अफ़ज़ा", "Hamdard Rooh Afza — classic rose-flavoured sharbat, summer cooler", "4", 120, 135, "750 ml", 15),
  p("p95", "Paper Boat Aam Panna", "पेपर बोट आम पन्ना", "Paper Boat Aam Panna — traditional raw mango drink, authentic desi taste", "4", 30, 30, "200 ml", 25),
  p("p96", "Limca", "लिम्का", "Limca — sparkling lime-lemon drink, India's original thirst-quencher", "4", 40, 40, "750 ml", 30),
  p("p97", "Real Fruit Juice Mixed", "रियल जूस मिक्स", "Real Mixed Fruit Juice — no added preservatives, daily fruit goodness", "4", 90, 99, "1 L", 15),

  // ─── Instant Food (cat 8) ───
  p("p98", "Maggi 2-Minute Noodles", "मैगी नूडल्स", "Maggi 2-Minute Noodles — masala flavour, India's iconic quick snack", "6", 14, 14, "70 g", 100),
  p("p99", "Maggi Masala (4-Pack)", "मैगी मसाला 4-पैक", "Maggi Masala Noodles 4-Pack — family pack value, kids' all-time favourite", "6", 52, 56, "280 g", 40),
  p("p100", "Yippee Noodles", "यिप्पी नूडल्स", "Sunfeast YiPPee Magic Masala — slim long noodles, spicy masala flavour", "6", 14, 14, "70 g", 60),
  p("p101", "Top Ramen Curry", "टॉप रामेन करी", "Nissin Top Ramen Curry — Japanese-style curry noodles, ready in 3 minutes", "6", 14, 14, "70 g", 35),
  p("p102", "MTR Ready Meal - Paneer Butter Masala", "MTR पनीर बटर मसाला", "MTR Paneer Butter Masala — ready-to-eat rich gravy, restaurant taste at home", "6", 85, 99, "300 g", 20),
  p("p103", "MTR Ready Meal - Dal Makhani", "MTR दाल मखनी", "MTR Dal Makhani — slow-cooked creamy dal, just heat and eat", "6", 75, 89, "300 g", 18),
  p("p104", "Haldiram Minute Khana - Rajma Chawal", "हल्दीराम राजमा चावल", "Haldiram's Rajma Chawal — complete ready-to-eat North Indian meal", "6", 90, 105, "375 g", 12),
  p("p105", "Knorr Soup - Tomato", "नॉर टमाटर सूप", "Knorr Classic Tomato Soup — smooth instant soup mix, warm comfort in a bowl", "6", 45, 50, "51 g", 30),
  p("p106", "Ching's Schezwan Noodles", "चिंग्स शेजवान", "Ching's Schezwan Noodles — desi-Chinese fiery spice, restaurant-style", "6", 25, 25, "60 g", 40),
  p("p107", "Saffola Oats", "सैफोला ओट्स", "Saffola Classic Oats — 100% whole grain, fibre-rich healthy breakfast", "6", 99, 115, "500 g", 15),
  p("p108", "Kellogg's Cornflakes", "कैलॉग्स कॉर्नफ्लेक्स", "Kellogg's Original Cornflakes — golden crunchy flakes, iron-fortified breakfast", "6", 165, 185, "475 g", 12),
  p("p109", "Upma Mix (MTR)", "एमटीआर उपमा मिक्स", "MTR Instant Upma Mix — South Indian breakfast ready in minutes", "6", 50, 58, "200 g", 20),

  // ─── Personal Care (cat 9) ───
  p("p110", "Colgate MaxFresh", "कोलगेट मैक्सफ्रेश", "Colgate MaxFresh — cooling crystals for long-lasting fresh breath", "19", 85, 95, "150 g", 30),
  p("p111", "Pepsodent Germicheck", "पेप्सोडेंट", "Pepsodent Germicheck — fights germs, prevents cavities, daily protection", "19", 55, 62, "150 g", 25),
  p("p112", "Dove Soap", "डव साबुन", "Dove Cream Beauty Bar — 1/4 moisturising cream, gentle on sensitive skin", "19", 48, 52, "100 g", 35),
  p("p113", "Lux Soap", "लक्स साबुन", "Lux Soft Touch Soap — rose & almond oil, silky smooth skin", "19", 35, 38, "100 g", 40),
  p("p114", "Lifebuoy Handwash", "लाइफबॉय हैंडवॉश", "Lifebuoy Total 10 Handwash — kills 99.9% germs, complete hand hygiene", "19", 99, 115, "190 ml", 25),
  p("p115", "Dettol Handwash", "डेटॉल हैंडवॉश", "Dettol Original Liquid Handwash — trusted antibacterial protection", "19", 109, 125, "200 ml", 20),
  p("p116", "Head & Shoulders Shampoo", "हेड एंड शोल्डर्स", "Head & Shoulders Anti-Dandruff Shampoo — clinically proven, flake-free hair", "19", 185, 210, "180 ml", 15),
  p("p117", "Clinic Plus Shampoo", "क्लिनिक प्लस", "Clinic Plus Strong & Long Shampoo — milk protein formula, healthy hair", "19", 95, 105, "175 ml", 20),
  p("p118", "Parachute Coconut Oil", "पैराशूट नारियल तेल", "Parachute 100% Pure Coconut Oil — natural hair nourishment, skin care", "19", 105, 115, "200 ml", 25),
  p("p119", "Nivea Body Lotion", "निवेआ बॉडी लोशन", "Nivea Nourishing Body Lotion — 48-hour moisture for soft smooth skin", "19", 195, 225, "200 ml", 12),
  p("p120", "Gillette Guard Razor", "जिलेट गार्ड", "Gillette Guard Razor — single-blade safety razor for clean comfortable shave", "19", 45, 49, "1 pc", 30),
  p("p121", "Whisper Choice Pads", "व्हिस्पर चॉइस", "Whisper Choice Regular Pads — dependable absorption, all-day comfort", "19", 42, 46, "7 pcs", 25),
  p("p122", "Vicks VapoRub", "विक्स वेपोरब", "Vicks VapoRub — soothing balm for cold, cough, and blocked nose", "16", 72, 80, "25 ml", 20),
  p("p123", "Band-Aid (Johnson's)", "बैंड-एड", "Johnson's Band-Aid Bandages — quick-stick wound care for minor cuts", "16", 40, 45, "10 pcs", 30),
  p("p124", "Vaseline Petroleum Jelly", "वैसलीन", "Vaseline Original Petroleum Jelly — deep moisturising, all-purpose skin care", "19", 75, 85, "100 g", 18),

  // ─── Cleaning (cat 10) ───
  p("p125", "Vim Dishwash Bar", "विम बार", "Vim Lemon Dishwash Bar — tough on grease, gentle on hands", "17", 10, 10, "140 g", 60),
  p("p126", "Vim Dishwash Gel", "विम जेल", "Vim Lemon Dishwash Gel — fast grease cut, fresh lemon fragrance", "17", 99, 115, "500 ml", 25),
  p("p127", "Surf Excel Detergent", "सर्फ एक्सेल", "Surf Excel Easy Wash Detergent — removes tough stains in fewer mugs of water", "17", 120, 135, "1 kg", 20),
  p("p128", "Rin Detergent Bar", "रिन बार", "Rin Detergent Bar — bright whites with chamak, value-for-money", "17", 25, 28, "250 g", 40),
  p("p129", "Harpic Toilet Cleaner", "हार्पिक", "Harpic Power Plus Toilet Cleaner — 10X stronger, kills 99.9% germs", "17", 85, 95, "500 ml", 20),
  p("p130", "Lizol Floor Cleaner", "लाइज़ॉल", "Lizol Citrus Floor Cleaner — disinfects floor, kills 1000 germs", "17", 115, 130, "500 ml", 18),
  p("p131", "Colin Glass Cleaner", "कॉलिन", "Colin Glass & Surface Cleaner — streak-free shine in seconds", "17", 85, 95, "500 ml", 15),
  p("p132", "Scotch-Brite Scrub Pad", "स्कॉच-ब्राइट", "Scotch-Brite Heavy Duty Scrub Pad — tough scrub power for stuck-on grime", "17", 30, 32, "1 pc", 40),
  p("p133", "Odonil Air Freshener", "ओडोनिल", "Odonil Room Freshener Block — long-lasting fragrance for bathrooms and rooms", "17", 45, 52, "75 g", 25),
  p("p134", "Good Knight Liquid Refill", "गुडनाइट", "Good Knight Liquid Refill — 45-night protection from mosquitoes", "17", 68, 75, "45 ml", 30),
  p("p135", "Hit Spray", "हिट स्प्रे", "Hit Cockroach & Ant Killer Spray — instant kill, deep reach formula", "17", 155, 175, "200 ml", 15),
  p("p136", "Garbage Bags (Black)", "कचरा बैग", "Heavy-duty black garbage bags — leak-proof, large capacity for kitchen waste", "17", 60, 70, "30 pcs", 25),
  p("p137", "Prill Dishwash Liquid", "प्रिल डिशवॉश", "Prill Dishwash Liquid — sparkling clean utensils with fresh lime fragrance", "17", 55, 62, "250 ml", 20),

  // ─── Baby Care (cat 11) ───
  p("p138", "Pampers Diapers (S)", "पैम्पर्स डायपर", "Pampers Baby Dry Pants (S) — up to 12-hour overnight dryness, soft on skin", "15", 399, 450, "22 pcs", 12),
  p("p139", "Pampers Diapers (M)", "पैम्पर्स डायपर", "Pampers Baby Dry Pants (M) — 5-star absorption, comfortable fit", "15", 449, 499, "20 pcs", 10),
  p("p140", "MamyPoko Pants (L)", "मैमीपोको पैंट", "MamyPoko Pants Standard (L) — easy to wear, super absorbent", "15", 499, 549, "18 pcs", 10),
  p("p141", "Johnson's Baby Soap", "जॉनसन बेबी साबुन", "Johnson's Baby Soap — gentle cleansing, no more tears formula", "15", 55, 62, "100 g", 20),
  p("p142", "Johnson's Baby Powder", "जॉनसन बेबी पाउडर", "Johnson's Baby Powder — soft mild fragrance, keeps baby fresh and dry", "15", 95, 105, "200 g", 15),
  p("p143", "Johnson's Baby Oil", "जॉनसन बेबी ऑयल", "Johnson's Baby Oil — clinically proven mild, daily massage and moisturising", "15", 140, 160, "200 ml", 12),
  p("p144", "Cerelac Baby Food (Wheat)", "सेरेलैक", "Nestlé Cerelac Wheat Stage 1 — fortified baby cereal, 6+ months", "15", 230, 260, "300 g", 10),
  p("p145", "Himalaya Baby Cream", "हिमालया बेबी क्रीम", "Himalaya Baby Cream — moisturising cream with olive oil & almond", "15", 85, 99, "100 ml", 15),
  p("p146", "Baby Wet Wipes", "बेबी वेट वाइप्स", "Gentle baby wet wipes — paraben-free, ideal for sensitive skin", "15", 75, 85, "72 pcs", 18),

  // ─── Pooja Needs (cat 12) ───
  p("p147", "Cycle Agarbatti", "साइकिल अगरबत्ती", "Cycle Pure Agarbatti — classic fragrance incense sticks, charcoal-free", "18", 35, 40, "120 sticks", 40),
  p("p148", "Mangaldeep Agarbatti", "मंगलदीप अगरबत्ती", "Mangaldeep Agarbatti — pure devotional fragrance, premium quality sticks", "18", 40, 45, "90 sticks", 30),
  p("p149", "Ghee Diya Batti", "घी दिया बत्ती", "Pure cotton ghee diya batti — long-burning wicks for daily pooja", "18", 15, 20, "1 pack", 50),
  p("p150", "Camphor (Kapur)", "कपूर", "Pure camphor tablets (kapur) — for aarti, pooja, and dhoop", "18", 30, 35, "50 g", 35),
  p("p151", "Sindoor", "सिंदूर", "Traditional red sindoor powder — auspicious, fine-textured", "18", 20, 25, "10 g", 30),
  p("p152", "Roli Kumkum", "रोली कुमकुम", "Roli kumkum powder — for tilak, pooja, and ceremonial use", "18", 15, 18, "1 pack", 40),
  p("p153", "Dhoop Batti", "धूप बत्ती", "Aromatic dhoop batti cones — long-lasting fragrance for spiritual ambience", "18", 25, 30, "20 pcs", 35),
  p("p154", "Gangajal", "गंगाजल", "Bottled holy Ganga jal — for daily pooja and rituals", "18", 20, 25, "100 ml", 25),
  p("p155", "Kalawa (Mauli)", "कलावा मौली", "Sacred kalawa / mauli thread — auspicious red-yellow puja thread", "18", 10, 12, "1 roll", 50),
  p("p156", "Janeu (Sacred Thread)", "जनेऊ", "Pure cotton janeu (sacred thread) — for yajnopavit and rituals", "18", 15, 18, "1 pack", 30),
  p("p157", "Coconut (Nariyal)", "नारियल", "Dry coconut (nariyal) — whole, for pooja and prasad offerings", "18", 35, 40, "1 pc", 25),
  p("p158", "Supari (Betel Nut)", "सुपारी", "Whole betel nut (supari) — premium quality, for pooja and beverages", "18", 20, 25, "50 g", 30),
];
