/**
 * Naya Raipur service-area data — GENERATED by scripts/generate-sectors-seed.mjs,
 * do not hand-edit. Mirrors the public.sectors seed (migration 020) so the
 * storefront can show ETAs and render /delivery/<sector> pages without a DB
 * round-trip. Distances are straight-line from the Sector 27 dark store.
 */

export interface Eta {
  min: number;
  max: number;
  zone: string;
}

export interface SectorArea {
  slug: string;
  name: string;
  nameHi: string;
  pincode: string;
  /** Pincode is the nearest serviceable one, not India Post verified. */
  pincodeApprox: boolean;
  areaType: "residential" | "civic" | "campus";
  lat: number;
  lng: number;
  /** Straight-line metres from the dark store. */
  distanceM: number;
  eta: Eta;
  /** false = mapped but not yet serviceable ("coming soon"). */
  active: boolean;
}

export const SECTOR_AREAS: SectorArea[] = [
  {
    "slug": "sector-21",
    "name": "Sector 21",
    "nameHi": "सेक्टर 21",
    "pincode": "492101",
    "pincodeApprox": false,
    "areaType": "residential",
    "lat": 21.169846,
    "lng": 81.772485,
    "distanceM": 3290,
    "eta": {
      "min": 25,
      "max": 30,
      "zone": "Medium"
    },
    "active": true
  },
  {
    "slug": "sector-22",
    "name": "Sector 22",
    "nameHi": "सेक्टर 22",
    "pincode": "492101",
    "pincodeApprox": false,
    "areaType": "residential",
    "lat": 21.1712,
    "lng": 81.75795,
    "distanceM": 4057,
    "eta": {
      "min": 25,
      "max": 30,
      "zone": "Medium"
    },
    "active": true
  },
  {
    "slug": "sector-23",
    "name": "Sector 23",
    "nameHi": "सेक्टर 23",
    "pincode": "492101",
    "pincodeApprox": false,
    "areaType": "residential",
    "lat": 21.1610268,
    "lng": 81.7864412,
    "distanceM": 2308,
    "eta": {
      "min": 20,
      "max": 25,
      "zone": "Near"
    },
    "active": true
  },
  {
    "slug": "sector-24",
    "name": "Sector 24",
    "nameHi": "सेक्टर 24",
    "pincode": "492101",
    "pincodeApprox": false,
    "areaType": "residential",
    "lat": 21.153,
    "lng": 81.787,
    "distanceM": 1501,
    "eta": {
      "min": 20,
      "max": 25,
      "zone": "Near"
    },
    "active": true
  },
  {
    "slug": "sector-25",
    "name": "Sector 25",
    "nameHi": "सेक्टर 25",
    "pincode": "492101",
    "pincodeApprox": false,
    "areaType": "residential",
    "lat": 21.146478,
    "lng": 81.791561,
    "distanceM": 1328,
    "eta": {
      "min": 20,
      "max": 25,
      "zone": "Near"
    },
    "active": true
  },
  {
    "slug": "sector-26",
    "name": "Sector 26",
    "nameHi": "सेक्टर 26",
    "pincode": "492101",
    "pincodeApprox": false,
    "areaType": "residential",
    "lat": 21.138913,
    "lng": 81.792676,
    "distanceM": 1326,
    "eta": {
      "min": 20,
      "max": 25,
      "zone": "Near"
    },
    "active": true
  },
  {
    "slug": "sector-27",
    "name": "Sector 27",
    "nameHi": "सेक्टर 27",
    "pincode": "492101",
    "pincodeApprox": false,
    "areaType": "residential",
    "lat": 21.140914,
    "lng": 81.784952,
    "distanceM": 503,
    "eta": {
      "min": 15,
      "max": 20,
      "zone": "Immediate"
    },
    "active": true
  },
  {
    "slug": "sector-28",
    "name": "Sector 28",
    "nameHi": "सेक्टर 28",
    "pincode": "492101",
    "pincodeApprox": false,
    "areaType": "residential",
    "lat": 21.138352,
    "lng": 81.777399,
    "distanceM": 418,
    "eta": {
      "min": 15,
      "max": 20,
      "zone": "Immediate"
    },
    "active": true
  },
  {
    "slug": "sector-29",
    "name": "Sector 29",
    "nameHi": "सेक्टर 29",
    "pincode": "492101",
    "pincodeApprox": false,
    "areaType": "residential",
    "lat": 21.133829,
    "lng": 81.782033,
    "distanceM": 836,
    "eta": {
      "min": 15,
      "max": 20,
      "zone": "Immediate"
    },
    "active": true
  },
  {
    "slug": "sector-30",
    "name": "Sector 30",
    "nameHi": "सेक्टर 30",
    "pincode": "492101",
    "pincodeApprox": true,
    "areaType": "residential",
    "lat": 21.130987,
    "lng": 81.791604,
    "distanceM": 1641,
    "eta": {
      "min": 20,
      "max": 25,
      "zone": "Near"
    },
    "active": true
  },
  {
    "slug": "sector-20",
    "name": "Sector 20",
    "nameHi": "सेक्टर 20",
    "pincode": "492018",
    "pincodeApprox": true,
    "areaType": "residential",
    "lat": 21.166478,
    "lng": 81.78327,
    "distanceM": 2838,
    "eta": {
      "min": 25,
      "max": 30,
      "zone": "Medium"
    },
    "active": true
  },
  {
    "slug": "sector-19",
    "name": "Sector 19",
    "nameHi": "सेक्टर 19",
    "pincode": "492030",
    "pincodeApprox": true,
    "areaType": "residential",
    "lat": 21.159034,
    "lng": 81.795544,
    "distanceM": 2555,
    "eta": {
      "min": 25,
      "max": 30,
      "zone": "Medium"
    },
    "active": true
  },
  {
    "slug": "capital-complex",
    "name": "Capital Complex",
    "nameHi": "कैपिटल कॉम्प्लेक्स",
    "pincode": "492018",
    "pincodeApprox": false,
    "areaType": "civic",
    "lat": 21.157291,
    "lng": 81.798267,
    "distanceM": 2603,
    "eta": {
      "min": 25,
      "max": 30,
      "zone": "Medium"
    },
    "active": true
  },
  {
    "slug": "iiit-naya-raipur",
    "name": "IIIT Naya Raipur",
    "nameHi": "IIIT नया रायपुर",
    "pincode": "492101",
    "pincodeApprox": true,
    "areaType": "campus",
    "lat": 21.1290954,
    "lng": 81.7656956,
    "distanceM": 2006,
    "eta": {
      "min": 20,
      "max": 25,
      "zone": "Near"
    },
    "active": true
  },
  {
    "slug": "hnlu",
    "name": "HNLU",
    "nameHi": "HNLU",
    "pincode": "492101",
    "pincodeApprox": true,
    "areaType": "campus",
    "lat": 21.1072823,
    "lng": 81.7583812,
    "distanceM": 4387,
    "eta": {
      "min": 25,
      "max": 30,
      "zone": "Medium"
    },
    "active": true
  },
  {
    "slug": "sector-7",
    "name": "Sector 7",
    "nameHi": "सेक्टर 7",
    "pincode": "492015",
    "pincodeApprox": true,
    "areaType": "residential",
    "lat": 21.193735,
    "lng": 81.779308,
    "distanceM": 5850,
    "eta": {
      "min": 35,
      "max": 45,
      "zone": "Far"
    },
    "active": false
  },
  {
    "slug": "sector-2",
    "name": "Sector 2",
    "nameHi": "सेक्टर 2",
    "pincode": "492015",
    "pincodeApprox": true,
    "areaType": "residential",
    "lat": 21.213109,
    "lng": 81.814872,
    "distanceM": 8778,
    "eta": {
      "min": 45,
      "max": 60,
      "zone": "Outer"
    },
    "active": false
  },
  {
    "slug": "sector-3",
    "name": "Sector 3",
    "nameHi": "सेक्टर 3",
    "pincode": "492015",
    "pincodeApprox": true,
    "areaType": "residential",
    "lat": 21.202256,
    "lng": 81.826246,
    "distanceM": 8312,
    "eta": {
      "min": 45,
      "max": 60,
      "zone": "Outer"
    },
    "active": false
  }
];

export const ACTIVE_SECTOR_AREAS = SECTOR_AREAS.filter((s) => s.active);

export function findSectorArea(nameOrSlug: string): SectorArea | undefined {
  const key = nameOrSlug.toLowerCase().trim();
  return SECTOR_AREAS.find((s) => s.slug === key || s.name.toLowerCase() === key);
}

