-- 020_sectors_all.sql — auto-generated by scripts/generate-sectors-seed.mjs
-- DO NOT hand-edit; regenerate after updating centres.
--
-- Full Naya Raipur service-area seed: Sector 19–30, Capital Complex, IIIT,
-- HNLU (active) + Sector 2/3/7 (mapped, inactive until the owner enables).
-- Polygons are ~1 km boxes around OSM centres; pincodes marked "approx" in
-- source are the nearest serviceable pincode, not India Post verified.
-- Idempotent: replaces every row keyed by name.

delete from public.sectors;

insert into public.sectors (name, name_hi, pincode, area_type, geometry, centroid_lat, centroid_lng, source, active)
values
  ('Sector 21', 'सेक्टर 21', '492101', 'residential',
   extensions.ST_GeomFromText('POLYGON((81.7676634 21.1653374, 81.7773066 21.1653374, 81.7773066 21.1743546, 81.7676634 21.1743546, 81.7676634 21.1653374))', 4326), 21.169846, 81.772485, 'OSM', true),
  ('Sector 22', 'सेक्टर 22', '492101', 'residential',
   extensions.ST_GeomFromText('POLYGON((81.7531284 21.1666914, 81.7627716 21.1666914, 81.7627716 21.1757086, 81.7531284 21.1757086, 81.7531284 21.1666914))', 4326), 21.1712, 81.75795, 'OSM', true),
  ('Sector 23', 'सेक्टर 23', '492101', 'residential',
   extensions.ST_GeomFromText('POLYGON((81.7816196 21.1565182, 81.7912628 21.1565182, 81.7912628 21.1655354, 81.7816196 21.1655354, 81.7816196 21.1565182))', 4326), 21.1610268, 81.7864412, 'Nominatim/approx', true),
  ('Sector 24', 'सेक्टर 24', '492101', 'residential',
   extensions.ST_GeomFromText('POLYGON((81.7821784 21.1484914, 81.7918216 21.1484914, 81.7918216 21.1575086, 81.7821784 21.1575086, 81.7821784 21.1484914))', 4326), 21.153, 81.787, 'interpolated', true),
  ('Sector 25', 'सेक्टर 25', '492101', 'residential',
   extensions.ST_GeomFromText('POLYGON((81.7867394 21.1419694, 81.7963826 21.1419694, 81.7963826 21.1509866, 81.7867394 21.1509866, 81.7867394 21.1419694))', 4326), 21.146478, 81.791561, 'OSM', true),
  ('Sector 26', 'सेक्टर 26', '492101', 'residential',
   extensions.ST_GeomFromText('POLYGON((81.7878544 21.1344044, 81.7974976 21.1344044, 81.7974976 21.1434216, 81.7878544 21.1434216, 81.7878544 21.1344044))', 4326), 21.138913, 81.792676, 'OSM', true),
  ('Sector 27', 'सेक्टर 27', '492101', 'residential',
   extensions.ST_GeomFromText('POLYGON((81.7801304 21.1364054, 81.7897736 21.1364054, 81.7897736 21.1454226, 81.7801304 21.1454226, 81.7801304 21.1364054))', 4326), 21.140914, 81.784952, 'OSM', true),
  ('Sector 28', 'सेक्टर 28', '492101', 'residential',
   extensions.ST_GeomFromText('POLYGON((81.7725774 21.1338434, 81.7822206 21.1338434, 81.7822206 21.1428606, 81.7725774 21.1428606, 81.7725774 21.1338434))', 4326), 21.138352, 81.777399, 'OSM', true),
  ('Sector 29', 'सेक्टर 29', '492101', 'residential',
   extensions.ST_GeomFromText('POLYGON((81.7772114 21.1293204, 81.7868546 21.1293204, 81.7868546 21.1383376, 81.7772114 21.1383376, 81.7772114 21.1293204))', 4326), 21.133829, 81.782033, 'OSM', true),
  ('Sector 30', 'सेक्टर 30', '492101', 'residential',
   extensions.ST_GeomFromText('POLYGON((81.7867824 21.1264784, 81.7964256 21.1264784, 81.7964256 21.1354956, 81.7867824 21.1354956, 81.7867824 21.1264784))', 4326), 21.130987, 81.791604, 'OSM (pincode approx)', true),
  ('Sector 20', 'सेक्टर 20', '492018', 'residential',
   extensions.ST_GeomFromText('POLYGON((81.7784484 21.1619694, 81.7880916 21.1619694, 81.7880916 21.1709866, 81.7784484 21.1709866, 81.7784484 21.1619694))', 4326), 21.166478, 81.78327, 'OSM (pincode approx)', true),
  ('Sector 19', 'सेक्टर 19', '492030', 'residential',
   extensions.ST_GeomFromText('POLYGON((81.7907224 21.1545254, 81.8003656 21.1545254, 81.8003656 21.1635426, 81.7907224 21.1635426, 81.7907224 21.1545254))', 4326), 21.159034, 81.795544, 'OSM (pincode approx)', true),
  ('Capital Complex', 'कैपिटल कॉम्प्लेक्स', '492018', 'civic',
   extensions.ST_GeomFromText('POLYGON((81.7915168 21.1509790, 81.8050172 21.1509790, 81.8050172 21.1636030, 81.7915168 21.1636030, 81.7915168 21.1509790))', 4326), 21.157291, 81.798267, 'OSM', true),
  ('IIIT Naya Raipur', 'IIIT नया रायपुर', '492101', 'campus',
   extensions.ST_GeomFromText('POLYGON((81.7618383 21.1254885, 81.7695529 21.1254885, 81.7695529 21.1327023, 81.7618383 21.1327023, 81.7618383 21.1254885))', 4326), 21.1290954, 81.7656956, 'Nominatim (pincode approx)', true),
  ('HNLU', 'HNLU', '492101', 'campus',
   extensions.ST_GeomFromText('POLYGON((81.7545239 21.1036754, 81.7622385 21.1036754, 81.7622385 21.1108892, 81.7545239 21.1108892, 81.7545239 21.1036754))', 4326), 21.1072823, 81.7583812, 'Nominatim (pincode approx)', true),
  ('Sector 7', 'सेक्टर 7', '492015', 'residential',
   extensions.ST_GeomFromText('POLYGON((81.7744864 21.1892264, 81.7841296 21.1892264, 81.7841296 21.1982436, 81.7744864 21.1982436, 81.7744864 21.1892264))', 4326), 21.193735, 81.779308, 'OSM (pincode approx)', false),
  ('Sector 2', 'सेक्टर 2', '492015', 'residential',
   extensions.ST_GeomFromText('POLYGON((81.8100504 21.2086004, 81.8196936 21.2086004, 81.8196936 21.2176176, 81.8100504 21.2176176, 81.8100504 21.2086004))', 4326), 21.213109, 81.814872, 'OSM (pincode approx)', false),
  ('Sector 3', 'सेक्टर 3', '492015', 'residential',
   extensions.ST_GeomFromText('POLYGON((81.8214244 21.1977474, 81.8310676 21.1977474, 81.8310676 21.2067646, 81.8214244 21.2067646, 81.8214244 21.1977474))', 4326), 21.202256, 81.826246, 'OSM (pincode approx)', false);

notify pgrst, 'reload schema';
select count(*) as sectors, count(*) filter (where active) as active_sectors from public.sectors;
